CruGlobal/godtools-swift

- godtools-swift/Renderer/Custom Classes/GTFollowupModalView.m
- godtools-swift/Renderer/Custom Classes/GTFollowupThankYouView.m
- godtools-swift/Renderer/Custom Classes/GTInputFieldView.m
- godtools-swift/Renderer/Custom Classes/GTLabel.h
- godtools-swift/Renderer/Custom Classes/GTLabel.m
- godtools-swift/Renderer/Nav Classes/GTFollowupViewController.h
- godtools-swift/Renderer/Nav Classes/GTFollowupViewController.m
- godtools-swift/Renderer/Nav Classes/GTViewController.m
- godtools-swift/Renderer/Parsing Classes/GTAboutViewController.m
- godtools-swift/Renderer/Parsing Classes/GTPageInterpreter.m
Remove deprecated classes and enums in favor of supported versions
> Fix deprecation warnings

- godtools.xcodeproj/project.pbxproj
- godtools/AppDelegate.swift
- godtools/Info.plist
- Add config and info for Fabric and Crashlytics
- Sets build number to 1
- Sets bundle id to org.cru.godtools.beta so app can be distributed along side current prod app
- Sets app name to "GodTools"
> First Beta Build Configuration

- godtools/FlowControllers/PlatformFlowController.swift
- godtools/Localizable.strings
- godtools/Managers/LanguagesManager.swift
- godtools/ViewControllers/BaseViewController.swift
- godtools/ViewControllers/Platform/LanguageSettingsViewController.swift
- godtools/ViewControllers/Platform/LanguagesTableViewController.swift
- godtools/ViewControllers/Platform/LanguagesTableViewController.xib
- godtools/Views/Cells/LanguageTableViewCell.swift
- godtools/Views/Cells/LanguageTableViewCell.xib
This PR adds the style to the languages tableview screen and its cells.
> Add style to languages tableview

- godtools.xcodeproj/project.pbxproj
- godtools/Constants/GTNotifications.swift
- godtools/Localizable.strings
- godtools/ViewControllers/Platform/HomeViewController.swift
- godtools/ViewControllers/Platform/OnboardingViewController.swift
- godtools/ViewControllers/Platform/OnboardingViewController.xib
- godtools/Views/Buttons/TransparentButton.swift
- godtools/Views/Labels/GTLabel.swift
This PR adds the onboarding screen that should appear on the 1st time to the user.
Right now it is appearing every time the user goes into this page. In order to display it only once it will require to add NSUserDefaults maybe, but I didn't add it so it can be tested many times.
> Onboarding screen

- godtools/Info.plist
- godtools/Localizable.strings
- godtools/ViewControllers/MenuViewController.swift
- godtools/ViewControllers/Platform/AddToolsViewController.swift
- godtools/ViewControllers/Tract/TractViewController.swift
Implements small improvements requested by Ann from build 2:
- https://jira.cru.org/browse/GT-282
- https://jira.cru.org/browse/GT-284
- https://jira.cru.org/browse/GT-285
> Build2 minor fixes

- Podfile
- Podfile.lock
- godtools.xcodeproj/project.pbxproj
- godtools/AppDelegate.swift
- godtools/Constants/GTConstants.swift
- godtools/Constants/GTNotifications.swift
- godtools/Managers/DownloadResources/DownloadedResourceManager.swift
- godtools/Managers/LanguagesManager.swift
- godtools/Managers/ToolsManager.swift
- godtools/Managers/TranslationZipImporter.swift
- godtools/Managers/Translations/TranslationResource.swift
- godtools/Managers/Translations/TranslationsManager.swift
- godtools/Models/DownloadedResource+CoreDataClass.swift
- godtools/Models/Language+CoreDataClass.swift
- godtools/Models/Translation+CoreDataProperties.swift
- godtools/ViewControllers/Platform/AddToolsViewController.swift
- godtools/ViewControllers/Platform/ToolDetailViewController.swift
- godtools/ViewControllers/Platform/ToolDetailViewController.xib
- godtools/Views/Cells/HomeToolTableViewCell.swift
- godtools/Views/Cells/HomeToolTableViewCell.xib
- godtools/Views/GTProgressView.swift
- godtools/godtools.xcdatamodeld/godtools.xcdatamodel/contents
Zip files are downloaded and extracted to a common resources folder.
Priority is given to primary and parallel language at the time a resource is downloaded, but is not changed if the user changes languages.
Deleting just flags that translations are not deleted and resources and languages should not be deleted, but does not currently purge resources from disk.
> Handle downloading of XML zip files from Server

- godtools/Localizable.strings
- godtools/Managers/DownloadResources/DownloadedResourceJson.swift
- godtools/Managers/DownloadResources/DownloadedResourceManager.swift
- godtools/Models/DownloadedResource+CoreDataClass.swift
- godtools/Models/DownloadedResource+CoreDataProperties.swift
- godtools/ViewControllers/Platform/ToolDetailViewController.swift
- godtools/Views/Cells/HomeToolTableViewCell.swift
- godtools/godtools.xcdatamodeld/godtools.xcdatamodel/contents
Copyright info and total views.
Show total views data on home view cell and tool detail view
Also show number of languages based on real data on tool detail view
> Track additional fields from API 

- godtools/AppDelegate.swift
- godtools/Managers/DownloadResources/DownloadedResourceManager.swift
- godtools/Managers/ToolsManager.swift
- godtools/Managers/TranslationZipImporter.swift
- godtools/Managers/Translations/TranslationsManager.swift
- godtools/Models/DownloadedResource+CoreDataClass.swift
- godtools/Views/Cells/HomeToolTableViewCell.swift
Handles cases where the latest translation is updated on the API and that information is synced to the device
> Handle updates

- godtools/Info.plist
- godtools/ViewControllers/BaseViewController.swift
- status bar will be shown by default, with option to hide it
- tract view controller will opt to hide it
> Add logic to show light content (white) status bar on all view controllers

- godtools.xcodeproj/project.pbxproj
- godtools/AppDelegate.swift
- godtools/Constants/GTConstants.swift
- godtools/Constants/GTNotifications.swift
- godtools/Managers/DownloadResources/DownloadedResourceManager.swift
- godtools/Managers/FirstLaunchInitializer.swift
- godtools/Managers/GTDataManager.swift
- godtools/Managers/LanguagesManager.swift
- godtools/Managers/ToolsManager.swift
- godtools/Managers/TranslationFileRemover.swift
- godtools/Managers/TranslationZipImporter.swift
- godtools/Managers/Translations/TranslationsManager.swift
- godtools/Models/ReferencedFile+CoreDataClass.swift
- godtools/Models/ReferencedFile+CoreDataProperties.swift
- godtools/Models/Translation+CoreDataProperties.swift
- godtools/ViewControllers/Platform/HomeViewController.swift
- godtools/Views/Cells/HomeToolTableViewCell.swift
- godtools/godtools.xcdatamodeld/godtools.xcdatamodel/contents
Includes changes that shows three resources (KGP, Satisfied and Four Spiritual Laws) by default when the app opens. It also shows English as an available language. Once the app has connected to the API and downloaded the resources from there, it will delete these temporary objects from the database.
Later we will include some default XML and images so that English can be viewed even if the app cannot connect to the API.
> Initial app state

- godtools/ViewControllers/MenuViewController.swift
They will not be supported in this version.
> Remove switches for preview mode and notifications from menu

- godtools/Managers/ToolsManager.swift
- godtools/ViewControllers/Platform/HomeViewController.swift
- creates a helper method to help determine this
> Show normal view or empty view depending on resources available

- godtools/FlowControllers/BaseFlowController.swift
- godtools/FlowControllers/PlatformFlowController.swift
- godtools/ViewControllers/BaseViewController.swift
- godtools/ViewControllers/MenuViewController.swift
- godtools/ViewControllers/MenuViewController.xib
- godtools/ViewControllers/Platform/LanguageSettingsViewController.swift
- godtools/ViewControllers/Tract/TractViewController.swift
- move some methods from PlatformFlowController to BaseFlowController to make this happen
> Enable transition from menu to language settings view

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtoolsTests/Info.plist
> Build Number Bump - 8

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtoolsTests/Info.plist
> Build Number Bump - 10

- godtools/Views/TractElements/TractTextContentProperties.swift
This needs another look for supporting right to left languages
> Fix crash b/c String cannot be converted to NSTextAlignment

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtoolsTests/Info.plist
> Build Number Bump - 11

- godtools/ViewControllers/Platform/LanguageSettingsViewController.xib
- godtools/ViewControllers/Platform/ToolDetailViewController.swift
- godtools/ViewControllers/Tract/TractViewController.swift
GT-331: Move back from Tool Detail to Home after the tool is downloaded or deleted
GT-333: Do not display title if there is only one language available and do not display segmented control if the primary language is the same to the parallel language
GT-334: Remove exclamation image from Language Settings
> Changes on the UI

- godtools.xcodeproj/project.pbxproj
- godtools/FlowControllers/BaseFlowController.swift
- godtools/Info.plist
- godtools/Localizable.strings
- godtools/ViewControllers/MenuViewController.swift
- godtools/ViewControllers/Platform/AboutViewController.swift
- godtools/ViewControllers/Platform/AboutViewController.xib
- godtools/ViewControllers/Platform/WebViewController.swift
- godtools/ViewControllers/Platform/WebViewController.xib
This PR contains:
- GT-326: share GodTools with native Share sheet
- GT-329: add WebView and display GodTools website as temporal page
- GT:327: if the user has configured the email account open mailer for sending a mail, otherwise displays a webview with the contact page
- GT:328: if the user has configured the email account open mailer for sending a mail, otherwise displays a webview with the contact page
- GT:330: a viewcontroller for about, where it has 9 labels with dynamic height inside of a scrollview
> Add actions to menu

- godtools.xcodeproj/project.pbxproj
- godtools/Constants/GTNotifications.swift
- godtools/Localizable.strings
- godtools/ViewControllers/Tract/TractViewController.swift
- godtools/ViewControllers/Tract/TractViewControllerActions.swift
- godtools/Views/TractElements/TractElementFunctions.swift
- godtools/Views/TractElements/TractEmail.swift
- godtools/Views/TractElements/TractEmailActions.swift
- godtools/Views/TractElements/TractEmailProperties.swift
- godtools/Views/TractElements/TractEmails.swift
- godtools/Views/TractElements/TractFormEmailActions.swift
- godtools/Views/TractElements/TractLink.swift
- godtools/XMLContent/KGP/kgp-7.xml
- godtools/XMLContent/KGP/kgp-manifest.xml
This PR adds an idea for how emails can be managed. It gets the email from xml and sends when the action is dispatched.
> GT-298: Sends an email dispatched from tract

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtoolsTests/Info.plist
> Build Number Bump - 12

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtoolsTests/Info.plist
> Build Number Bump - 13

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtoolsTests/Info.plist
> Build Number Bump - 14

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtoolsTests/Info.plist
> Build Number Bump - 15

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtoolsTests/Info.plist
> Build Number Bump - 16

- godtools/Constants/GTNotifications.swift
- godtools/Localizable.strings
- godtools/Managers/ToolsManager.swift
- godtools/Managers/TranslationZipImporter.swift
- godtools/ViewControllers/Platform/HomeViewController.swift
- godtools/ViewControllers/Platform/LanguagesTableViewController.swift
- godtools/ViewControllers/Tract/TractViewControllerContent.swift
- give user option to re-download resources when it appears that a download has failed.
> Handle failed downloads

- godtools/FlowControllers/BaseFlowController.swift
- godtools/Localizable.strings
- godtools/Managers/DownloadResources/DownloadedResourceManager.swift
- godtools/ViewControllers/BaseViewController.swift
- godtools/ViewControllers/Platform/HomeViewController.swift
- godtools/ViewControllers/Platform/LanguagesTableViewController.swift
- godtools/ViewControllers/Platform/ToolDetailViewController.swift
same as #76, just merged to wrong branch
> After download

- godtools/Views/TractElements/TractImageProperties.swift
- godtools/Views/TractElements/TractPageProperties.swift
- godtools/Views/TractElements/TractTextContent+UI.swift
- godtools/Views/TractElements/TractTextContentProperties.swift
- godtools/XMLManagement/XMLManager.swift
Allows for cardTextColor to be set at the page level to override textColor set for the rest of the page or manifest.
Some other small cleanup too
> Card text color

- godtools/Managers/LanguagesManager.swift
- godtools/ViewControllers/Platform/ToolDetailViewController.swift
- fall back to english if there is an issue loading current language
> Show localized description on tool info view

- godtools.xcodeproj/project.pbxproj
- godtools/FlowControllers/BaseFlowController.swift
- godtools/TractClasses/ManifestProperties.swift
- godtools/ViewControllers/Platform/HomeViewController.swift
- godtools/ViewControllers/Tract/TractViewController.swift
- godtools/Views/NavigationBarBackground.swift
- godtools/Views/TractElements/BaseTractElement.swift
- godtools/Views/TractElements/TractPage.swift
- fix typo that prevented color from being loaded from properties 'B' -> 'b'
- use machine generated images with alpha for the background image of nav bars to achieve transparency
> Fix and update nav bar issues

- godtools/ViewControllers/Platform/LanguageSettingsViewController.xib
- godtools/ViewControllers/Platform/OnboardingViewController.xib
Improve layout on a couple screens
> Onboarding layout

- godtools.xcodeproj/project.pbxproj
- godtoolsTests/Info.plist
> Build Number Bump - 18

- godtools/Managers/ToolsManager.swift
- godtools/Views/Cells/HomeToolTableViewCell.xib
- make touchable area of info button 5 pts wider and taller
- wrap language names for longer languages
- wrap resource names for longer resources
> Improvements to tool cell

- godtools/ViewControllers/Platform/HomeViewController.swift
add a refresh control to the home view to download resource updates w/o having to restart the app
> Refresh control

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtoolsTests/Info.plist
> Build Number Bump - 19

- godtools.xcodeproj/project.pbxproj
- godtools/Views/TractElements/BaseTractElement+Functions.swift
- godtools/Views/TractElements/BaseTractElement+StaticFunctions.swift
- godtools/Views/TractElements/TractButton+Actions.swift
- godtools/Views/TractElements/TractCard+Actions.swift
- godtools/Views/TractElements/TractCard+Animations.swift
- godtools/Views/TractElements/TractCard+UITextFieldDelegate.swift
- godtools/Views/TractElements/TractCard.swift
- godtools/Views/TractElements/TractCardProperties.swift
- godtools/Views/TractElements/TractForm+Actions.swift
- godtools/Views/TractElements/TractForm.swift
- godtools/Views/TractElements/TractInput.swift
This PR:
- Adds handlers for textfields
- Adds animations for move the content of the card when the keyboard appears or disappears 
- Adds the dismiss listeners to the card
- Adds the function for hiding the card when the event related to the dismiss listener is dispatched
> Add handlers for textfields and animation for move when keyboard presents and hides

- godtools/Views/TractElements/TractParagraph+UI.swift
- godtools/Views/TractElements/TractParagraph.swift
- godtools/Views/TractElements/TractTabs.swift
The problem was with the margins. I don't know why I did not set those margins, specifically for the paragraph, this change is important because it will affect everything.
> GT-353: Add margin bottom to tabs, and margin top to paragraph

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtoolsTests/Info.plist
> Build Number Bump - 20

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtoolsTests/Info.plist
> Build Number Bump - 21

- godtools/Managers/DownloadResources/DownloadedResourceJson.swift
- godtools/Managers/DownloadResources/DownloadedResourceManager.swift
- godtools/Managers/GTDataManager+Migrations.swift
- godtools/Models/DownloadedResource.swift
- godtools/ViewControllers/Platform/ToolDetailViewController.swift
The server is tracking the resource description, but the iOS client hasn't pulled it in until now.
> Add resource description

- Podfile
- Podfile.lock
- godtools.xcodeproj/project.pbxproj
- godtools/Analtyics/GodToolsAnaltyics.swift
- godtools/Config.swift
- godtools/config.sample.plist
- godtools/godtools-Bridging-Header.h
Adds pod and basic code for tracking AdWords conversions.
> GT-235 AdWords conversion tracking support

- godtools/AppDelegate.swift
- godtools/Managers/FollowUps/FollowUpsManager.swift
Create a function that will sync cached follow ups, attempting 2 more times before giving up.
This method is not called yet, b/c I will call it from the AppDelegate. There are at least two other branches that need merged into the delegate, and it will be conflict-city with if I do it now.
> GT-362 Sync Cached follow ups

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtoolsTests/Info.plist
> Build Number Bump - 22

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtoolsTests/Info.plist
> Build Number Bump - 23

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtoolsTests/Info.plist
> Build Number Bump - 24

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtoolsTests/Info.plist
> Build Number Bump - 25

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtoolsTests/Info.plist
> Build Number Bump - 26

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
- godtools/ViewControllers/Tract/TractViewController.swift
- godtools/ViewControllers/Tract/TractViewControllerActions.swift
Fixes reporting in analytics and an error in the build process.
> Release 5.0.2

- godtools/Views/Cells/HomeToolTableViewCell.swift
- godtools/Views/Cells/LanguageTableViewCell.swift
- godtools/Views/Cells/LanguageTableViewCell.xib
Remove delete icon from languages list b/c users are finding what it does confusing.
> Remove delete icon

- godtools/ViewControllers/MenuViewController.swift
- godtools/Views/Cells/MenuTableViewCell.swift
- godtools/Views/Cells/MenuTableViewCell.xib
- MenuViewController implements the cell delegate
- The controller determines the index path from the cell
- then programatically selects the cell
> Add outlet and delegate to make menu cell buttons work

- godtools/ViewControllers/Platform/LanguageSettingsViewController.xib
Add exclamation point back to language settings view
> Gt 408 reinstate red exclamation point

- godtools.xcodeproj/project.pbxproj
- godtools/Managers/ToolsManager.swift
- godtools/ViewControllers/Tract/TractViewController.swift
- godtools/ViewControllers/Tract/TractViewControllerDataManagement.swift
- godtools/Views/Cells/HomeToolTableViewCell.swift
- godtools/lv.lproj/Localizable.strings
show english resources in tract controller when the resource is not translated into the primary language.
this includes some refactoring of how languages are referenced from the `TractViewController`
> Gt 420 english resources

- godtools.xcodeproj/project.pbxproj
- godtools/Constants/GTSettings.swift
- godtools/Managers/ToolsManager.swift
- godtools/ViewControllers/Tract/TractViewController.swift
- godtools/ViewControllers/Tract/TractViewControllerDataManagement.swift
- godtools/Views/Cells/HomeToolTableViewCell.swift
- godtools/lv.lproj/Localizable.strings
it will default to the first page of the KGP on knowgod.com
> Re-add share link to us KGP

- godtools.xcodeproj/project.pbxproj
- godtools/Info.plist
This fixes broken analytics, which was actually broken due to a file outside of this repo. The config.plist, wasn't copied over to my new dev machine. The result it GA IDs were not pushed in the last update.
> Update prov profile and build number 5.0.8

- godtools/Managers/FollowUps/FollowUpsManager.swift
also includes a fix for swift4 deprecation. we can now access strings directly w/o using 'characters'
> Fabric issue 83

- godtools/Views/Cells/LanguageTableViewCell.swift
Should fix: https://fabric.io/cru/ios/apps/org.cru.godtools/issues/5a26ca2761b02d480dedfd23?time=last-thirty-days
> Use guard let instead of force unwrap to prevent crash

- godtools/Constants/GTNotifications.swift
- godtools/ViewControllers/Platform/HomeViewController.swift
- godtools/ViewControllers/Platform/OnboardingViewController.swift
- godtools/ViewControllers/Platform/OnboardingViewController.xib
- first commit is the actual change. removes multiple buttons and therefore decision point that was confusing/annoying users
- second commit removes `self` references where they aren't necessary.
> Gt 443 modify onboarding screens

- godtools/Managers/LanguagesManager.swift
- godtools/ViewControllers/Platform/LanguagesTableViewController.swift
- godtools/Views/Cells/LanguageTableViewCell.swift
pop back to previous view after selecting language by the download button. also clean up code a bit.
> Gt 444 language setting experience

- Podfile
- Podfile.lock
- godtools.xcodeproj/project.pbxproj
- godtools/Analtyics/GodToolsAnaltyics.swift
- godtools/Managers/ToolsManager.swift
- godtools/ViewControllers/Login/LoginViewController.swift
- godtools/ViewControllers/Platform/HomeViewController.xib
- godtools/ViewControllers/Platform/ToolDetailViewController.xib
- godtools/ViewControllers/Tract/TractViewController.xib
- godtools/Views/Cells/HomeToolTableViewCell.swift
- godtools/Views/Cells/HomeToolTableViewCell.xib
- godtools/Views/Labels/GTLabel.swift
This adds additional line for Tract description as well as some cell reformatting for new design
> Gt 502 testing 2fa- New cell layout

- Podfile
- Podfile.lock
- godtools.xcodeproj/project.pbxproj
- godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
- godtools/App/Services/AppsFlyer/AppsFlyer.swift
- Using Swift Package Manager to install AppsFlyer SDK :)
- Changed AppsFlyer deep linking to run through their new deepLinkDelegate
> GT-1319 Fix deep link not clearing

- godtools/App/Features/Onboarding/OnboardingQuickStartView.swift
- godtools/App/Features/Onboarding/OnboardingQuickStartView.xib
- godtools/App/Features/Onboarding/Views/OnboardingQuickStartCell.swift
- godtools/App/Features/Onboarding/Views/OnboardingQuickStartCell.xib
Hey @reldredge71 added a fade to the quick actions list.  Let me know what you think.
I also updated and flattened the view hierarchy.  A good tip I learned when reading about autolayout is if possible keep the hierarchy as flat as possible, makes it easier to work with and update constraints.
> GT 1309 add fade

- godtools/App/Features/Account/Protocols/AccountItemViewType.swift
- godtools/App/Features/Account/Views/AccountItemCell.swift
- godtools/App/Features/Articles/Views/ArticlesErrorMessageView.swift
- godtools/App/Features/Lessons/Lesson/Views/LessonProgressView.swift
- godtools/App/Features/Tool/Views/ToolNavBar/ToolNavBarView.swift
- godtools/App/Features/Tools/FavoritedToolsView.swift
- godtools/App/Features/Tools/Views/Tool/ToolCell.swift
- godtools/App/Features/Tools/Views/ToolsMenuToolbar/ToolsMenuToolbarView.swift
- godtools/App/Flows/FlowDelegate.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentSection/MobileContentSectionView.swift
- godtools/App/Services/Renderer/Views/Tool/Views/CallToAction/ToolPageCallToActionView.swift
- godtools/App/Services/Renderer/Views/Tool/Views/Card/Animations/ToolPageCardBounceAnimation.swift
- godtools/App/Services/Renderer/Views/Tool/Views/Modal/ToolPageModalView.swift
- godtools/App/Services/Renderer/Views/Training/Views/Page/TrainingPageView.swift
- godtools/App/Share/Protocols/NibBased.swift
- godtools/App/Share/Views/AlertMessageView/AlertMessageViewModelType.swift
- godtools/App/Share/Views/GTSegmentControl/GTSegmentedControl.swift
- godtools/App/Share/Views/PageNavigationCollectionView/PageNavigationCollectionView.swift
protocol implementing class is deprecated in exchange for AnyObject
> GT-1226 Change protocol class to AnyObject

- godtools/App/Flows/TractFlow.swift
Adding deep link navigation between tools
> GT-1342 Allow deep linking between tools

- godtools/App/Features/Onboarding/Views/OnboardingQuickStartCellViewModel.swift
> GT-1309: Fix Link Button Title in QUickStartCells

- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAnimation/MobileContentAnimationView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentStack/MobileContentStackView.swift
- godtools/App/Share/Extensions/UIView+Constraints.swift
- godtools/App/Share/Views/AnimatedView/AnimatedView.swift
- godtools/App/Share/Views/AnimatedView/AnimatedViewModel.swift
- godtools/App/Share/Views/AnimatedView/AnimatedViewModelType.swift
- Setting animation content mode scaleToFill
- Maintaining animation aspect ratio while width fills container 100%
> GT-1000 Fix renderer animation scaling

- godtools/App/Services/Renderer/Analytics/MobileContentAnalytics.swift
- godtools/App/Services/Renderer/Parser/Multiplatform/Models/MultiplatformLessonPage.swift
- godtools/App/Services/Renderer/Parser/Multiplatform/Models/MultiplatformTipPage.swift
- godtools/App/Services/Renderer/Parser/Multiplatform/Models/MultiplatformTractPage.swift
- godtools/App/Services/Renderer/Parser/Protocol/Models/PageModelType.swift
- godtools/App/Services/Renderer/Parser/Xml/NodeParser/Nodes/PageNode.swift
- godtools/App/Services/Renderer/Renderer/MobileContentRendererPageViewFactories.swift
- godtools/App/Services/Renderer/Views/Lesson/ViewFactory/LessonPageViewFactory.swift
- godtools/App/Services/Renderer/Views/Lesson/Views/Page/LessonPageViewModel.swift
- godtools/App/Services/Renderer/Views/Tool/ViewFactory/ToolPageViewFactory.swift
- godtools/App/Services/Renderer/Views/Tool/Views/Page/ToolPageViewModel.swift
Trigger an analytics event on pageDidAppear for Lessons and Tools
> GT-1280: XML Analytics Events for Lesson and Tools Pages

- godtools/App/Features/Lessons/LessonsList/LessonsListViewModel.swift
- godtools/App/Features/Tools/AllToolsViewModel.swift
- godtools/App/Features/Tools/FavoritedToolsViewModel.swift
- godtools/App/Services/RealmDatabase/RealmDatabase.swift
- godtools/App/Services/Resources/RealmResourcesCache/Models/RealmResource.swift
- godtools/App/Services/Resources/ResourcesApi/Models/ResourceModel.swift
- Added isHidden attribute to ResourceModel
- Filtering all tools, favorited tools, and lessons by isHidden
> GT-1369 support resource attr-hidden

- fastlane/.env.default
- godtools.xcodeproj/project.pbxproj
- godtools/fi.lproj/Localizable.strings
- godtools/sv.lproj/Localizable.strings
- Added localization files to Xcode project from project settings
- Added language codes to list of OneSky localization files that are downloaded into the Xcode project
> GT-1444 add swedish and finnish language localizations

- godtools/App/Services/Renderer/Renderer/MobileContentRendererPageViewFactories.swift
- godtools/App/Services/Renderer/Views/ChooseYourOwnAdventure/ViewFactory/ChooseYourOwnAdventurePageViewFactory.swift
- godtools/App/Services/Renderer/Views/MobileContent/ViewFactory/MobileContentPageViewFactory.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentCard/MobileContentCardView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentFlow/MobileContentFlowView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentFlowItem/MobileContentFlowItemView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentFlowRow/MobileContentFlowRow.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentFlowRow/MobileContentFlowRowItem.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentPage/MobileContentContentPageView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentStack/MobileContentStackView.swift
In this PR I added insets to the first 2 pages of the conversation starter.  This was kind of tricky to do.  I ended up for now doing it when the view is instantiated and placed it in the conversation starter view factory since it is specific only to this tool.
I also started adding the shadow to the content cards, but had to disable that for now.  I need a good resolution on how to apply spacing to flow items.
> GT-1450 and started GT-1354 adding shadow to cards

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/ChooseYourOwnAdventure/ChooseYourOwnAdventureView.swift
- godtools/App/Features/ChooseYourOwnAdventure/ChooseYourOwnAdventureViewModel.swift
- godtools/App/Features/ChooseYourOwnAdventure/ChooseYourOwnAdventureViewModelType.swift
- godtools/App/Features/ChooseYourOwnAdventure/Models/ChooseYourOwnAdventureNavBarModel.swift
- godtools/App/Features/ChooseYourOwnAdventure/Models/ChooseYourOwnAdventureNavBarTitleType.swift
- godtools/App/Flows/ChooseYourOwnAdventureFlow.swift
Fixed conversation starter tool navbar to display GodTools if showing single language.
> GT-1451 Fix nav title to display GodTools when set to single language

- godtools/App/Services/Renderer/Parser/Multiplatform/Models/MultiplatformContentText.swift
- godtools/App/Services/Renderer/Parser/Protocol/Models/ContentTextModelType.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentText/MobileContentTextView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentText/MobileContentTextViewModel.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentText/MobileContentTextViewModelType.swift
Take Minimum Height from Multiplatform and apply to MobileContentText
> GT-1341: Implement Minimum Lines in Text Content

- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentCard/MobileContentCardView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentStack/MobileContentStackView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/MobileContentView.swift
- Added shadow to content cards
- Added paddingInsets to MobileContentView base class (currently used with the MobileContentStackView when adding MobileContentViews)
- Fixed place in MobileContentStackView where the bottom contentInset was not getting applied.
> GT-1354 add card shadow and padding on all edges

- godtools.xcodeproj/project.pbxproj
- godtools/App/AppDiContainer.swift
- godtools/App/Services/DeepLinkingService/Parsers/CYOA/CYOADeepLinkParser.swift
- godtools/App/Share/Extensions/Collection+SafeLookup.swift
- godtools/godtools.entitlements
Deep links for Choose Your Own Adventure tools have a deepLinkValue in the form of "tool|cyoa|<resourceAbbreviation>|<languageCode>".  Adding the ability to parse these deep links and route to the correct tool.
> GT-1415: Handle Choose Your Own Adventure Tool Deep Links

- .gitignore
Added *.orig to ignore auto generated files from merge conflicts on project.pbxproj
> Add *.orig to gitignore

- README.md
Made some updates to the ReadMe to include GodTools architectural pattern which is helpful in onboarding new developers.
> GT update readme

- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentButton/MobileContentButtonViewModel.swift
- Using textScale from Button text and falling back to Button textScale
> GT-1367 Fix button text scale

- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentMultiSelectOption/MobileContentMultiSelectOptionView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentMultiSelectOption/MobileContentMultiSelectOptionViewModel.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentMultiSelectOption/MobileContentMultiSelectOptionViewModelType.swift
Added support for flat MultiSelectOption style which will not render a shadow on the view.
> GT-1431 Add support for flat multi select option

- godtools/App/Services/Renderer/Views/ChooseYourOwnAdventure/ViewFactory/ChooseYourOwnAdventurePageViewFactory.swift
- godtools/App/Services/Renderer/Views/MobileContent/ViewFactory/MobileContentPageViewFactory.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentCard/MobileContentCardView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentFlow/MobileContentFlowView.swift
Removed vertical spacing from the flow element and instead apply padding and content insets to mobile content card
> GT-1513 fix flow item spacing

- godtools/App/Services/DeepLinkingService/GodToolsManifest/GodToolsDeepLinkingManifest.swift
- godtools/App/Services/ShortcutItems/ToolShortcutItem.swift
PR fixes home screen quick launch.  Needed to add the parser and also lowercase the tool shortcut item scheme GodTools to godtools.
> GT-1573 Fix home screen quick launch

- godtools/App/AppDiContainer.swift
- godtools/App/Features/LanguagesList/Domain/GetToolLanguagesUseCase/GetToolLanguagesUseCase.swift
- godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
This PR uses the language's translated language name in the languages list.
> GT-1627 Use language translatedLanguageName in languages list

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/Models/ToolDetailsSegmentType.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsView.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
This PR adds selection for About and Versions and updates the view in ToolDetails based on selection
> GT-1418 about versions selection

- godtools/App/Services/Resources/ResourcesApi/Models/ResourceType.swift
- godtools/App/Services/Resources/ResourcesCache.swift
- godtools/App/Share/Domain/Extensions/Array+ResourceModel.swift
https://jira.cru.org/browse/GT-1658
Also solves https://jira.cru.org/browse/GT-1664
> GT-1658 all tools meta tool filtering

- godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
Update swift packages OktaAuthentication to version 1.2.3
> GT-1634 Update OktaAuthentication swift package

- Podfile.lock
- godtools.xcodeproj/project.pbxproj
- godtools/App/Services/RealmDatabase/RealmDatabase.swift
- godtools/App/Services/Resources/RealmResourcesCache/Models/RealmResource.swift
- godtools/App/Services/Resources/ResourcesApi/Models/DefaultVariantData.swift
- godtools/App/Services/Resources/ResourcesApi/Models/ResourceModel.swift
- godtools/App/Services/Resources/ResourcesApi/Models/ResourceModelType.swift
- godtools/App/Services/Resources/ResourcesCache.swift
- godtools/App/Share/Domain/UseCases/GetToolVersionsUseCase/GetToolVersionsUseCase.swift
https://jira.cru.org/browse/GT-1668
> GT-1668 decode default variant relationship

- godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsView.swift
https://jira.cru.org/browse/GT-1630
> GT-1630 match spacing from All Tools on All Favorites

- godtools/App/Features/ToolDetails/ToolDetailsViewModel.swift
Set selected tool version to tool in tool details instead of default variant
> GT-1676 Update selected tool version to match tool loaded in tool details

- godtools/App/Features/ToolDetails/Subviews/ToolDetailsAboutView.swift
- godtools/App/Features/ToolDetails/ToolDetailsView.swift
- godtools/App/Features/ToolDetails/ToolDetailsViewModel.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/Base.lproj/Localizable.strings
This PR adds the tools available languages to the about section of ToolDetails.
> GT-1667 Add available languages to ToolDetails about section

- godtools/App/Features/Tools/SwiftUI/AllTools/ToolCategoriesView/ToolCategoriesView.swift
https://jira.cru.org/browse/GT-1704
> GT-1704 explicitly define category grid height to fix iOS 13.4 bug

- godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/SubViews/ToolCardTitleView.swift
- godtools/App/Share/SwiftUI Views/LessonCardView/LessonCardView.swift
- godtools/App/Share/SwiftUI Views/LessonCardView/ViewModels/MockLessonCardViewModel.swift
- godtools/App/Share/SwiftUI Views/ResourceCard Subviews/ResourceCardLanguageView.swift
🛑 Branched off of #1267 so comparing with that for now
https://jira.cru.org/browse/GT-1685
> GT-1685 line limits on resource cards

- godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/FavoriteToolsViewModel.swift
https://jira.cru.org/browse/GT-1709
Some of my best work right here 😄
> GT-1709 allow 5 favorites to be shown

- godtools/App/Features/Lessons/Lessons/LessonsContentViewModel.swift
- godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentViewModel.swift
- godtools/App/Features/Tools/SwiftUI/AllTools/ToolSpotlightView/ViewModels/ToolSpotlightViewModel.swift
- godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsView.swift
- godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsViewModel.swift
- godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Services/Analytics/AnalyticsConstants.swift
https://jira.cru.org/browse/GT-1696
https://jira.cru.org/browse/GT-1697
> Gt 1697 tools analytics

- Podfile
- Podfile.lock
This includes the new accordion analytics properties
> upgrade shared parser to 0.6.1-SNAPSHOT

- Podfile.lock
- godtools/App/Features/Lessons/Lessons/LessonsListView/LessonsListView.swift
- godtools/App/Features/Tools/SwiftUI/AllTools/ToolSpotlightView/Subviews/SpotlightTitleView.swift
https://jira.cru.org/browse/GT-1729
> increase subtitle font size

- godtools/App/Features/Lessons/Lessons/LessonsContentViewModel.swift
- godtools/App/Features/ToolDetails/ToolDetailsViewModel.swift
- godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentViewModel.swift
- godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsViewModel.swift
- godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
- godtools/App/Services/Analytics/AnalyticsConstants.swift
https://jira.cru.org/browse/GT-1751
Updated analytics events based on Steve's slides: https://docs.google.com/presentation/d/15_9VEn6xWa-5phB2iAWk8wK5-Iz2kboQk2EtMfI8_D0/edit?usp=sharing
> GT-1751 analytics fixes

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
- godtools/App/Share/Extensions/Publisher+ReceiveOnMain.swift
https://jira.cru.org/browse/GT-1761
> GT-1761 receive on main if not already on main

- godtools/App/Share/Domain/UseCases/GetOnboardingQuickLinksEnabledUseCase/GetOnboardingQuickLinksEnabledUseCase.swift
- godtools/App/Share/LanguageCodes.swift
https://jira.cru.org/browse/GT-1597
> GT-1597 include spanish in quick links

- godtools/App/Features/Languages/ChooseLanguage/ChooseLanguageViewModel.swift
- godtools/App/Features/Languages/LanguageSettings/LanguageSettingsViewModel.swift
- godtools/App/Features/SetupParallel/Views/ParallelLanguageListViewModel.swift
- godtools/App/Features/ToolDetails/Subviews/VersionsCard/ToolDetailsVersionsCardViewModel.swift
- godtools/App/Features/ToolDetails/ToolDetailsViewModel.swift
- godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
- godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
- godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
- godtools/App/Share/SwiftUI Views/LessonCardView/ViewModels/LessonCardViewModel.swift
https://jira.cru.org/browse/GT-1764
> GT-1764 use new receiveOnMain in viewModel publishers

- Podfile.lock
- godtools.xcodeproj/project.pbxproj
- godtools/App/AppDiContainer.swift
- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentView.swift
- godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsList.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Share/Data/FavoritingToolMessageCache/FavoritingToolMessageCache.swift
Moved ```FavoritingToolMessageCache.swift``` to ```Share/Data/``` and moved allocation of this class to ```AppDataLayerDependencies.swift```.
> GT Moved FavoritingToolMessageCache

- godtools.xcodeproj/xcshareddata/xcschemes/godtools.xcscheme
- godtoolsUITests/godtoolsUITests.swift
Disabling the GodToolsUIRecording test and godtoolsUITest testExample() method which wasn't doing anything at the moment.
> GT-Remove GodTools UIRecording test

- godtools/App/Flows/App/AppFlow.swift
This PR ensures that navigation to the lessons list occurs after viewing a lesson.
> GT-1494 navigate to lessons list after viewing a lesson.

- Podfile
- Podfile.lock
- godtools.xcodeproj/project.pbxproj
- godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
- godtools/App/Features/Onboarding/Views/OnboardingTutorialIntroView.swift
- godtools/App/Features/ToolSettings/ShareToolScreenTutorial/ShareToolScreenTutorialView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentEmbeddedVideo/MobileContentEmbeddedVideoView.swift
- godtools/App/Share/SwiftUI Views/VideoView/VideoView.swift
- godtools/App/Share/SwiftUI Views/VideoView/VideoViewCoordinator.swift
- godtools/App/Share/Views/TutorialCell/TutorialCell.swift
- godtools/App/Share/Views/TutorialPagerView/TutorialPagerView.swift
- godtools/App/Share/Views/VideoPlayerView/VideoPlayerView.swift
Fixing signing error on Xcode 14 caused by the youtube-ios-player-helper pod.
> remove youtube pod and install as a swift package

- godtools/App/Features/Tools/ToolsMenu/Views/ToolsMenuToolbar/Views/ToolsMenuToolbarItemView.swift
> GT-1594 Darken tool menu text

- godtools/App/Share/Domain/UseCases/GetAllFavoritedToolsUseCase/GetAllFavoritedToolsUseCase.swift
https://jira.cru.org/browse/GT-1715
> GT-1715 sort favorited resources by language availability

- godtools/App/AppDiContainer.swift
- godtools/App/Flows/DownloadToolTranslations/DownloadToolTranslationsFlow.swift
- godtools/App/Share/Data/FavoritedResourcesRepository/Cache/FavoritedResourcesCache.swift
- godtools/App/Share/Data/FavoritedResourcesRepository/FavoritedResourcesRepository.swift
This PR removes the FavoritedResourcesCache reference in AppDiContainer and the Observables since those have been replaced by Combine and FavoritedResourcesRepository.
> GT-1825 Removed Observables on FavoritedResourcesCache

- Podfile
- Podfile.lock
- godtools/App/Share/Data/TranslationsRepository/ManifestParser/ParseTranslationManifestForRenderer.swift
This update just has some internal restructuring. This version will include user activity/badges business logic
> upgrade the shared library to 0.8.0-SNAPSHOT

- godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
https://jira.cru.org/browse/GT-1818
> GT-1802 translation fix

- godtools/App/Features/Dashboard/Presentation/Dashboard/DashboardTabBarView/DashboardTabItem.swift
https://jira.cru.org/browse/GT-1834 (Justin's request in comments)
> increase dashboard tab font size to 14

- godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/ToolDetailsAboutView.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
- godtools/App/Share/Data/RealmDatabase/RealmDatabaseProductionConfiguration.swift
- godtools/App/Share/Data/TranslationsRepository/Api/Models/TranslationModel.swift
- godtools/App/Share/Data/TranslationsRepository/Api/Models/TranslationModelType.swift
- godtools/App/Share/Data/TranslationsRepository/Cache/Models/RealmTranslation.swift
The new translations attributes are currently only available on the stage renderer testing tool in English.
> GT-1803 tool details accordion

- Podfile
- Podfile.lock
- godtools.xcodeproj/project.pbxproj
- godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
- godtools/App/Share/Common/FileCache/FileCache+SSZipArchive.swift
Removed SSZipArchive 2.40 from Podfile and adding via SPM (ZipArchive 2.5.0).
> GT Remove SSZipArchive and add via SPM

- godtools/App/Services/Renderer/Views/Tool/Views/Cards/ToolPageCardsView.swift
- godtools/App/Services/Renderer/Views/Tool/Views/Page/ToolPageViewModel.swift
- godtools/App/Share/Views/TutorialCell/TutorialCell.swift
- godtools/App/Share/Views/VideoPlayerView/VideoPlayerView.swift
This PR finishes up removal of warnings under the godtools target.
> GT-1896 finish remove warnings

- godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
- godtools/App/Share/SwiftUI Views/TextWithLinks/TextWithLinks.swift
Call layoutIfNeeded() to force layout update.
> GT-1917 Fix Tool Details about text clipped

- godtools/App/Flows/App/AppFlow.swift
This PR makes a naming change to notification observers in AppFlow.swift.  Naming is more specific to the type of observers being added and handled.
- Changed the ```observersAdded``` to ```uiApplicationLifeCycleObserversAdded```.
- Changed ```handleNotification``` to ```handleUIApplicationLifeCycleNotification```.
- Moved methods into MARKED extensions.
> GT-Change observer naming in AppFlow

- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentTab/MobileContentTabViewModel.swift
minor change needed before I can merge https://github.com/CruGlobal/kotlin-mpp-godtools-tool-parser/pull/410
> update the Tab renderer to use getAnalyticsEvents()

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/Articles/Presentation/ArticlesWeb/ArticleWebView.swift
- godtools/App/Features/Articles/Presentation/ArticlesWeb/ArticleWebView.xib
- godtools/App/Features/Articles/Presentation/ArticlesWeb/ArticleWebViewModel.swift
- godtools/App/Features/Articles/Presentation/ArticlesWeb/ArticleWebViewState.swift
This PR makes the following changes to ArticleWebView:
- Adds method to ArticleWebViewModel that will stop a current WKWebView load request.
- Adds a view state (loadingArticle, errorMessage, viewingArticle) that the ArticleWebView can observe.
- Adds a timer which will change the view state to viewingArticle after 2 seconds of loading url request for the WKWebView. (In some devices the WKNavigationDelegate didFinish method wasn't firing).
> GT-1963 fix article loading

- godtools/App/Features/Menu/MenuStringKeys.swift
> GT-2051 correct lesson completions string key

- godtools/App/Features/Menu/Presentation/Menu/MenuView.swift
- godtools/App/Features/Menu/Presentation/Menu/MenuViewModel.swift
Localize strings for menu section titles and menu option titles
> GT-2058 Add localized strings for new menu

- godtools/App/Flows/App/AppFlow.swift
For some reason using CGAffineTransform seemed to be causing a UI bug with SwiftUI.
> GT-2080 Remove transform animation and instead animate UIView frame.

- .github/workflows/download_onesky_translations.yml
Noticed this PR was failing at Create Pull Request step so I updated to use the same personal access token MPDXiOSLib is using.
Ran this workflow here -> https://github.com/CruGlobal/godtools-swift/actions/runs/5657524440
> Remove Xcode select and change github token

- godtools/App/Features/Dashboard/Presentation/AllYourFavoriteTools/AllYourFavoriteToolsView.swift
- godtools/App/Features/Dashboard/Presentation/Favorites/Subviews/YourFavoriteTools/YourFavoriteToolsView.swift
- godtools/App/Features/Dashboard/Presentation/Tools/Subviews/ToolCard/ToolCardView.swift
- godtools/App/Features/Dashboard/Presentation/Tools/Subviews/ToolSpotlight/ToolSpotlightView.swift
- godtools/App/Features/Dashboard/Presentation/Tools/ToolsView.swift
Hide spotlight tool category in ToolCardView.
> GT-2082 Fix spotlight tool category

- .github/workflows/build.yml
Revisiting to see if I can get Fastlane scan to work with Code coverage.  https://jira.cru.org/browse/GT-2043
> GT-2043 Run tests via Fastlane

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/Onboarding/Presentation/OnboardingTutorial/OnboardingTutorialView.swift
- godtools/App/Features/Onboarding/Presentation/OnboardingTutorial/OnboardingTutorialViewModel.swift
- godtools/App/Features/Onboarding/Presentation/OnboardingTutorial/Subviews/ChooseAppLanguageButton/ChooseAppLanguageButton.swift
- godtools/App/Features/Onboarding/Presentation/OnboardingTutorial/Subviews/ChooseAppLanguageCenteredHorizontally/ChooseAppLanguageCenteredHorizontallyView.swift
- godtools/App/Flows/ChooseAppLanguageNavigation/ChooseAppLanguageNavigationFlow.swift
- godtools/App/Flows/Flow/FlowStep.swift
- godtools/App/Flows/LanguageSettings/LanguageSettingsFlow.swift
- godtools/App/Flows/Onboarding/OnboardingFlow.swift
- godtools/App/Share/Application/ImageCatalog/ImageCatalog.swift
This PR just adds the choose language button to the onboarding screen.  Still need to populate the button title and have it animate in etc.  Will work that in a separate ticket.
> GT-2128 Add choose language button to onboarding screen

- godtools/App/Features/AppLanguage/Data/AppLanguagesRepository/AppLanguagesRepository.swift
Hey @rachaelblue I had the original list commented out and was only including ar and en.  Updated to include more languages.  Might be nice to see more languages as you implement that list.
> GT-2122 Add more app languages 

- godtools.xcodeproj/project.pbxproj
- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
- godtools/App/Features/Onboarding/Data-DomainInterface/GetOnboardingQuickStartSupportedLanguagesRepository.swift
- godtools/App/Features/Onboarding/DependencyContainer/OnboardingDataLayerDependencies.swift
- godtools/App/Features/Onboarding/DependencyContainer/OnboardingDomainLayerDependencies.swift
- godtools/App/Features/Onboarding/Domain/Interface/GetOnboardingQuickStartSupportedLanguagesRepositoryInterface.swift
- godtools/App/Features/Onboarding/Domain/UseCases/GetOnboardingQuickStartIsAvailableUseCase.swift
- godtools/App/Share/Data-DomainInterface/GetLaunchCountRepository.swift
- godtools/App/Share/Domain/Interface/GetLaunchCountRepositoryInterface.swift
- godtools/App/Share/Domain/UseCases/GetLaunchCountUseCase.swift
- godtoolsTests/App/Features/Onboarding/Data-DomainInterface/TestsGetLaunchCountRepository.swift
- godtoolsTests/App/Features/Onboarding/Data-DomainInterface/TestsGetOnboardingQuickStartInterfaceStringsRepository.swift
- godtoolsTests/App/Features/Onboarding/Data-DomainInterface/TestsGetOnboardingQuickStartSupportedLanguagesRepository.swift
- godtoolsTests/App/Features/Onboarding/Data-DomainInterface/TestsGetOnboardingTutorialInterfaceStringsRepository.swift
- godtoolsTests/App/Features/Onboarding/Data-DomainInterface/TestsGetOnboardingTutorialViewedRepository.swift
- godtoolsTests/App/Features/Onboarding/Domain/UseCaseTests/GetOnboardingQuickStartInterfaceStringsUseCaseTests.swift
- godtoolsTests/App/Features/Onboarding/Domain/UseCaseTests/GetOnboardingQuickStartIsAvailableUseCaseTests.swift
- godtoolsTests/App/Features/Onboarding/Domain/UseCaseTests/GetOnboardingTutorialInterfaceStringsUseCaseTests.swift
- godtoolsTests/App/Features/Onboarding/Domain/UseCaseTests/GetOnboardingTutorialIsAvailableUseCaseTests.swift
Added some behavior tests for:
- Testing onboarding tutorial interface strings when switching app language from English to Spanish.
- Testing if the onboarding tutorial is available when launch count is 1 and the tutorial hasn't been viewed.
- Testing onboarding quick start interface strings when switching app language from English to Spanish.
- Testing onboarding quick start screen is available when the app language is a supported language for quick start.
> GT-Add some onboarding use cases tests

- godtools/App/Features/Dashboard/Presentation/Tools/ToolsViewModel.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsView.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Flows/Flow/FlowStep.swift
Tool details language will either be the injected tool language, in this case the tool filter language from tools, or if null the current app language.
> GT-2162 connect tool details to tool filter selection

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/ToolSettings/Data/ToolSettingsRepository/Cache/RealmToolSettings.swift
- godtools/App/Features/ToolSettings/Data/ToolSettingsRepository/Cache/RealmToolSettingsCache.swift
- godtools/App/Features/ToolSettings/Data/ToolSettingsRepository/ToolSettingsDataModel.swift
- godtools/App/Features/ToolSettings/Data/ToolSettingsRepository/ToolSettingsRepository.swift
- godtools/App/Share/Data/RealmDatabase/Configuration/RealmDatabaseProductionConfiguration.swift
Adding a repository and realm cache for tool settings.
> GT-2224 Add tool settings repository and realm cache

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/ToolSettings/Data-DomainInterface/DeleteToolSettingsParallelLanguageRepository.swift
- godtools/App/Features/ToolSettings/Data-DomainInterface/GetToolSettingsParallelLanguageRepository.swift
- godtools/App/Features/ToolSettings/Data-DomainInterface/GetToolSettingsPrimaryLanguageRepository.swift
- godtools/App/Features/ToolSettings/Data-DomainInterface/StoreToolSettingsParallelLanguageRepository.swift
- godtools/App/Features/ToolSettings/Data-DomainInterface/StoreToolSettingsPrimaryLanguageRepository.swift
- godtools/App/Features/ToolSettings/Domain/Entities/ToolSettingsToolLanguageDomainModel.swift
- godtools/App/Features/ToolSettings/Domain/Interfaces/DeleteToolSettingsParallelLanguageRepositoryInterface.swift
- godtools/App/Features/ToolSettings/Domain/Interfaces/GetToolSettingsParallelLanguageRepositoryInterface.swift
- godtools/App/Features/ToolSettings/Domain/Interfaces/GetToolSettingsPrimaryLanguageRepositoryInterface.swift
- godtools/App/Features/ToolSettings/Domain/Interfaces/StoreToolSettingsParallelLanguageRepositoryInterface.swift
- godtools/App/Features/ToolSettings/Domain/Interfaces/StoreToolSettingsPrimaryLanguageRepositoryInterface.swift
- godtools/App/Features/ToolSettings/Domain/UseCases/DeleteToolSettingsParallelLanguageUseCase.swift
- godtools/App/Features/ToolSettings/Domain/UseCases/GetToolSettingsParallelLanguageUseCase.swift
- godtools/App/Features/ToolSettings/Domain/UseCases/GetToolSettingsPrimaryLanguageUseCase.swift
- godtools/App/Features/ToolSettings/Domain/UseCases/SetToolSettingsParallelLanguageUseCase.swift
- godtools/App/Features/ToolSettings/Domain/UseCases/SetToolSettingsPrimaryLanguageUseCase.swift
- Adds use cases and dependency inversion for retrieving the tool settings primary and parallel languages
- Adds use cases and dependency inversion for setting the tool settings primary and parallel languages
- Adds use case and dependency inversion for deleting the tool settings parallel language
> GT-2224 Adding tool settings use cases for retrieving and storing languages

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/Dashboard/Presentation/ChooseYourOwnAdventure/ChooseYourOwnAdventureView.swift
- godtools/App/Features/Dashboard/Presentation/ChooseYourOwnAdventure/ChooseYourOwnAdventureViewModel.swift
- godtools/App/Features/Dashboard/Presentation/Tool/ToolView.swift
- godtools/App/Features/Lessons/Presentation/Lesson/LessonView.swift
- godtools/App/Flows/ChooseYourOwnAdventure/ChooseYourOwnAdventureFlow.swift
- godtools/App/Flows/Lesson/LessonFlow.swift
- godtools/App/Flows/Tract/TractFlow.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesView.swift
- godtools/App/Share/Views/Navigation/NavigationBar/NavBarItems/NavBarItem/ButtonsWithImage/AppHomeBarItem.swift
Updated the choose your own adventure view navigation bar to be configured from the flow.  Currently the home button and back button is toggled.  
Will need to fix this in right to left language layouts which will be part of a separate ticket.
> GT-2238 Update choose your own adventure to show either home button or back button.

- godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
- godtools/App/Features/Dashboard/Domain/UseCases/GetOptInOnboardingBannerEnabledUseCase/GetOptInOnboardingBannerEnabledUseCase.swift
- godtools/App/Features/Dashboard/Presentation/Dashboard/DashboardPresentationLayerDependencies.swift
- godtools/App/Features/Dashboard/Presentation/Favorites/FavoritesView.swift
- godtools/App/Features/Dashboard/Presentation/Favorites/FavoritesViewModel.swift
- godtools/App/Features/Menu/Presentation/Menu/MenuView.swift
- godtools/App/Features/Menu/Presentation/Menu/MenuViewModel.swift
- godtools/App/Share/Domain/UseCases/GetOptInOnboardingTutorialAvailableUseCase/GetOptInOnboardingTutorialAvailableUseCase.swift
Updated the UseCase to take in the app language rather than checking the device language when determining if the opt in tutorial is available.
> GT-2242 Updated to show menu tutorial and banner when app language is english

- godtools/App/Features/Dashboard/Presentation/ChooseYourOwnAdventure/ChooseYourOwnAdventureViewModel.swift
- godtools/App/Features/Dashboard/Presentation/Tool/ToolViewModel.swift
- godtools/App/Flows/ChooseYourOwnAdventure/ChooseYourOwnAdventureFlow.swift
- godtools/App/Flows/Tract/TractFlow.swift
- godtools/App/Share/Views/NavBarSelector/NavBarSelectorView.swift
- godtools/App/Share/Views/Navigation/NavigationBar/AppNavigationBar.swift
This change makes it so the tools language selector in the navigation bar is updated when languages change from tool settings.
> GT-2239 Make languageNames Publishable 

- godtools/App/Features/ToolDetails/Data-DomainInterface/GetToolDetailsMediaRepository.swift
Was pulling the tool details banner image from the incorrect resource.
> GT-2245 Get the tool details banner image from attr banner about

- godtools/App/Share/Data/TranslatedLanguageNameRepository/Sync/TranslatedLanguageNameRepositorySync.swift
Remove call to backgroundRealmPublisher in flatMap
> GT-2256 Fix Realm Crash

- godtools/App/Flows/ChooseYourOwnAdventure/ChooseYourOwnAdventureFlow.swift
- godtools/App/Flows/Tract/TractFlow.swift
Update tracts and choose your own adventure tools to have the navigation bar layout direction reflect the app language
> GT-2239 Have navigation bar layout direction follow the app language

- godtools/App/Features/ToolDetails/Data-DomainInterface/GetToolDetailsRepository.swift
- godtools/App/Features/ToolDetails/Domain/Entities/ToolVersionDomainModel.swift
- godtools/App/Features/ToolDetails/Domain/Interface/GetToolDetailsRepositoryInterface.swift
- godtools/App/Features/ToolDetails/Domain/UseCases/ViewToolDetailsUseCase.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/VersionsCard/ToolDetailsVersionsCardView.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/VersionsCard/ToolDetailsVersionsCardViewModel.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
- Translate tool details interface strings in app language
- Include parallel language in tool versions
> GT-2162 Translate tool details interface strings in app language

- godtools/App/Features/AppLanguage/Data/UserAppLanguageRepository/UserAppLanguageRepository.swift
- godtools/App/Features/AppLanguage/DependencyContainer/AppLanguageFeatureDataLayerDependencies.swift
- godtools/App/Flows/ToolNavigation/ToolNavigationFlow.swift
- godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/DetermineToolTranslationsToDownload/DetermineDeepLinkedToolTranslationsToDownload.swift
Removed reference to deprecated GetSettingsPrimaryLanguageUseCase and updated Tool Deeplinking to fallback to app language.
> GT-2136 remove deprecated settings primary language dependency

- godtools/App/Share/Data-DomainInterface/Supporting/GetTranslatedToolName/GetTranslatedToolName.swift
- godtools/App/Share/Data/RealmDatabase/Configuration/RealmDatabaseProductionConfiguration.swift
- godtools/App/Share/Data/ResourcesRepository/Api/Models/ResourceModel.swift
- godtools/App/Share/Data/ResourcesRepository/Api/Models/ResourceModelType.swift
- godtools/App/Share/Data/ResourcesRepository/Cache/Models/RealmResource.swift
- Add attrDefaultLocale to ResourceModel and parse as attr-default-locale from mobile-content-api.
- In GetTranslatedToolName fallback to attrDefaultLocale.
> GT-2292 update tool titles for app language and default language

- .github/workflows/update_spm_dependencies.yml
- fastlane/Pluginfile
Remove check for dependencies changed
> Add firebase app distribution plugin

- godtools/App/Features/Dashboard/Presentation/Tool/ToolViewModel.swift
Adding analytics tracking when tool options is tapped.
> GT-2024 add analytics tracking for tool options

- godtools.xcodeproj/project.pbxproj
Update analytics logging to exclude arm64 for any simulator
Update display name for production, staging, and analytics logging
> GT update analytics-logging scheme

- godtools/App/Features/AppLanguage/Data-DomainInterface/GetDownloadableLanguagesListRepository.swift
- godtools/App/Features/AppLanguage/Data/ToolLanguageDownloader/ToolLanguageDownloader.swift
- godtools/App/Features/ToolsFilter/Data-DomainInterface/GetToolFilterCategoriesRepository.swift
- godtools/App/Features/ToolsFilter/Data-DomainInterface/GetToolFilterLanguagesRepository.swift
- godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
- godtools/App/Share/Data/ResourcesRepository/Filter/ResourcesFilter.swift
- godtoolsTests/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCacheTests.swift
Changed attribute names to hopefully better reflect that these attributes belong to the LanguageModel which comes from mobile-content-api.
- Changed ```languageId``` to ```languageModelId```. 
- Changed ```languageCode``` to ```languageModelCode```.
> GT-2343 Changed some attribute naming ResourcesFilter

- godtools/App/Features/ToolsFilter/Data-DomainInterface/GetToolFilterLanguagesRepository.swift
Somehow weren't being sorted at all 🤦‍♀️
> GT-2335 sort language filter list

- godtools/App/DependencyContainer/AppDiContainer.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Flows/ChooseYourOwnAdventure/ChooseYourOwnAdventureFlow.swift
- godtools/App/Flows/Lesson/LessonFlow.swift
- godtools/App/Flows/ToolNavigation/ToolNavigationFlow.swift
- godtools/App/Flows/Tract/TractFlow.swift
- godtools/App/Services/Renderer/Navigation/MobileContentRendererNavigation.swift
- godtools/App/Services/Renderer/Renderer/MobileContentPageRenderer.swift
- godtools/App/Services/Renderer/Renderer/MobileContentRenderedPageContext.swift
- godtools/App/Services/Renderer/Renderer/MobileContentRenderer.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentEmbeddedVideo/MobileContentEmbeddedVideoViewModel.swift
Update renderer youtube videos to support app language.
> GT-2353 video options in app language

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/LessonEvaluation/Data-DomainInterface/GetSpiritualConversationReadinessScale.swift
- godtools/App/Features/LessonEvaluation/DependencyContainer/LessonEvaluationFeatureDataLayerDependencies.swift
- godtools/App/Features/LessonEvaluation/DependencyContainer/LessonEvaluationFeatureDomainLayerDependencies.swift
- godtools/App/Features/LessonEvaluation/Domain/Entities/LessonEvaluationScaleDomainModel.swift
- godtools/App/Features/LessonEvaluation/Domain/Entities/SpiritualConversationReadinessScaleDomainModel.swift
- godtools/App/Features/LessonEvaluation/Domain/Interface/GetSpiritualConversationReadinessScaleInterface.swift
- godtools/App/Features/LessonEvaluation/Domain/UseCases/DidChangeScaleForSpiritualConversationReadinessUseCase.swift
- godtools/App/Features/LessonEvaluation/Presentation/LessonEvaluation/LessonEvaluationView.swift
- godtools/App/Features/LessonEvaluation/Presentation/LessonEvaluation/LessonEvaluationViewModel.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Share/SwiftUI Views/ScaleValueSlider/ScaleValue.swift
- godtools/App/Share/SwiftUI Views/ScaleValueSlider/ScaleValueSliderView.swift
- godtoolsTests/App/Features/LessonEvaluation/Data-DomainInterface/GetSpiritualConversationReadinessScaleTests.swift
- When evaluating a lesson and viewing the ready to share faith scale (1 to 10) the scale numbers will now be translated in the app language.
- Added tests for lesson evaluation ready to share faith scale.
> GT-2363 translate lesson evaluation ready to share faith scale number in app language

- godtools.xcodeproj/project.pbxproj
- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/App/Features/AppLanguage/Data-DomainInterface/StoreInitialAppLanguage.swift
- godtools/App/Features/AppLanguage/DependencyContainer/AppLanguageFeatureDataLayerDependencies.swift
- godtools/App/Share/Application/DeviceSystemLanguage/DeviceSystemLanguage.swift
- godtools/App/Share/Application/DeviceSystemLanguage/DeviceSystemLanguageInterface.swift
- godtoolsTests/App/Features/AppLanguage/Data-DomainInterface/SearchAppLanguageInAppLanguagesListRepositoryTests.swift
- godtoolsTests/App/Features/AppLanguage/Data-DomainInterface/StoreInitialAppLanguageTests.swift
- godtoolsTests/App/Share/Application/DeviceSystemLanguage/MockDeviceSystemLanguage.swift
- Add tests for storing initial app language.
- Add tests for searching app languages list.
> GT add app language feature tests

- godtools/App/Features/ToolsFilter/Data-DomainInterface/GetToolFilterCategoriesRepository.swift
- godtools/App/Features/ToolsFilter/Data-DomainInterface/GetToolFilterLanguagesRepository.swift
- godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
- godtools/App/Share/Data/ResourcesRepository/ResourcesRepository.swift
This was super nice!  Will have to remember that Realm feature.
> GT-2341 get distinct categories from realm

- godtools.xcodeproj/project.pbxproj
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/Models/MobileContentAccordionSectionPositionState.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentStack/MobileContentStackView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentStack/Models/MobileContentStackPositionState.swift
This PR adds position states for the content stack view scroll position and accordion section view is hidden in order to set the content stack scroll position and whether an accordion section is hidden when toggling the primary and parallel language in a tool.
> GT-2373 Add position states for content stack and content accordion section 

- .github/workflows/build.yml
Hey @gyasistory @rachaelblue I've been able to successfully update my mac to ```14.5``` and Xcode to ```15.3.0``` and running GodTools without any issues.
> GT Upgrade xcode version to 15.3.0

- godtools.xcodeproj/project.pbxproj
- godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
Update to use realm-swift 10.50.0
> GT Update realm to 10.50.0 and update to include privacy manifest

- godtools/App/Features/Onboarding/Presentation/OnboardingTutorial/OnboardingTutorialViewModel.swift
Updated to use CombineLatest on currentPage and pages published properties and drop first value of pages since pages are initially empty.
> GT-2387 Fix crash in onboarding tutorial when setting current page.  

- godtools/App/AppBackgroundState.swift
- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/App/Features/ToolsFilter/Data-DomainInterface/GetToolFilterLanguagesRepository.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Share/Data/LanguagesRepository/Cache/RealmLanguagesCache.swift
- godtools/App/Share/Data/LanguagesRepository/LanguagesRepository.swift
- godtools/App/Share/Data/TranslatedLanguageNameRepository/Sync/TranslatedLanguageNameRepositorySync.swift
- godtools/App/Share/Data/TranslatedLanguageNameRepository/TranslatedLanguageNameRepository.swift
Fixed an issue where the sync to store translated language names wasn't firing.  Ended up adding a prepend to the languages changed observer.
Also moved the translated language name syncing logic into AppBackgroundState singleton.
> GT-2389 fix kek showing up blank in tools languages filter

- godtools/App/Share/Data/LanguagesRepository/Api/Models/LanguageModel.swift
Creating a temp override of en-PH to fil-x-taglish until staging is merged into production.
> GT-2398 override en-PH with fil-x-taglish

- godtools/App/Features/Dashboard/Presentation/Dashboard/DashboardView.swift
- godtools/App/Features/Dashboard/Presentation/Dashboard/DashboardViewModel.swift
- godtools/App/Features/LearnToShareTool/Presentation/LearnToShareTool/LearnToShareToolView.swift
- godtools/App/Features/Onboarding/Presentation/OnboardingTutorial/OnboardingTutorialView.swift
- godtools/App/Features/ToolScreenShare/Presentation/ToolScreenShareTutorial/ToolScreenShareTutorialView.swift
- godtools/App/Features/Tutorial/Presentation/Tutorial/TutorialView.swift
I wasn't able to find the exact cause of this crash, but to be safe will only show the TabView when the items count is greater than 0.
> GT-2400 fix crash in tabview

- .github/workflows/create-version.yml
- .github/workflows/run-tests.yml
- .github/workflows/swift-lint.yml
- .github/workflows/testflight.yml
> GT Include releases/* this way we can distribute a new release build against previous releases

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/Account/Presentation/SocialSignIn/SocialSignInView.swift
- godtools/App/Features/Menu/Presentation/Menu/MenuView.swift
- godtools/App/Features/Menu/Presentation/Menu/Subviews/MenuItemView.swift
- godtools/App/Features/Menu/Presentation/WebContent/WebContentView.swift
- godtools/App/Features/ShareGodTools/Presentation/ShareGodTools/ShareGodToolsView.swift
- godtools/App/Features/Tutorial/Presentation/Tutorial/TutorialView.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Flows/Menu/MenuFlow.swift
- godtools/App/Share/Application/Accessibility/AccessibilityStrings.swift
- godtools/App/Share/Application/Accessibility/UIViewController+AccessibilityScreenId.swift
- godtoolsUITests/App/Flows/Menu/MenuFlowTests.swift
- godtoolsUITests/Share/Extensions/XCTestCase+AssertScreenDoesNotExist.swift
Started some UI tests for menu navigation.  Some of the navigation tests are a little more difficult and will come back to those at a later time.  Created this task [GT-2419](https://jira.cru.org/browse/GT-2419).
> GT menu flow tests

- .github/dependabot.yml
https://github.com/dependabot/dependabot-core/issues/1245#issuecomment-1650556093
https://github.com/dependabot/dependabot-core/pull/7525
> Update dependabot.yml to Add Swift Package Manager

- godtools/App/Features/AppLanguage/Data/AppLanguagesRepository/Api/AppLanguagesApi.swift
- Added app languages (sw, de, ja, ko).
- Sorted app languages list by language code.
> GT-2422 Add app languages (sw, de, ja, ko)

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/AppLanguage/Data-DomainInterface/GetConfirmAppLanguageInterfaceStringsRepository.swift
- godtools/App/Features/AppLanguage/Domain/Entities/ConfirmAppLanguageHighlightStringDomainModel.swift
- godtools/App/Features/AppLanguage/Domain/Entities/ConfirmAppLanguageInterfaceStringsDomainModel.swift
- godtools/App/Features/AppLanguage/Presentation/ConfirmAppLanguage/ConfirmAppLanguageView.swift
- godtools/App/Features/AppLanguage/Presentation/ConfirmAppLanguage/ConfirmAppLanguageViewModel.swift
Branched off of the cyoa feature.
> GT-2177 create domain model for highlighted text

- .github/workflows/download_onesky_translations.yml
Replace with ruby-setup to cache the result of bundle-install.
https://github.com/ruby/setup-ruby?tab=readme-ov-file#caching-bundle-install-automatically
> GT-2448 setup-ruby

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/AppLanguage/Data-DomainInterface/DownloadToolLanguageRepository.swift
This change will remove the DownloadedLanguage from the repository when downloading fails.
> GT-2457 Fix bug in language downloader when download fails

- .github/workflows/testflight.yml
> GT Add destination generic/platform=iOS

- godtools/App/Features/Shareables/Presentation/ReviewShareShareable/ReviewShareShareableView.swift
- godtools/App/Features/Shareables/Presentation/ReviewShareShareable/ReviewShareShareableViewModel.swift
- godtools/App/Flows/ArticleDeepLink/ArticleDeepLinkFlow.swift
This fixes a couple issues.
- The app language wasn't getting assigned in the ViewModel.
- Created a ZStack for the button and placed a rectangle within it for the button hit area.
> GT-2433 increase tap area on share related graphic button

- godtools/App/Features/UserLessonProgress/Presentation/ResumeLessonProgressModal/ResumeLessonProgressModal.swift
> GT-2465 Resume Lesson Modal - make button stack vertically

- godtools/App/Features/FeaturedLessons/Data-DomainInterface/GetFeaturedLessonsRepository.swift
- godtools/App/Features/FeaturedLessons/Domain/Entities/FeaturedLessonDomainModel.swift
- godtools/App/Features/Lessons/Data-DomainInterface/GetLessonsListRepository.swift
- godtools/App/Features/Lessons/Domain/Entities/LessonListItemDomainModel.swift
- godtools/App/Features/Lessons/Domain/Entities/LessonListItemDomainModelInterface.swift
- godtools/App/Features/Lessons/Presentation/Lessons/Subviews/LessonCard/LessonCardView.swift
- godtools/App/Features/Lessons/Presentation/Lessons/Subviews/LessonCard/LessonCardViewModel.swift
> GT-2442 Lesson Title Alignment

- .github/workflows/firebase.yml
Starting to add GitHub Actions workflow for firebase distribution.  
Will most likely need some tweaking as I test this more.
> GT GitHub actions firebase staging deploy

- godtools.xcodeproj/project.pbxproj
- godtools/App/Services/Renderer/Views/MobileContent/Views/Page/MobileContentPageView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/PageCollection/MobileContentPageCollectionPagesViewModel.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/PageCollection/MobileContentPageCollectionView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/PageCollection/MobileContentPageCollectionViewModel.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Renderer/MobileContentRendererView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Renderer/MobileContentRendererViewModel.swift
Page Collections are pages that contain multiple sub pages.  
This PR updates page collections to send any page events from sub pages upward to the owner of page collections.
> GT-2501 send page events upward from page collection

- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentButton/MobileContentButtonView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentButton/MobileContentButtonViewModel.swift
Add support for button title alignment in renderer.
Start
End
> GT-1261 Support button text alignment in renderer

- godtools/App/Services/Renderer/Views/MobileContent/Views/BackgroundImage/MobileContentBackgroundImageView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Page/MobileContentPageView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Page/MobileContentPageViewModel.swift
- godtools/App/Services/Renderer/Views/Tract/Views/Card/TractPageCardView.swift
Support background image layering in renderer page.
The page background image is layered by (manifest background, page background).
> GT 1485 overlay manifest background with page background

- godtools/App/Share/Common/ProgressTimer/ProgressTimer.swift
Updates ProgressTimer to support Combine by adding a ```startPublisher``` method.
> GT Add publisher to progress timer

- godtools/App/Features/AppLanguage/Data-DomainInterface/DownloadToolLanguageRepository.swift
- godtools/App/Features/AppLanguage/Data-DomainInterface/GetDownloadableLanguagesListRepository.swift
- godtools/App/Features/AppLanguage/Domain/Entities/DownloadableLanguageListItemDomainModel.swift
- godtools/App/Features/AppLanguage/Domain/Interface/DownloadToolLanguageRepositoryInterface.swift
- godtools/App/Features/AppLanguage/Domain/UseCases/DownloadToolLanguageUseCase.swift
- godtools/App/Features/AppLanguage/Presentation/DownloadableLanguages/DownloadableLanguagesViewModel.swift
- godtoolsTests/App/Features/AppLanguage/Data-DomainInterface/SearchLanguageInDownloadableLanguagesRepositoryTests.swift
Removing languageCode on the domain model since its not being utilized.
> GT-2478 Remove languageCode attribute

- godtools.xcodeproj/project.pbxproj
- godtools/App/Share/Common/RealmObjectPublisher/RealmObjectPublisher.swift
- godtools/App/Share/Common/RealmObjectPublisher/RealmObjectSubscription.swift
Adding a custom publisher for realm object changes.
https://www.mongodb.com/docs/atlas/device-sdks/sdk/swift/react-to-changes/#register-an-object-change-listener
> GT-2524 Add publisher for realm object change

- godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/VersionsCard/ToolDetailsVersionsCardView.swift
- godtools/App/Share/SwiftUI Views/LanguageSupportedText/LanguageSupportedText.swift
> GT-2307 add green/red color to language supported text

- godtools/App/Features/ToolDetails/Data-DomainInterface/GetToolDetailsRepository.swift
- godtools/App/Share/Application/Strings/LocalizableStringDictKeys.swift
- godtools/Base.lproj/Localizable.stringsdict
> GT-2536 Updated tool version card in tool details to use stringsdict for number of languages

- godtools/App/Features/Dashboard/Presentation/Tools/Subviews/ToolCard/ToolCardView.swift
Hey @rachaelblue just a heads up going to revert these changes to develop since no changes.
> GT-1719 revert tool card view changes

- godtoolsUITests/App/Flows/App/AppFlowTests.swift
- godtoolsUITests/App/Flows/Menu/MenuFlowTests.swift
- godtoolsUITests/App/Flows/Onboarding/OnboardingFlowTests.swift
UITests are randomly failing in GitHub Actions.  Will see if I can resolve those errors.  I believe it's a timing issue.
> GT-2562 Fix UI tests randomly failing

- godtools.xcodeproj/project.pbxproj
- godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
- godtools/App/Features/GlobalActivity/Data/GlobalAnalyticsRepository/Api/MobileContentGlobalAnalyticsApi.swift
- godtools/App/Share/Data/AttachmentsRepository/Api/MobileContentAttachmentsApi.swift
- godtools/App/Share/Data/LanguagesRepository/Api/MobileContentLanguagesApi.swift
- godtools/App/Share/Data/MobileContentApiAuthSession/MobileContentApiAuthSession.swift
- godtools/App/Share/Data/MobileContentAuthTokenRepository/Api/MobileContentAuthTokenAPI.swift
- godtools/App/Share/Data/ResourcesRepository/Api/MobileContentResourcesApi.swift
- godtools/App/Share/Data/TranslationsRepository/Api/MobileContentTranslationsApi.swift
Includes breaking change to RequestSender.  URLSession is now required to be sent with the URLRequest when sending a URLRequest.
> GT-2595 Update RequestOperation to include URLSession when sending URLRequest

- godtools/App/Features/OptInNotification/Data/OptInNotificationRepository/OptInNotificationRepositoryInterface.swift
- godtools/App/Features/OptInNotification/Presentation/OptInNotification/OptInNotificationViewModel.swift
- godtools/App/Share/Data/RemoteConfigRepository/RemoteConfigDataModel.swift
- godtoolsTests/App/Features/OptInNotification/Data/MockOptInNotificationRepository.swift
> GT Fix mock test

- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/App/Features/AppLanguage/Data/ToolLanguageDownloader/ToolLanguageDownloader.swift
- godtools/App/Features/Dashboard/Data-DomainInterface/FavoritedToolsLatestToolDownloader.swift
- godtools/App/Features/Dashboard/Presentation/Tools/Subviews/ToolCard/ToolCardViewModel.swift
- godtools/App/Features/Dashboard/Presentation/Tools/ToolsViewModel.swift
- godtools/App/Features/Favorites/Presentation/Favorites/FavoritesViewModel.swift
- godtools/App/Features/Lessons/Presentation/Lessons/LessonsViewModel.swift
- godtools/App/Features/Lessons/Presentation/Lessons/Subviews/LessonCard/LessonCardViewModel.swift
- godtools/App/Features/Shareables/Data-DomainInterface/GetShareablesRepository.swift
- godtools/App/Features/ToolDetails/Data-DomainInterface/GetToolDetailsLearnToShareToolIsAvailableRepository.swift
- godtools/App/Features/ToolDetails/Data-DomainInterface/GetToolDetailsMediaRepository.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/VersionsCard/ToolDetailsVersionsCardViewModel.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Renderer/MobileContentRendererViewModel.swift
- godtools/App/Share/Data/AttachmentsRepository/Api/MobileContentAttachmentsApi.swift
- godtools/App/Share/Data/AttachmentsRepository/AttachmentsRepository.swift
- godtools/App/Share/Data/ResourcesRepository/Api/MobileContentResourcesApi.swift
- godtools/App/Share/Data/ResourcesRepository/ResourcesRepository.swift
- godtools/App/Share/Data/ToolDownloader/ToolDownloader.swift
- godtools/App/Share/Data/TranslationsRepository/Api/MobileContentTranslationsApi.swift
- godtools/App/Share/Data/TranslationsRepository/TranslationsRepository.swift
- godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/GetToolTranslationsFilesUseCase.swift
- Added request prioritization level for attachment file downloads.
- Added request prioritization level for translation files.
- Added request prioritization level for resources.
> GT-2599 prioritize network requests

- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Services/Renderer/Views/Tract/Views/Form/TractPageFormViewModel.swift
- godtools/App/Share/Data/FollowUpsService/Api/FollowUpsApi.swift
- godtools/App/Share/Data/FollowUpsService/FollowUpsService.swift
Updates to FollowUpService.swift
- Added Combine Publisher
- Added network request prioritization
> GT-2614 update follow up service to use combine publisher

- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/App/Features/Account/Domain/UseCases/AuthenticateUserUseCase.swift
- godtools/App/Share/Data/EmailSignUpService/Api/EmailSignUpApi.swift
- godtools/App/Share/Data/EmailSignUpService/Cache/RealmEmailSignUpsCache.swift
- godtools/App/Share/Data/EmailSignUpService/EmailSignUpService.swift
Updated EmailSignUpService
- Added Combine Publisher
- Added network request prioritization
> GT-2615 update email sign up service for combine publisher

- godtools/Base.lproj/Localizable.stringsdict
- Fixes crash in UITests
- Possible will fix crash in develop
> GT Add NSStringLocalizedFormatKey for numberOfLanguages

- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/App/Features/AppLanguage/Data/DownloadedLanguagesRepository/Cache/RealmDownloadedLanguagesCache.swift
- godtools/App/Features/Dashboard/Presentation/Tools/ToolsViewModel.swift
- godtools/App/Features/Favorites/Presentation/Favorites/FavoritesViewModel.swift
- godtools/App/Features/Lessons/Presentation/Lessons/LessonsViewModel.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Share/Data/ResourcesRepository/ResourcesRepository.swift
Fetches resources plus latest translations and attachments based on time interval unless a pull to refresh is made.
> GT-2640 add timing for fetching resources

- godtools.xcodeproj/project.pbxproj
Removed some folder references from the project that didn't exist.
> GT Remove project references to folders that do not exist

- README.md
Starting to add a tests section to the ReadMe.
> GT Add tests section to ReadMe

- godtools/App/Share/Application/LaunchEnvironment/LaunchEnvironmentKey.swift
- godtools/App/Share/Application/LaunchEnvironment/LaunchEnvironmentReader.swift
- godtools/App/Share/Application/LaunchEnvironment/LaunchEnvironmentWriter.swift
- godtools/App/main.swift
- godtoolsUITests/App/Flows/BaseFlowTests.swift
Adding isUITests Bool flag to launch environment.  Eventually will use this when setting up the app for UI Tests.
> GT add is UI tests to launch environent

- godtools/App/Flows/ToolScreenShare/ToolScreenShareFlow.swift
- godtools/App/Share/Application/Accessibility/AccessibilityStrings.swift
- godtoolsUITests/App/Flows/ToolScreenShare/ToolScreenShareFlowTests.swift
Tests skip button goes to last page of tutorial screen.
> GT-2696 Tool screen share tutorial navigation tests

- godtools/Localizable/ru-143.lproj/Localizable.strings
- godtools/Localizable/ru-143.lproj/Localizable.stringsdict
Add ru-143.lproj.  Will see if I get the Warning.
> GT-2732 Add ru 143
