- godtools.xcodeproj/project.pbxproj
- godtools/AppDelegate.swift
- godtools/Constants/GTSettings.swift
- godtools/Constants/GTUIExtensions.swift
- godtools/Localizable.strings
- godtools/Managers/DownloadResources/DownloadedResourceJson.swift
- godtools/Managers/DownloadResources/DownloadedResourceManager.swift
- godtools/Managers/GTDataManager.swift
- godtools/Managers/LanguageResource.swift
- godtools/Managers/LanguagesManager.swift
- godtools/Managers/ToolsManager.swift
- godtools/Managers/Translations/TranslationResource.swift
- godtools/Managers/Translations/TranslationsManager.swift
- godtools/Models/DownloadedResource+CoreDataProperties.swift
- godtools/Models/Language+CoreDataProperties.swift
- godtools/ViewControllers/Platform/AddToolsViewController.swift
- godtools/ViewControllers/Platform/HomeViewController.swift
- godtools/ViewControllers/Platform/LanguageSettingsViewController.swift
- godtools/ViewControllers/Platform/LanguageSettingsViewController.xib
- godtools/ViewControllers/Platform/LanguagesTableViewController.swift
- godtools/ViewControllers/Platform/ToolDetailViewController.swift
- godtools/Views/Cells/HomeToolTableViewCell.swift
- godtools/Views/Cells/LanguageTableViewCell.swift
- godtools/godtools.xcdatamodeld/godtools.xcdatamodel/contents
Begins to wire some of the front end UIs into the background data model.
- Home and Add Tools show available resources, based off of DownloadedResource.shouldDownload
- Selecting an item from Add Tools "downloads" (simulated for now) and makes it appear on the Home view
- this should be the button driving the "download", I think, but it's done there yet
- Selecting a language from the languages screen sets it as the primary/parallel language in the user settings
- download/delete buttons are not yet wired up.
- Onboarding view is shown in viewDidLoad so it only shows once per app open, and once a user selects a primary language it is not shown again.
> Wire UI to data/services (part 1)

- godtools/Views/Cells/HomeToolTableViewCell.swift
This ensures that when a resource is removed, the cell below it doesn't accidentally display the banner for the resource just removed.
The use case is, cell n has a banner and n+1 does not. Cell n's resource is removed, and when coming back to the home view cell n+1 (now cell n) renders the banner for the resource just removed because the banner passed into the config method was nil, and there was nothing to handle that.
> When banner is nil, then set the placeholder image.

- godtools/Managers/DownloadResources/DownloadedResourceManager.swift
- godtools/Managers/Translations/TranslationResource.swift
- godtools/Models/DownloadedResource+CoreDataClass.swift
- godtools/ViewControllers/Platform/ToolDetailViewController.swift
- godtools/ViewControllers/Tract/TractViewController.swift
- godtools/Views/Cells/HomeToolTableViewCell.swift
Retrieve localized name and description when updating translations from the database
Use these values to show throughout the app where resource.name was used.
> Localized name description

- godtools/Managers/DownloadResources/DownloadedResourceManager.swift
- godtools/Managers/GTDataManager.swift
- godtools/Managers/LanguagesManager.swift
- godtools/Managers/Translations/TranslationsManager.swift
- godtools/ViewControllers/Platform/LanguageSettingsViewController.swift
- godtools/Views/Cells/HomeToolTableViewCell.swift
- godtools/godtools.xcdatamodeld/godtools.xcdatamodel/contents
- refactor all MR calls into `GTDataManager`
- fix hideous bug where deleting ReferencePages cascaded to delete Translations. :-1: for my experimentation.
- use proper context that does saving on a background thread (as recommended by MagicalRecord)
Also fixes issue where progress bar was not showing on add tools view
> Improve CoreData Context handling and fix a bug

- godtools.xcodeproj/project.pbxproj
- godtools/Managers/ResourceViews.swift
- godtools/Managers/ToolsManager+ResourceViews.swift
- godtools/Managers/ToolsManager.swift
- godtools/Models/DownloadedResource+CoreDataProperties.swift
- godtools/godtools.xcdatamodeld/godtools.xcdatamodel/contents
This PR adds the ability to record with the API that a resource has been viewed. If the request fails, then a counter is incremented on DownloadedResource object. These stored values are then synced on app re-launch. If successful the counter resets to 0
> Track views

- godtools/Views/TractElements/TractCardActions.swift
This will change the current behaviour, from hiding only the open card to hide all cards (moving them back to its original position) when the user press on the label of the card
> GT-332: Hide all cards when touching the label of an open card

- godtools/Views/TractElements/TractButtonActions.swift
- godtools/Views/TractElements/TractLinkActions.swift
- godtools/XMLContent/KGP/kgp-5.xml
@pablomarti I believe I adjusted the changed separator for multi-events.
This is dependent on the changes made in this PR: https://github.com/CruGlobal/mobile-content-api/pull/68
> switching to space separated events instead of comma separated

- godtools.xcodeproj/project.pbxproj
- godtools/Constants/GTAppDefaultColors.swift
- godtools/FlowControllers/BaseFlowController.swift
- godtools/GeneralExtensions/String.swift
- godtools/GeneralExtensions/UIColor.swift
- godtools/Managers/TractManager.swift
- godtools/TractClasses/TractColors.swift
- godtools/ViewControllers/BaseViewController.swift
- godtools/ViewControllers/Tract/TractViewController.swift
- godtools/XMLContent/KGP/kgp-0.xml
- godtools/XMLContent/KGP/kgp-manifest.xml
This PR sets the navigation bar items to have the color defined in the primary text color of the manifest. The background color also changes, but first it transforms the color with an alpha to a similar color without alpha, removing the transparency.
> GT-294: Change style of navigation bar of tract

- godtools/Managers/TractManager.swift
- godtools/ViewControllers/Tract/TractViewController.swift
- godtools/ViewControllers/Tract/TractViewControllerContent.swift
- godtools/ViewControllers/Tract/TractViewControllerPageMovements.swift
This PR changes the way of how the views are managed. It will always have a max of 5 items, but will have a specific space for storing each view (that, when not used will be nil). This fix the crash and helps by making the code easy to understand and handle, and allows to move from long distance views.
> GT-337: Fix crash when moving through pages

- godtools/FlowControllers/BaseFlowController.swift
- godtools/Localizable.strings
- godtools/ViewControllers/BaseViewController.swift
- godtools/ViewControllers/Platform/HomeViewController.swift
- godtools/ViewControllers/Platform/LanguagesTableViewController.swift
- godtools/ViewControllers/Platform/ToolDetailViewController.swift
- return to home view after delete or download from tract info view
- demo a "Clear" button as one way to deselect a parallel language
- this button is an imcomplete feature as it should show hide appropriate based on state updates within the view. However b/c other changes are coming to the LanguagesManager and we don't know if we will use this, i want to put off those changes until later.
> Platform updates

- godtools/Views/TractElements/TractHeading.swift
- godtools/Views/TractElements/TractParagraph.swift
- godtools/Views/TractElements/TractTextContentProperties.swift
- Change default text size to 16 to match designs
- Change hero heading text from 54 light to 30 regular to match designs
- Eliminate extra margin constant on paragraph
> Layout tweaks

- godtools.xcodeproj/project.pbxproj
- godtools/Managers/BannerManager.swift
- godtools/Managers/DownloadResources/DownloadedResourceJson.swift
- godtools/Managers/DownloadResources/DownloadedResourceManager.swift
- godtools/Managers/GTDataManager+Migrations.swift
- godtools/Managers/GTDataManager.swift
- godtools/Managers/ToolsManager.swift
- godtools/Models/DownloadedResource.swift
- godtools/ViewControllers/Platform/ToolDetailViewController.swift
- godtools/Views/Cells/HomeToolTableViewCell.swift
Restructure Banner Manager to download both. This class no longer returns a promise b/c no one listens for it. It still posts a notification when the home page banner finishes.
BannerManager also defines its own GET method b/c storing bannerId in internal state got messy with the downloading of multiple banners in one instance.
> Download two banners, one for home page, one for about page

- godtools/TractClasses/TractProperties.swift
- godtools/Views/TractElements/BaseTractElement+StaticFunctions.swift
- godtools/Views/TractElements/BaseTractElement.swift
- godtools/Views/TractElements/TractHeader.swift
- godtools/Views/TractElements/TractHeaderProperties.swift
- godtools/Views/TractElements/TractHeadingProperties.swift
- godtools/Views/TractElements/TractNumber.swift
- godtools/Views/TractElements/TractParagraph+UI.swift
- godtools/Views/TractElements/TractTextContent+UI.swift
- godtools/Views/TractElements/TractTextContent.swift
- godtools/Views/TractElements/TractTextContentProperties.swift
- make colors inherited from the top level downward (manifest, page, text:content)
- a local text color should override anything set above it
- font scaling support works now too, only on lowest level content:text node
- default text size = 18, except for headings, now 30
> Font size & color tweaks

- godtools/FlowControllers/BaseFlowController.swift
- godtools/Views/TractElements/TractCard+Actions.swift
- godtools/Views/TractElements/TractCard+UI.swift
- godtools/Views/TractElements/TractCard.swift
- godtools/Views/TractElements/TractCards+Animations.swift
- godtools/Views/TractElements/TractCards+ChildSetup.swift
- godtools/Views/TractElements/TractCards.swift
- cards should not slide behind nav bar.
This means cards starting yPos should be adjusted by the nav bar height, but the height should also be reduced by the nav bar height
The internal heights also need adjusted so that the scrolls work well
> Take the fact that the view slides behind the nav bar when moving cards.

- godtools/AppDelegate.swift
- godtools/Managers/LanguagesManager.swift
- godtools/Managers/TranslationFileRemover.swift
- godtools/Managers/TranslationZipImporter.swift
The referenced file counts were being done incorrectly. This led to deleting one language or resource deleting files that belong to something else. This could mean images missing or even crashes when XML pages were missing.
> Fix issues when deleting a resource or a translation

- godtools/ViewControllers/Platform/ToolDetailViewController.xib
the constraint was 64 which ironically is the height of the navbar at this time.
> Fix constraint so there's no gap b/w image top and navbar

- godtools/Base.lproj/Localizable.strings
- godtools/ViewControllers/Platform/ToolDetailViewController.swift
- godtools/Views/Buttons/GTButton.swift
- godtools/Views/Cells/HomeToolTableViewCell.swift
When a resource exists, but has no published translations: 
- don't show the download button on the add tools table view
- show a disabled "unavailable" button on the tool detail view.
> Disabled download button

- godtools/Views/TractElements/BaseTractElement.swift
- godtools/Views/TractElements/TractCards+ChildSetup.swift
- godtools/Views/TractElements/TractCards+UI.swift
- godtools/Views/TractElements/TractCards.swift
- godtools/Views/TractElements/TractHero.swift
On iPhone 4 and 5, currently, if the text of the `<hero>` is large and there are too many `<card>` inside of `<cards>`, the first `<card>` will not be able to have a touch gesture because the `<cards>` element gets its position down, and those `<card>` objects have a -y position (this problem may also happen in iPhone 6 and 7 if the problem with the heights overlaps).
The solution is that the position y of the `<cards>` object should be updated taking the new height of the `<hero>` component (that new height is calculated after the `<cards>` object was added, so, this required operations between elements of the same level).
> Fix cards problem when text of hero component is large and there are many cards

- godtools.xcodeproj/project.pbxproj
- godtools/Views/TractElements/TractCard+Actions.swift
- godtools/Views/TractElements/TractCard.swift
- godtools/Views/TractElements/TractCards+Actions.swift
- godtools/Views/TractElements/TractCards+Gestures.swift
- godtools/Views/TractElements/TractCards.swift
Now it is possible to do the swipe up and down not just in the `<card>` element but also in `<cards>`, so if the user does the swipe in the free space between the open card and the closed cards, it will work. Also, now there is a press gesture recognizer in that same area so if the last card touching area is too small it would not be a problem.
> GT-358: Add gestures to cards element

- godtools/Views/TractElements/TractButton+Actions.swift
So I added a method to add http:// to those that don't have one.
Without a protocol, the call to: UIApplication.shared.openURL(url) will do nothing
> The values in OneSky do not have a protocol. 

- godtools/Constants/GTConstants.swift
- godtools/ViewControllers/Platform/HomeViewController.swift
This was broken when logic was added to preset the primary language on first launch.
> Show onboarding screens on first launch

- godtools/ViewControllers/Tract/TractViewController.swift
Not totally sure the cases that cause this failure, but it's been reported in crashlytics a couple times.
https://fabric.io/cru/ios/apps/org.cru.godtools.beta/issues/5956b1f0be077a4dccd947b4?time=last-seven-days
> Prevent crash when navigation controller is nil.

- godtools/Managers/LanguagesManager.swift
I think I was thinking that this would just return out from the block, but I'm not sure. At any rate, this prevents new languages from being saved, which is an insta-crash whenever something new is published.
> Continue to next language instead of returning from function.

- godtools/ViewControllers/Tract/TractViewController.swift
- godtools/ViewControllers/Tract/TractViewControllerActions.swift
- unwrap optional resource when reporting name
- report the first view "0" when a tract is first loaded
> Analytics name fix

- godtools/Info.plist
- godtools/ViewControllers/Tract/TractViewController.swift
Do not append 0 to share URL for first page:
- the website does not use 0 for the first page.
- also tack on a space for padding so that trailing punctuation does not interfere with the link
> Share url fix

- godtools/ViewControllers/Tract/TractViewController.swift
- godtools/ViewControllers/Tract/TractViewControllerActions.swift
It was being reported twice b/c the code was trigger both in:
1. TractViewController.viewDidLoad() - this one worked properly because the method it called built the view name "resource"-"pageNum"
2. BaseViewController.viewWillAppear() - this one did not work, because TractViewController did not override the screenName() method with the logic to build the name. It fell back to "unknown" as defined in BaseViewController.screenName().
This fix eliminates the call in viewDidLoad() and just allows the call in BaseViewController.viewWillAppear() to be triggered. It also moves the logic to build the view name to the overridden screenName() method that is used for all views of a tract now. the viewWillAppear() call now uses the screenName() logic to build the right name.
> Fix screen name reporting for first view of tract controller

- godtools/Models/DownloadedResource.swift
- godtools/ViewControllers/Tract/TractViewControllerDataManagement.swift
- godtools/Views/Cells/HomeToolTableViewCell.swift
The parallel language name indicator is missing when adding a tool. This PR fixes that by clarifying the difference b/w a translation being "available" and "downloaded"
Downloaded means it is downloaded to the device
Available means it can be downloaded to the device. It may or may not actually be downloaded to the device, however.
> Gt 411 language indicator add tools

- godtools/Assets.xcassets/AppIcon.appiconset/Contents.json
- godtools/ViewControllers/BaseViewController.swift
The issue actually isn't specific to the "right side" buttons, though the issue was noticed there.
The reason is because the buttons that are shown on the right side of the bar have images that are signficantly larger than the left side.
This version of XCode that builds the project doesn't respect the size applied to UIBarButton item and allows the image (in customView) to expand as large as it wants to. The old builder enforced the limit at the UIBarButtonItem level
The actual fix is to apply height and width constraints to the buttons inside the UIBarButtonItem to make sure they stay 22x22 regardless of the size of the image they contain.
> Fix rendering of navigation buttons in XCode 9

- README.md
- godtools/Analtyics/GodToolsAnaltyics.swift
This PR moves all Adobe Analytics operations to a background queue as to not interfere with any interactions on the main thread.
There is also an update in the readme describing the current state of the branches.
After merging this branch, the develop branch will still contain code unsuitable for release. Hotfixes should be done from develop-xcode8
> Adobe analytics async

- godtools/Views/TractElements/BaseTractElement.swift
- godtools/Views/TractElements/TractCard+Animations.swift
- godtools/Views/TractElements/TractCard.swift
- godtools/Views/TractElements/TractPageContainer.swift
When changing language on tracts the state of the open cards was not persisted; the bug was introduced with the changes for supporting iPhone X. This PR fix that bug.
> Fix open cards on lang

- godtools/Managers/TranslationZipImporter.swift
Force unwrapping is probably causing the issue: https://fabric.io/cru/ios/apps/org.cru.godtools/issues/5992cddfbe077a4dcc1c73a4?time=last-thirty-days
> Use a guard let statement instead of force unwrap on translation.language

- godtools/Managers/ToolsManager.swift
I'm not sure how this would happen, probably some sort of race condition. This fix would prevent a crash, and the result would be whatever was in the dequeued cell would be returned. This may produce undefined behavior, but at least the crash is avoided.
> Return cell immediately if section exceeds number of resources in the array

- godtools/Managers/TranslationZipImporter.swift
Track English download when resource is not available in primary language
This will prevent weird UI/UX b/c w/o this change the AddTools screen will not show any update or pop b/c all notifications are filtered out.
fixes: https://jira.cru.org/browse/GT-440
> Fix downloads ux

- godtools/Views/TractElements/TractCallToAction+UI.swift
- godtools/Views/TractElements/TractCallToActionProperties.swift
- godtools/Views/TractElements/TractHeader.swift
Allows the call to action button color to be customized. If the optional control-color attribute is not set, then the fallback will be to page.primary-color and manifest.primary-color in that order.
Tested on stage: w/ control-color set, with page.primary-color set, with manifest.primary-color set. See KGP in stage for different scenarios.
> Gt 378 call to action button color

- godtools/GeneralExtensions/String.swift
- godtools/Managers/GTDataManager+Migrations.swift
- godtools/Managers/LanguageResource.swift
- godtools/Managers/LanguagesManager.swift
- godtools/Models/Language.swift
- godtools/Views/TractElements/TractTextContent+UI.swift
Problem: iOS does not inspect runtime text and determine which direction it should render, Android seems to. `NSTextAlignment.natural` only applies to system strings defined at build time, not dynamically created runtime labels/strings like we use in the content renderer.
My first attempt was to use NSLinguisiticTagger to inspect the runtime content strings and determine the language. It worked, but only about 85% of the time when trying render Arabic.
This solution is to use an attribute added to the API in PR: (https://github.com/CruGlobal/mobile-content-api/pull/138) which specifies the direction the text ought to be rendered in. This attribute is added at stored and used to determine the direction.
Every label in the renderer is defaulted to `NSTextAlignment.left` unless …
> Gt 449 right to left content rendering

- godtools/Views/TractElements/TractHeader.swift
In recent commit, it was mistakenly set to "page background" which is always white. It should have been set to "page primary color" which is set at the page or manifest level.
This was a small refactoring mistake.
> Fix header background setting

- godtools/XMLManagement/XMLPage.swift
per the content spec: https://github.com/CruGlobal/mobile-content-api/blob/master/public/xmlns/content.xsd#L124
> Listeners are space separated, not comma separated

- godtools/App/Features/Onboarding/Views/OnboardingTutorialIntroView.swift
- godtools/App/Features/Tools/Views/OpenTutorialView/OpenTutorialView.swift
- godtools/App/Share/Extensions/UIKit+Extensions.swift
- godtools/App/Share/ImageCatalog.swift
Hey @reldredge71 this should do it.  One I had to force the layout on the button by calling layoutIfNeeded, and also added an override for when the view is actually added to the superview and updating the button layout when that happens because when we configure that view it's not even part of the view hierarchy at that point.
Also fixed the shared extension by including the imageWidth when positioning the image to the right of the button title. Including that imageWidth places the image left edge right on the title right edge.
> GT-1308 Fix positioning image to right of button title

- godtools/App/AppDelegate.swift
- godtools/App/Flows/AppFlow.swift
- godtools/App/Flows/MenuFlow.swift
- godtools/App/Flows/ToolsFlow.swift
- godtools/App/Share/ColorPalette.swift
- godtools/Info.plist
Fixed status bar for iOS 11 by setting window background color to match navigation bar background color.  Doesn't effect iOS 13 and up because status bar color will use the navigation bar color by default.
> GT-1359 Fix status bar for iOS 11

- godtools/App/Share/Extensions/UINavigationBar+Appearance.swift
- godtools/App/Share/NavControllers/ModalNavigationController.swift
With iOS 13 and up we can hide the separator line by setting the shadowColor to clear on UINavigationBarAppearance.
> GT-1360 Fix navigation bar separator line showing on shared modal navigation

- godtools/App/Services/Renderer/Parser/Protocol/Models/MobileContentButtonIcon.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentButton/MobileContentButtonView.swift
- godtools/App/Share/Extensions/UIView+Constraints.swift
- Changes to MobileContentButtonView to support multiline text.  Had to remove UIButton because it is very difficult to use the System UIButton with multiline text and image.  Instead using UILabel and UIImageView and manually adding constraints.
> GT-1366 allow buttons to have multiple lines of text

- .github/workflows/build.yml
Use environment variable to set GHA to use XCode 13.2.
> set XCode version in GHA build job

- godtools.xcodeproj/project.pbxproj
New macs running Apple Silicon will need this flag in order to run builds in the Simulator.
https://medium.com/@johny.urgiles/wrestling-with-xcode-12-and-arm64-6c7977922abb
> GT Adding arm64 for simulator in excluded architecture

- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesView.swift
- godtools/App/Share/Views/PageNavigationCollectionView/PageNavigationCollectionView.swift
- Fixed pageDidAppear not getting called which occurs whenever scrollToPage animated flag is set to false.  This is because the ScrollView delegate methods will not get called when animated is set to false.  I was able to re-use similar functionality for calling pageDidAppear when table data is reloaded.  
- Removed the pageWillDisappear delegate method because it is not being used and UICollectionView doesn't provide any means of reporting when a cell will disappear.  There is also the pageDidDisappear which UICollectionView does provide and can be used if any cleanup is needed.
> GT-1206 Fix pageDidAppear not getting called when animate scroll is set to false

- godtools/App/Services/Renderer/Views/Tool/Views/Card/ToolPageCardView.swift
- godtools/App/Services/Renderer/Views/Tool/Views/Card/ToolPageCardView.xib
- godtools/App/Services/Renderer/Views/Tool/Views/Cards/ToolPageCardsView.swift
There were two parts to the issue I found:
1. The gradient is initially being set before the content insets between the CardsView and the Card are set.  So the width of the gradient is the full with of the CardsView, not the new shrunken width of the Card.
2. Multiple gradient layers are getting layered on top of each other each time `setupLayout()` is getting stepped through.  So, even when the content insets are applied to the card and I call `layoutSubviews()`, the original gradient still exists.
My solution is to:
1. Make sure the gradient is getting set after the content insets are in place, and
2. If there is a gradient layer already in place, replace it instead of adding a new one.
> GT-1394: Fix Bottom Gradient in Tool Cards

- godtools/App/Flows/AppFlow.swift
Tapping back from the conversation starter tool should take you back to the tools menu.  I believe this broke in GT-1445 when I moved the ToolsFlow into AppFlow.
> GT-1458 Fix navigate back to all tools from conversation starter tool

- godtools/App/Services/Renderer/Views/MobileContent/Views/CardCollectionPage/MobileContentCardCollectionPageView.swift
- godtools/App/Share/Extensions/UIView+Constraints.swift
Hey @reldredge71 made some changes to UIView+Constraints shared extension.
1. Added edgeInsets argument to the constrainEdgesToView method.
2. When adding a trailing and bottom constraint I would multiply that by -1 to get a padding effect.  I decided to move that logic into the extension instead.
> Added edgeInsets argument to constrainEdgesToView

- godtools/App/Services/Renderer/Views/MobileContent/Views/CardCollectionPage/MobileContentCardCollectionPageView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/CardCollectionPage/MobileContentCardCollectionPageViewModel.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/CardCollectionPage/MobileContentCardCollectionPageViewModelType.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/CardCollectionPage/Models/MobileContentCardCollectionPagePositionState.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
Fixed language toggling for the conversation starter tool.  The issue was when switching languages the current logic was fetching the incorrect page model.  Changed this to use the page id which guarantees the correct page model will be used when switching between language renderers.
@aaronlaib I also made a fix where the card index was being used to track which card should be navigated to when switching languages.  Updated to use card id instead.
> GT-1425 fix card collection page toggling

- godtools/App/Flows/AppFlow.swift
This was a strange one, the bug would only occur when dismissing a viewController that was presented on the navigationController and also calling layoutIfNeeded on the navigationController when setting the toolsMenu in the stack.  I initially had the layoutIfNeeded there to force the navigationController to layout when setting the toolsMenu in the stack.  I don't think it is necessary however, so will remove to address this bug.
> GT-1463 Fix home screen panning of tools lists

- godtools/App/Features/Tool/Views/ToolNavBar/ToolNavBarView.swift
Screen Share Icon should remain visible at the top of the screen while screen sharing is happening.
> GT-1398 -- Fix for disappearing Screen Share Icon

- godtools/App/Features/Onboarding/Models/OnboardingQuickStartItem.swift
- godtools/App/Features/Onboarding/OnboardingQuickStartViewModel.swift
- godtools/App/Features/Onboarding/OnboardingTutorialViewModel.swift
- godtools/App/Flows/OnboardingFlow.swift
- godtools/App/Services/Analytics/AnalyticsConstants.swift
Created a couple of new analytics events to be triggered when pressing the Quick Start links, or pressing the "Get Started" button.
> GT-1477: Add Analytics Tracking for Pressing Quick Start Links

- godtools/App/AppDelegate.swift
There's been some bugs reported in iOS 15 with Keychain data disappearing.  This would occur if initialization of the Keychain data access occurred during AppDelegate init() and the fix was to move this logic to AppDelegate didFinishLaunching().  I noticed in MPDX this was causing problems.  With GodTools I don't think there is any issue, however, I decided to move AppDiContainer and AppFlow initialization from AppDelegate init() to AppDelegate didFinishLaunching() by making those lazy variables so they're initialized upon first access.
> GT-1388 - Change startup initialization to prevent iOS 15 bug

- godtools/App/Services/Renderer/Views/Tool/Views/Header/ToolPageHeaderView.xib
For this fix I increased the compression resistance on the number UILabel.  A higher compression resistance won't allow the label to shrink smaller than the containing text.
> GT1453 - Fix tool header number label clipping

- godtools.xcodeproj/project.pbxproj
I needed to add these Localizations (Pashto and Kurdish) to the Xcode project settings as well in order for those to get pulled into the project bundle when distributing to TestFlight.
> GT-1470 Add Pashto and Kurdish Localizations to Xcode project settings

- godtools/App/Features/Tools/ToolsMenuView.swift
The issue here was the ToolsMenuView startingToolbarItem is overriding the reset methods toolbarItem when the view finishes layout.  This will happen anytime reset is called before the view finishes laying out.  This fix addresses that by updating the startingToolbarItem whenever reset is called and the view hasn't finished its layout.
> GT-1472 Fix AppsFlyer deferred deep linking into lessons list and all tools list

- godtools/App/Services/Renderer/Views/MobileContent/ViewFactory/MobileContentPageViewFactory.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentFlow/MobileContentFlowView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentFlowItem/MobileContentFlowItemView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentFlowItem/MobileContentFlowItemViewModel.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentFlowItem/MobileContentFlowItemViewModelType.swift
This PR includes work that will update flowItems visibility (gone, hidden, visible) within the content flow.  Whenever a flowItem's visibility changes and the previous visibility or new visibility is equal to gone, it will trigger a rebuilding of the entire content flow and flow items.
> GT-1406 Implement flow item state visibility

- godtools/App/Services/Renderer/Views/MobileContent/Views/CardCollectionPageCard/MobileContentCardCollectionPageCardView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentInput/MobileContentInputView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentTabs/MobileContentTabsView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentText/MobileContentTextView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Page/MobileContentPageView.swift
- godtools/App/Services/Renderer/Views/Tool/Views/CallToAction/ToolPageCallToActionView.swift
- godtools/App/Services/Renderer/Views/Tool/Views/Card/ToolPageCardView.swift
- godtools/App/Services/Renderer/Views/Tool/Views/Header/ToolPageHeaderView.swift
- godtools/App/Services/Renderer/Views/Tool/Views/Modal/ToolPageModalView.swift
- godtools/App/Services/Renderer/Views/Training/Views/Page/TrainingPageView.swift
- godtools/App/Services/Renderer/Views/Training/Views/TrainingTip/TrainingTipView.swift
- godtools/App/Share/Protocols/NibBased.swift
This PR addresses code duplication when loading a UINib from a custom .xib.  Logic for loading a UINib exists in the NibBased extension loadNib method.  I updated the following UIView Subclasses to implement NibBased and utilize the loadNib method.
> GT-1508 remove duplicated load nib logic

- godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionView.xib
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentCard/MobileContentCardView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentMultiSelect/MobileContentMultiSelectView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentMultiSelectOption/MobileContentMultiSelectOptionView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentStack/MobileContentStackView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/MobileContentView.swift
- godtools/App/Services/Renderer/Views/Tool/Views/Card/ToolPageCardView.swift
In this PR I added drawShadow() to the base MobileContentView class which is the base class for all mobile content renderer UI elements.  I removed shadow drawing code in subclasses and subclasses utilize the base drawShadow().
I also made a change to MobileContentStackView background color.  The MobileContentStackView consists of a view hierarchy like so. UIView (rootView) > UIScrollView? > UIView (contentView) where background color was applied to the contentView.  A change was made to set UIScrollView and contentView background colors to clear and background color will instead be applied to the rootView.
> GT-1506 add shadow support to base MobileContentView

- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentCard/MobileContentCardView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentStack/MobileContentStackView.swift
In this PR I updated MobileContentStackView to support content insets between scrollable content and non scrollable content.  Not all MobileContentStackView's are scrollable, but if one is, then its minimum content insets will be 10 by default to prevent any clipping of inner elements that have shadows.
Also changed the content card content insets to 8 instead of padding.  That way the background stays fixed to the edges of the card and inner content would be spaced 8 points from the background edge.
> GT-1513 update stack renderer to support shadows

- godtools/App/Services/Renderer/Views/Tool/Views/Header/ToolPageHeaderView.swift
- godtools/App/Services/Renderer/Views/Tool/Views/Header/ToolPageHeaderView.xib
This PR fixes extra spacing that was getting applied from the tract header training tip.  When the training tip is hidden, spacing is still getting accounted for.  This fix addresses that by adjusting the header's training tip top layout constraint when hidden vs visible.
> GT-1512 Fixed spacing issue in tract renderer

- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentFlowRow/MobileContentFlowRow.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentFlowRow/MobileContentFlowRowItem.swift
In this PR a couple of things were done:
1. Added code to equally center flow items in a flow when gravity is set to center.  This is done by taking the remaining space available in a row (minus combined width of added flow items) and evenly distributing this space between flow items and the first items leading space to the row and the last items trailing space to the row.
2. Ensure the first flow items leading constraint is attached to the rows leading and the last flow items trailing is attached to the rows trailing so all horizontal constraints are satisfied.
> GT-1283 Fix to center gravity in flow 

- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Flows/Tract/TractFlow.swift
- godtools/App/Flows/Tract/TractFlowCompletedState.swift
This PR involves linking a close tract to the lessons list whenever a deeplink is triggered from an opened tract to the lessons list.
> GT-1489 Link tract to lessons list

- godtools.xcodeproj/project.pbxproj
- godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
- godtools/App/Services/Renderer/Analytics/MobileContentEventAnalyticsTracking.swift
- godtools/App/Services/Renderer/Views/MobileContent/Models/ProcessedEventResult/ProcessedEventResult.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentTabs/MobileContentTabsView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/MobileContentView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Page/MobileContentPageView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModelType.swift
- godtools/App/Services/Renderer/Views/Tool/Views/Cards/ToolPageCardsView.swift
- godtools/App/Services/Renderer/Views/Tool/Views/Form/ToolPageFormView.swift
- godtools/App/Services/Renderer/Views/Tool/Views/Modal/ToolPageModalView.swift
This PR fixes an issue where the ```followup:send``` event was getting sent to all forms in a page when it should only be sent to the form in the view hierarchy that the event was generated from.  
This was fixed by changing how events are sent to views in a page.  Originally, whenever an event is triggered, it will start at the rootView (page) of the view hierarchy and recurse all children passing the eventIds to each child for processing.  This means that the ```followup:send``` event would get passed to each form in the page hierarchy which is what we don't want.  
To fix this, a couple things were done:
1. Changed the didReceiveEvents method to process a single eventId at a time and added a ```ProcessedEventResult?``` return type.  This return type contains a flag …
> Gt 1514 fix Vietnamese prayer pathway registration bug

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/ToolDetails/Models/ToolDetailBanner.swift
- godtools/App/Features/ToolDetails/Models/ToolDetailBannerType.swift
- godtools/App/Features/ToolDetails/ToolDetailView.swift
- godtools/App/Features/ToolDetails/ToolDetailView.xib
- godtools/App/Features/ToolDetails/ToolDetailViewModel.swift
- godtools/App/Features/ToolDetails/ToolDetailViewModelType.swift
- godtools/App/Services/Attachments/AttachmentsFileCache.swift
- godtools/App/Services/RealmDatabase/RealmDatabase.swift
- godtools/App/Services/Resources/RealmResourcesCache/Models/RealmResource.swift
- godtools/App/Services/Resources/ResourcesApi/Models/ResourceModel.swift
- godtools/App/Services/Resources/ResourcesApi/Models/ResourceModelType.swift
- godtools/App/Services/SHA256FileCache/SHA256FileLocation.swift
This PR adds support for animations in the ToolDetailView top banner.  Added an enum ToolDetailBanner that the view observes on the viewModel to control if the banner should display an image, youtube video, or animation.
Honor Restored and The Four both support animations in the tool details.
> GT-1300 support animations in about banner

- godtools/App/Services/Renderer/Views/Tool/Views/Cards/ToolPageCardsView.swift
Was using the incorrect cards array when getting the number of visible cards.  Should have been filtering on all cards instead of using the length of renderedCards.
> GT-1574 fix stacked cards in tool renderer 

- godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsView.swift
- godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewModel.swift
- godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewPreview.swift
- godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsChooseLanguage/ToolSettingsChooseLanguageView.swift
- godtools/Base.lproj/Localizable.strings
This PR updates some UI in Tool Settings:
- Reduced vertical spacing between separator lines.
- Fixed choose primary and parallel language Text to be set correctly along the left insets.
- Added localization for the toggle language messaging.
> GT-1567 tool settings change line spacing and parallel language spacing

- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordion/MobileContentAccordionView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentAccordionSection/MobileContentAccordionSectionView.xib
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentStack/MobileContentStackView.swift
This PR makes a change to the accordion content section view.  Before, content sections would only render a single text element in the expanded view.  The single text element has been replaced with a content stack which makes this view more dynamic in that it can render a stack of content.
This change can be seen in Staging > The Four (USA) tool in the Did you pray this prayer? accordion content section view.
> GT-1636 fix content sections to render content stack instead of single text element

- godtools/App/Features/ToolDetails/Domain/GetToolVersionsUseCase/GetToolVersionsUseCase.swift
- godtools/App/Features/ToolDetails/Domain/GetToolVersionsUseCase/ToolVersionDomainModel.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/Views/ToolDetailsVersionsView.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/Views/VersionsCard/ToolDetailsVersionsCardView.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/Views/VersionsCard/ToolDetailsVersionsCardViewModel.swift
- godtools/App/Share/SwiftUI Views/CircleSelector/CircleSelectorView.swift
This PR updates the selected state of the version card in ToolDetails.  The default version will start selected and tapping a new version will update the selected card by filling the circle on the card.
> GT-1418 Update tool version card selection state

- godtools/App/Flows/App/AppFlow.swift
This PR will re-instantiate the ToolsMenuView rather than keeping an instance of ToolsMenuView and calling reset.  I think creating a new instance is much preferred, keeping an instance and calling reset adds more management when it comes to resetting that entire view.
ToolsMenuView is re-allocated from deep links, dismissing the tutorial, completing onboarding, and app launch.
> GT-1545 instantiate tools menu instead of calling reset

- Podfile.lock
- godtools/App/Flows/App/AppFlow.swift
This PR fixes navigation to tools (lessons, favorites, all tools) from a quick link.  I moved the logic for navigating to the tools menu to occur before dismissing the onboarding flow.  This way when onboarding is dismissed a user is seeing the correct tools list.
Previously there was a navigation to tools menu happening before dismissing onboarding and another happening when dismissing onboarding completed.
> GT-1657 Fix navigation to tools from quick links

- godtools/App/Features/ToolDetails/ToolDetailsViewModel.swift
This fixes a bug in ToolDetails about section.  This bug can be reproduced when tapping the versions tab to view a tools versions, and then tapping the about section again to go back to the about details text.  The bug that occurs from this is you're unable to scroll all the way down to the bottom of the about details text when switching to versions and back to about.
This bug is related to using a UIViewRepresentable UITextView (UIKit) and does not occur if I have a plain Text (SwiftUI) element with a lot of text. For now this temporary hack will have to do until Text (SwiftUI) with tappable url links can be fully supported and the UIViewRepresentable UITextView> (UIKit) can be dropped.
> GT-1662 Temporary fix for the ToolDetails about section scroll issue

- godtools/App/Features/ToolSettings/Presentation/ToolSettings/Views/ToolSettingsOptions/ToolSettingsOptionsItemView.swift
Changed line limit on tool settings options from 1 to 2.
> GT-1673 Change tool settings options line limit to 2

- godtools/App/Share/Domain/UseCases/GetToolVersionsUseCase/GetToolVersionsUseCase.swift
This PR sets the description for a tool version card in ToolDetails to the translations translated tagline.
> GT-1671 Add variant description from translated tagline attribute

- godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
- godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/LessonCardsView/LessonCardsViewModel.swift
This PR updates the Favorites features lessons and favorited tools lists to be reloaded from the cache when the viewModels are initialized.  That way cached results are displayed immediately.
> GT-1674 Favorites data loading

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/Mail/MailView.swift
- godtools/App/Features/Mail/MailViewModel.swift
- godtools/App/Features/Mail/MailViewModelType.swift
- godtools/App/Features/Menu/Presentation/DeleteAccount/DeleteAccountHostingView.swift
- godtools/App/Features/Menu/Presentation/DeleteAccount/DeleteAccountView.swift
- godtools/App/Features/Menu/Presentation/DeleteAccount/DeleteAccountViewModel.swift
- godtools/App/Features/Menu/Presentation/Menu/MenuDataSource/MenuItem.swift
- godtools/App/Features/Menu/Presentation/Menu/MenuView.swift
- godtools/App/Features/Menu/Presentation/Menu/MenuViewModel.swift
- godtools/App/Features/Menu/Presentation/Menu/MenuViewModelType.swift
- godtools/App/Features/ToolDetails/Subviews/ToolDetailsAboutView.swift
- godtools/App/Flows/Flow+PresentNativeMailApp.swift
- godtools/App/Flows/FlowStep.swift
- godtools/App/Flows/Menu/MenuFlow.swift
- godtools/App/Share/SwiftUI Views/TextWithLinks/TextViewLinksCoordinator.swift
- godtools/App/Share/SwiftUI Views/TextWithLinks/TextWithLinks.swift
- godtools/Base.lproj/Localizable.strings
This PR adds an option to the Menu to Delete Account.  Tapping Delete Account will navigate to the DeleteAccountView with instructions on how to make a request to HelpDesk to delete your Okta account.  Tapping the help@cru.org will launch the native mail app (if available) with a prefilled message to send to the Help Desk.
> GT-1693 add delete account screen

- .github/workflows/build.yml
- .github/workflows/download_onesky_translations.yml
Increasing fastlane build settings timeout to 60 seconds.  Noticed quite often showBuildSettings will fail in GitHub actions after 4 tries.  Will see if increasing the timeout will help.
> GT Increase FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT

- godtools.xcodeproj/project.pbxproj
Noticed an error in GitHub Actions RunTests that SetupParallelLanguageView.swift was duplicated in Build Phases.  Fixed that by deleting the duplication.
Only 1 file now.
> GT Remove duplicate SetupParallelLanguageView.swift in Build Phases

- godtools/App/Flows/ToolNavigation/ToolNavigationFlow.swift
Removed TODO and left a comment that navigation is not necessary for meta tools.
> GT Removing TODO for meta tool navigation in ToolNavigationFlow

- godtools/App/Features/ToolDetails/Subviews/ToolDetailsVersionsView.swift
- godtools/App/Features/ToolDetails/Subviews/VersionsCard/ToolDetailsVersionsCardView.swift
- godtools/App/Features/ToolDetails/ToolDetailsView.swift
Had to force a width on the versions cards for the banner images.  Without it the banner images couldn't resize to anything and was taking the raw image width into account.
> GT-1701 fix tool details versions layout bug

- godtools.xcodeproj/project.pbxproj
ParallelLanguageListViewModel.swift was duplicated in build phases.
> GT Fix duplicated file in build phases

- godtools/App/Features/Tools/ToolsMenu/ToolsMenuView.swift
- godtools/App/Flows/App/AppFlow.swift
Hey @rachaelblue I noticed in your PR for GT-1694 I didn't fully remove the reset method on ToolsMenuView.  This PR finishes that work and there was one additional place this affected was when you are in the Teach Me to Share tool and at the end of the tool you tap the button to Go To Lessons.  When that happens ToolsMenuView is now re-instantiated instead of reset.
> GT-1703 Removed reset method on ToolsMenuView

- godtools/App/Share/Data/LanguagesRepository/Api/Models/LanguageModel.swift
- godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
- godtools/App/Share/Data/ResourcesRepository/Cache/Sync/RealmResourcesCacheSync.swift
- Changed to decodeIfPresent in LanguageModel.
- Need to keep older translations in the realm database until some more testing can be done around removing those.
> GT keep translations in database

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/DownloadTool/DownloadTool/DownloadToolViewModel.swift
- godtools/App/Flows/DownloadToolTranslations/DownloadToolTranslationsFlow.swift
- godtools/App/Flows/FlowStep.swift
- godtools/App/Flows/NetworkErrorAlert/Flow+NetworkErrorAlert.swift
- godtools/App/Flows/ToolNavigation/ToolNavigationFlow.swift
- godtools/App/Share/Data/TranslationsRepository/TranslationsRepository.swift
- godtools/App/Share/Data/URLResponseError.swift
- godtools/App/Share/Data/URLResponseObject.swift
- godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/GetToolTranslationsFilesUseCase.swift
- godtools/App/Share/Extensions/Error+NetworkError.swift
- godtools/App/Share/Views/AlertMessageView/Models/ResponseErrorAlertMessage.swift
This PR fixes 2 issues.
1. Tapping the close button from the downloading tool progress modal wasn't dismissing the download progress modal.
2. An alert wasn't being presented when downloading a tool failed due to no network connection.
Both of these issues are related and resolved by ensuring the download tool progress modal is dismissed when the combine publisher fails.  This line here -> (https://github.com/CruGlobal/godtools-swift/blob/GT-1769-fix-downloading-tool-alert/godtools/App/Flows/DownloadToolTranslations/DownloadToolTranslationsFlow.swift#L46)
Some other changes include:
- Adding Flow+NetworkErrorAlert extension for presenting URLResponseErrors.
- Deprecating ResponseErrorAlertMessage.
- Removed the didCloseClosure in DownloadToolViewModel in place of using a FlowStep.
> GT-1769 fix downloading tool alert

- godtools.xcodeproj/project.pbxproj
- godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
- godtools/App/Features/ToolDetails/ToolDetailsViewModel.swift
- godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
- godtools/App/Share/Data/ResourcesRepository/Api/Models/ResourceModel.swift
- godtools/App/Share/Domain/UseCases/GetLanguageAvailabilityStringUseCase/GetLanguageAvailablityStringUseCase.swift
- godtools/App/Share/Domain/UseCases/GetToolIsFavoritedUseCase/GetToolIsFavoritedUseCase.swift
- godtools/App/Share/Domain/UseCases/GetToolUseCase/GetToolUseCase.swift
- godtools/App/Share/Domain/UseCases/GetToolUseCase/ToolDomainModel.swift
- godtools/App/Share/Domain/UseCases/ToggleToolFavoritedUseCase/ToggleToolFavoritedUseCase.swift
- godtools/App/Share/Protocols/LanguageSupportable.swift
https://jira.cru.org/browse/GT-1777
- Cleaned up the remaining `ResourceModel` dependencies inside `ToolCardViewModel`
- In `GetLanguageAvailabilityStringUseCase`, `ResourceModel` was being passed in, and in some cases it was a tool and others it was a lesson.  This brings us back to the question of whether or not we want lessons to share tool code or have duplicated code.  I tend think it makes sense to share behavior by using protocols, but still keep the domain models separate-- `ToolDomainModel` and `LessonDomainModel`.  So, I made a protocol `LanguageSupportable` so any domain model that conforms to it can use `GetLanguageAvailabilityStringUseCase` moving forward.  Thoughts?
> GT-1742 finish mapping resource model

- godtools/App/Share/Data/ResourcesRepository/ResourcesRepository.swift
If for any reason fetching resources from the bundle fails, still ensure resources are fetched from remote.  This would occur in non release builds because at the moment assets are only pre-bundled with release builds.
> GT fix to resources sync when running in debug 

- godtools/App/Features/ToolDetails/ToolDetailsViewModel.swift
- godtools/App/Features/ToolTraining/ToolTrainingViewModel.swift
- godtools/App/Services/Analytics/AnalyticsTracking/ExitLinkAnalytics.swift
- godtools/App/Services/Analytics/AnalyticsTracking/Models/ExitLinkModel.swift
- godtools/App/Services/Analytics/Firebase/FirebaseAnalytics.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Page/MobileContentPageViewModel.swift
- godtools/App/Share/Domain/UseCases/GetLanguageUseCase/GetLanguageUseCase.swift
- godtools/App/Share/Domain/UseCases/GetLanguageUseCase/LanguageDomainModel.swift
This PR is the beginning work for Epic Analytics Content Language.  The focus of this epic is to fix the contentlanguage and contentlanguagesecondary being sent to Firebase analytics.  Currently those parameters are hardcoded to the language settings primary and parallel languages which isn't desired in all situations.
The following work for this PR includes:
Update the following method signatures in FirebaseAnalytics.swift to accept a contentLanguage and secondaryContentLanguage.  
- trackScreenView
- trackAction
- trackExitLink
Require contentLanguage and secondaryContentLanguage on trackExitLink method and update places in the app to send the correct contentLanguage and secondaryContentLanguage for ExitLink analytics.
Future:
Require contentLanguage and secondaryContentLanguage on …
> GT-1782 send correct content language on exit link events

- godtools.xcodeproj/project.pbxproj
- godtools/App/Share/Data/ResourcesRepository/Api/Models/ResourceModel+LanguageSupportable.swift
- godtools/App/Share/Data/ResourcesRepository/Api/Models/ResourceModel.swift
Moved LanguageSupportable logic from ResourceModel into its own file that way ResourceModel.swift is free from the LanguageSupportable.swift dependency.  
The build phase script for downloading initial resources is dependent on ResourceModel.swift and didn't want to add the additional LanguageSupportable.swift to that since it isn't needed by that build phase script.
> GT-Moved LanguageSupportable on ResourceModel into separate file extension

- godtools/App/Features/Tools/SwiftUI/AllTools/AllToolsContentViewModel.swift
When landing on AllTools we need to send a firebase event iam_tools which is used for triggering firebase messages.
> GT-1547 Send firebase event iam_tools

- godtools/App/Features/ToolSettings/ToolSettings/Subviews/ToolSettingsShareables/ToolSettingsShareableItemView.swift
- Set the shareable image size to match the containing view
- Set the background color of the containing view in the event the image is cropped due to aspectFit ratio and if the image is transparent
> GT-1682 Fix shareable image sizing

- godtools.xcodeproj/project.pbxproj
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentText/MobileContentTextView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentText/MobileContentTextViewModel.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentText/MobileContentTextViewModelType.swift
- godtools/App/Share/Extensions/UILabel+Underline.swift
I was able to add support for both bold and underline, I need to look into italics a little more.  I'm pretty sure italics would work for system fonts, but because we're also using custom fonts we will most likely need to add italic fonts to the project for those unless we switch to system fonts.
> GT-1120 Add support for bold and underline on content text elements in renderer

- godtools/App/Flows/App/AppFlow.swift
The issue here was popping back to the previous viewController in the navigation stack rather than the tools menu.
> GT-1544 Fix openers back to home

- Podfile.lock
- godtools/App/Share/Data/TranslationsRepository/TranslationsRepository.swift
- godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/GetToolTranslationsFilesUseCase.swift
With settings primary language English and parallel language Spanish, sometimes a lesson would open in Spanish.
The issue was downloading the translations is concurrent and could finish in any order.  Updated both the UseCase and Data Layer to maintain the downloaded order of translations.
> GT-1798 Fix bug where lesson would sometimes open in the parallel language (Spanish)

- Podfile.lock
- godtools/App/Features/LanguageSettings/Presentation/ChooseLanguage/ChooseLanguageViewModel.swift
When choosing a parallel language from language settings, there was a Clear button in the top right of the navigation bar that allowed users to delete the parallel language from settings.  That logic got lost during the refactor.  This PR fixes that and shows the button to delete the settings parallel language if a parallel language exists.
> GT-1804 restore button to delete parallel language

- Podfile.lock
- godtools/App/Features/Lessons/Lessons/LessonsView/LessonsViewModel.swift
- godtools/App/Features/Tools/SwiftUI/AllTools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
- godtools/App/Features/Tools/SwiftUI/AllTools/ToolCategoriesView/ToolCategoriesViewModel.swift
- godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/BaseFavoriteToolsViewModel.swift
- godtools/App/Features/Tools/SwiftUI/Favorites/FavoriteToolsView/ViewModels/FavoriteToolsViewModel.swift
- godtools/App/Features/Tools/SwiftUI/Favorites/FavoritesContentViewModel.swift
- godtools/App/Features/Tools/SwiftUI/Favorites/FeaturedLessonsView/FeaturedLessonCardsViewModel.swift
- godtools/App/Share/SwiftUI Views/LessonCardView/ViewModels/LessonCardViewModel.swift
https://jira.cru.org/browse/GT-1805
The headers weren't showing up if you select a primary language that doesn't have translations for the headers, swipe the app out of memory, and then open it back up.  This isn't related to iOS 16, it would've happened on any device.
> GT-1805 missing headers

- Podfile.lock
- godtools/App/Features/Tools/SwiftUI/Favorites/AllFavoriteToolsView/AllFavoriteToolsView.swift
In iOS 16 the system navigation back button will automatically appear when using SwiftUI.  For now we will have to hide those on the SwiftUI View.
> GT-1806 fix duplicate back button on all favorites

- godtools/App/Features/Tools/ToolsMenu/ToolsMenuView.swift
- godtools/App/Flows/App/AppFlow.swift
This PR deals with navigation to the lessons list which can happen from 2 situations:
1. User opens lesson from the lessons list and then closes the lesson.
2. User deep links into a lesson and then closes a lesson.
In this change a check is made if the ToolsMenu already exists in the navigation stack, if it does we manually tab to the lessons list and then pop back to the lessons list rather than creating a new instance every time a lesson is closed.
> GT-1494 Fix closing lesson to lessons list from deep link

- godtools/App/Features/Menu/About/AboutViewModel.swift
- godtools/App/Features/Menu/Menu/MenuViewModel.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
- godtools/Base.lproj/Localizable.strings
Currently localized text for "About" was being shared in 3 places of the app.
1. Tool Details screen, the about section title.
2. In the menu there is a menu option with About title.
3. Tapping the menu About option would open a screen with navigation title About.
There are now 2 phrases for the "About" text and the "about" phrase has been removed.
aboutApp.navTitle
toolDetails.about.title
> GT-1642 Create 2 phrases for "About" text

- godtools.xcodeproj/project.pbxproj
- godtools/App/Share/Data/LanguagesRepository/Cache/Sync/RealmLanguagesCacheSync.swift
This PR fixes a high rate crash in Firebase.  The languages sync logic was accessing realm language objects that had already been deleted from the Realm Database leading to a crash.
https://console.firebase.google.com/u/0/project/godtools-b2f82/crashlytics/app/ios:org.cru.godtools/issues/903f6aa72ea166d4ccdcdb05d040c13d?time=last-seven-days&sessionEventKey=9c4efb4fdbbe42b8b7ef9b27c41dd945_1730589182804246939
> Fix Firebase crash in languages sync

- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/App/Share/Data/ResourcesRepository/Cache/Sync/RealmResourcesCacheSync.swift
- godtools/App/Share/Data/TrackDownloadedTranslationsRepository/Cache/Models/RealmDownloadedTranslation.swift
- godtools/App/Share/Data/TrackDownloadedTranslationsRepository/Cache/TrackDownloadedTranslationsCache.swift
- godtools/App/Share/Data/TrackDownloadedTranslationsRepository/DownloadedTranslationDataModel.swift
- godtools/App/Share/Data/TrackDownloadedTranslationsRepository/DownloadedTranslationDataModelType.swift
- godtools/App/Share/Data/TrackDownloadedTranslationsRepository/TrackDownloadedTranslationsRepository.swift
- godtools/App/Share/Data/TranslationsRepository/Cache/Models/RealmTranslation.swift
- godtools/App/Share/Data/TranslationsRepository/TranslationsRepository.swift
This PR fixes logic for falling back to already downloaded translations if a new translation download fails.  
If a new Translation download fails, we take the resourceId and languageId and use that to query against RealmDownloadedTranslation objects.  Any matching RealmDownloadedTranslation are then sorted by version and the latest version is used as the fallback. 
The Sync will also keep Translation objects in the database that match any existing RealmDownloadedTranslation objects by (resourceId, languageId and latest version).
Attributes resourceId, languageId, and version were introduced to RealmDownloadedTranslation objects in this PR that map from the downloaded Translation object.
> GT-1810 always persist downloaded translation

- godtools/App/Features/Menu/Presentation/Account/AccountViewModel.swift
- godtools/App/Features/Menu/Presentation/Account/Subviews/AccountSections/AccountSectionsView.swift
This PR updates AccountViewModel to use analytics screen names from ```GodToolsShared``` for the account activity and account global activity screen tracking.
Also updated the view to send analytics screen tracking when account section is first viewed.
> G-1861 Use analytics constants from GodToolsShared

- godtools/App/Share/Data/TranslationsRepository/TranslationsRepository.swift
- godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/GetToolTranslationsFilesUseCase.swift
This PR adds a fix to the download translations logic where we always want to show the latest downloaded translation if downloading a new translation fails due to no network connection.
The issue here was we maintain the order of downloaded translations by sorting those on the translation id.  In the case where we use a fallback translation, the translation id will never match the translation to download because they're different translation models.  Instead we need to search on the translation resource id and language id.
> GT-1810 Fixed maintaining the order of downloaded translations

- godtools/App/AppDelegate.swift
- godtools/App/Flows/App/AppFlow.swift
This PR removes UIWindow allocation from AppDelegate init() and moves to didFinishLaunching() in order to fix the following warning that was in the Xcode console.
```UIWindows were created prior to initial application activation. This may result in incorrect visual appearance```
> GT-1884 Fix UIWindow warning

- godtools/App/Flows/App/AppFlow.swift
This PR makes a fix to deep link navigation.  The issue was deep link navigation would trigger on a closure that in some cases wouldn't get called.  Ended up moving that call out of the closure.  Also made the following changes:
- Renamed ```setupNavBar()``` method to ```configureNavBarForDashboard()```.
- Merged ```buildNewDashboard()``` method into ```navigateToDashboard()``` because there was some logic in there that should trigger anytime navigation to dashboard takes place.
> GT-1817 Fix to deep link navigation

- godtools/App/Features/Dashboard/Presentation/Home/FavoritesContentView.swift
- godtools/App/Share/SwiftUI Views/BackwardCompatibleList.swift
There was a strange scroll effect that was occurring in iOS 16 for favorites, tool spotlight, and tool categories. (https://jira.cru.org/browse/GT-1875)
Found a related issue posted to Stackoverflow here:  https://stackoverflow.com/questions/74042635/nested-scrollview-in-a-list-refreshable-strange-behaviour-in-ios-16
Seems to be fixed by using a ScrollView instead of a List.  It's nice to use a ScrollView here too since we don't have to worry about how the System might style the List element and since we have custom content going into the ScrollView.
Also removed some iOS 13 code in BackwardsCompatibleList.swift since we're now pointing to iOS 14.
> GT-1875 Fix strange scroll effect in iOS 16

- godtools/App/Share/Data/GlobalAnalyticsRepository/Cache/RealmGlobalAnalytics.swift
- godtools/App/Share/Data/GlobalAnalyticsRepository/Cache/RealmGlobalAnalyticsCache.swift
The existing RealmGlobalAnalytics object was getting mutated outside of a write transaction which would cause a crash.  Also, since id is a primaryKey it cannot be mutated from a write transaction and instead set when a new object is created.
> GT-1894 Fix crash when writing to existing RealmGlobalAnalytics object

- godtools/App/Share/ColorPalette.swift
There is an existing helper method for fetching a ```Color``` with RGB values and thought it would be a good idea to have the same helper method for fetching a ```UIColor``` since we are still using UIKit in some places.
> GT Add method for fetching UIColor with RGB values

- godtools/App/Share/SwiftUI Views/GTBlueButton.swift
- godtools/App/Share/SwiftUI Views/GTWhiteButton.swift
This PR updates the shared Button views to include the SwiftUI Button element.  By doing so we get the system highlight when a button is tapped which will highlight the Text element.  Basically any elements within the Button content or highlighted and since the Rectangle is a clear color there will be no highlight effect on the Rectangle element.
- Added a Rectangle element within the Button content which is needed for the tap area of the button.
> GT-1926 Update shared buttons to include SwiftUI Button element.

- godtools/App/Flows/App/AppFlow.swift
The issue was when a tool needs to be downloaded it presents the download modal.  That was failing because the learn to share modal was presented.  The fix is to ensure that the learn to share modal is dismissed first, then present the download modal.
> GT-1919 Fix learn to share navigation to tool

- godtools/App/Features/LanguageSettings/Domain/UseCases/GetSettingsPrimaryLanguageUseCase/GetSettingsPrimaryLanguageUseCase.swift
- godtools/App/Share/Data/LanguageSettingsRepository/Cache/LanguageSettingsCache.swift
- godtools/App/Share/Data/LanguageSettingsRepository/LanguageSettingsRepository.swift
In `GetSettingsPrimaryLanguageUseCase`, the `getPrimaryLanguagePublisher()` wasn't firing immediately, which was causing a noticeable lag in generating the lesson titles.  By adding `.prepend(getPrimaryLanguage())` to the publisher, it will immediately fire with the current primary language value while we wait for any further values to come through.
The other thing I learned is that `CombineLatest(_, _)` doesn't actually fire until _both_ publishers being combined have a value:
```
The combined publisher doesn’t produce elements until each of its upstream publishers publishes at least one element.
```
https://developer.apple.com/documentation/combine/publishers/sequence/combinelatest(_:)
In this case, we don't care if both publishers have a value a simultaneously, we just want to be …
> GT-1933 Lesson Titles Loading Slowly

- godtools/App/Features/ToolSettings/ShareTool/ShareToolViewModel.swift
Needed to remove ```www.``` from ```https://knowgod.com``` since we don't support ```https://www.knowgod.com``` in Universal links.
> GT-1942 Fix knowgod.com share link

- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
- godtools/App/Share/Views/PageNavigationCollectionView/PageNavigationCollectionView.swift
This PR fixes page navigation in tract rendering when changing the primary language from a left to right or right to left language.  Navigation direction should match the primary language direction (left to right, right to left).
This was fixed by making ```pageNavigationSemanticContentAttribute``` an ```ObservableValue``` on the ViewModel ``` and when this value changes the View will set the semantic content attribute on the UICollectionView.
> GT-1931 Fix ToolSettings language flip

- godtools/App/Share/Data/LanguageSettingsRepository/LanguageSettingsRepository.swift
Hey @rachaelblue I noticed after merging ```GT-1933``` which fixed the language title observing that when I chose a new primary language from the languages list, the primary language button title wouldn't update on the prior screen.
This screen here wouldn't update after choosing Arabic:
I didn't realize, but ```Empty()``` will cause a publisher to finish immediately.  So what happened was the first time that button was set the publisher finished and no longer received changes.
https://developer.apple.com/documentation/combine/empty
It also appears that using ```Empty(completeImmediately: false)``` still wouldn't send changes.  
```Empty()``` seems a bit misleading in the naming as you would expect an empty response. 
Instead changed to use ```map``` to return ```Void```.  Could have also …
> GT-1933 Fix settings primary language changed observing

- godtools.xcodeproj/project.pbxproj
I think ```godtoolsRelease.entitlements``` was auto generated when adding universal links for Firebase.  Removed and set back to ```godtools.entitlements```.
> GT-Change release entitlements file from godtoolsRelease to godtools

- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentEmbeddedVideo/MobileContentEmbeddedVideoView.swift
- godtools/App/Share/Views/PageNavigationCollectionView/PageNavigationCollectionView.swift
I believe a possible fix for this was removing the ```collectionView.reloadData()``` call in ```PageNavigationCollectionView.swift``` ```override func layoutSubviews()```.  I'm not exactly sure why I had that call in there, I know I ran into some issues with auto layout constraints in the renderer.  However, I don't think it's a good idea to reload the collectionView anytime layoutSubviews() is called.  Could be extensive.
I noticed when the embedded YouTube video in the renderer went into FullScreen it caused layoutSubviews() to trigger which ended up deallocating the rendered page and building it again.  This would occur multiple times on that view which was not good.
I also ended up setting some delegates to null when the embedded video was deallocated.  This was just for added measure …
> GT-1946 Fix WebKit crash from Firebase

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/ChooseYourOwnAdventure/ChooseYourOwnAdventureViewModel.swift
- godtools/App/Features/Lesson/Lesson/LessonViewModel.swift
- godtools/App/Features/Tool/ToolViewModel.swift
- godtools/App/Flows/ChooseYourOwnAdventure/ChooseYourOwnAdventureFlow.swift
- godtools/App/Flows/Lesson/LessonFlow.swift
- godtools/App/Flows/ToolNavigation/ToolNavigationFlow.swift
- godtools/App/Flows/Tract/TractFlow.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/Models/MobileContentPagesPage.swift
- godtools/App/Share/Data/DeepLinkingService/ParsedDeepLink/ToolDeepLinkPage+MobileContentPagesPage.swift
This PR fixes deeplinking to a ```cyoa``` tool with a pageId that is a category.  In iOS if the page is a category page, not (```intro``` or ```categories```) then we will build the intro, categories, and then category page in the renderer navigation stack.
- Remove ```page: Int?``` from ```MobileContentPagesViewModel``` ```init()``` and replace with ```initialPage: MobileContentPagesPage?``` which encapsulates either a ```pageId: String``` or ```pageNumber: Int``` for the initial page to renderer.
- Change ```MobileContentPagesViewModel``` ```currentPage``` attribute to ```currentRenderedPageNumber```.
- Update renderer navigation to include page ids.
> GT-1951 Fix deeplink to cyoa

- godtools/App/Services/Renderer/Views/ChooseYourOwnAdventure/ViewFactory/ChooseYourOwnAdventurePageViewFactory.swift
Because the categories page was inserted as the starting page on a deeplink it was using the content insets of 60 that is applied to the intro page.
> GT-1953 Fix categories list spacing issue

- godtools/App/Services/Renderer/Renderer/MobileContentPageRenderer.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
The main fix for this is removing ```pagesToRender = renderablePages``` when navigating to a specific page number.  ```renderablePages``` encompassed all pages including hidden which we don't want include all hidden pages in the renderer.
> GT-1951 Fix navigation to page number

- godtools.xcodeproj/project.pbxproj
- godtools/godtools.entitlements
This PR does some pre-configuration for Apple Sign In.  
- Configured Apple Id (org.cru.godtools) to include Sign in with Apple.
- Created a Services Key in Apple Developer and shared private key with Andrew Roth for validating authorization code.
- Downloaded release and production provisioning with included Sign in with Apple and imported into Xcode project.
- Added Sign in with Apple to capabilities / godtools.entitlements.
> GT Update provisioning and entitlements for Apple Sign In

- godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
- godtools/App/Features/Menu/Domain/UseCases/LogOutUserUseCase/LogOutUserUseCase.swift
- godtools/App/Share/Data/MobileContentAuthTokenRepository/Cache/MobileContentAuthTokenCache.swift
- godtools/App/Share/Data/MobileContentAuthTokenRepository/Cache/MobileContentAuthTokenKeychainAccessor.swift
- godtools/App/Share/Data/MobileContentAuthTokenRepository/MobileContentAuthTokenRepository.swift
When a user logs out, delete the cached userId and auth token.  This won't account for the case where Okta logs a user out automatically-- not sure that there's a good way to know that.  But since Okta is being removed anyway, we may want to revisit this as other login methods are added.  It's also not strictly necessary that the auth token get deleted on logout, but preferable to leaving it there.
> GT-1847 delete auth token on logout

- .github/workflows/build.yml
- .github/workflows/download_onesky_translations.yml
This moves management of the OneSky secrets to be centralized in AWS. I will be deleting the previous OneSky secrets from GHA secrets once this is merged.
Manual run of the download latest translations workflow: https://github.com/CruGlobal/godtools-swift/actions/runs/4534218676
> Switch to loading OneSky secrets from AWS SSM

- godtools/App/Services/Renderer/Views/Tool/Views/Card/ToolPageCardView.swift
- godtools/App/Services/Renderer/Views/Tool/Views/Cards/Models/ToolPageCardTopConstantState.swift
- godtools/App/Services/Renderer/Views/Tool/Views/Cards/ToolPageCardsView.swift
- godtools/App/Services/Renderer/Views/Tool/Views/Page/ToolPageView.swift
This PR updates tracts card headers to display the full title when in the starting state.  The rendering states for tract cards are (hidden, collapsed, starting, showing, showingKeyboard).
The rendering state that needed to be fixed was the ```starting``` state which shows all cards at the bottom of the screen with visible title headers.
> GT-1699 support 2 lines of text in rendered card header

- godtools/App/Features/ToolSettings/ShareToolScreenTutorial/ShareToolScreenTutorialView.swift
- godtools/App/Flows/DownloadToolTranslations/DownloadToolTranslationsFlow.swift
- godtools/App/Flows/LearnToShareTool/LearnToShareToolFlow.swift
- godtools/App/Flows/Onboarding/OnboardingFlow.swift
- godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
- godtools/App/Flows/Tutorial/TutorialFlow.swift
- godtools/App/Flows/VideoModal/Flow+VideoModal.swift
- godtools/App/Share/NavControllers/ModalNavigationController.swift
There was some inconsistencies between the tutorials (learn to share tool, tutorial behind menu) and the remote share screen tutorial in the way the navigation bar control color was getting set.  Updated to be consistent and use the shared GTblue color.
> GT-1925 Fix control colors to be consistent with shared GTBlue color

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/ToolDetailsAboutView.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/ToolDetailsSectionDescriptionTextView.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/Subviews/ToolDetailsVersionsView.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsView.swift
- godtools/App/Share/SwiftUI Views/TextWithLinks/TextWithLinks.swift
This PR makes follow updates to ToolDetailsView.swift:
- Updates TextWithLinks.swift (UITextView) to support dynamic type and enables About text in ToolDetails to support dynamic type.
- Adjusts About text and Versions text padding to match to edge of screen.
- Add ToolDetailsSectionDescriptionTextView to share between About and Versions sections.
> GT-1929 Allow TextWithLinks (UITextView) to support dynamic type

- Podfile
- Podfile.lock
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
- godtools/App/Flows/DownloadToolTranslations/DownloadToolTranslationsFlow.swift
- godtools/App/Share/Data/TranslationsRepository/ManifestParser/TranslationManifestParser.swift
- godtools/App/Share/Data/TranslationsRepository/TranslationsRepository.swift
- godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/GetToolTranslationsFilesUseCase.swift
Hey @frett was able to use async.  This PR includes:
- Replace IosManifestParser with ManifestParser to parse async.
- Needed to ensure parse async is called from main thread.
- Also on the getToolTranslationsFilesPublisher there is a closure downloadStarted which needed to be dispatched to the main thread in DownloadToolTranslationsFlow.swift.
> GT-1997 parse manifest async

- godtools.xcodeproj/xcshareddata/xcschemes/GodTools-Production.xcscheme
- godtools.xcodeproj/xcshareddata/xcschemes/godtools.xcscheme
Removed SharedAppleExtensionsTests from the godtools and GodToolsProduction schemes.
SharedAppleExtensions swift package has been removed and those tests are now part of the godtoolsTests target.
> GT Remove SharedAppleExtensionsTests target from tests

- .github/codecov.yml
- .github/workflows/build.yml
- Gemfile
- godtools.xcodeproj/xcshareddata/xcschemes/GodTools-Production.xcscheme
- godtools.xcodeproj/xcshareddata/xcschemes/godtools.xcscheme
This PR is enabling code coverage reports to be uploaded to codecov under CruGlobal/godtools-swift
- Point ```godtools``` scheme Tests to Production build configuration.
- Add upload codecov reports in workflow.
- Enable godtools-swift in codecov CruGlobal account https://app.codecov.io/gh/CruGlobal/godtools-swift and add token to GitHub secrets
> GT Upload code coverage reports to CruGlobal codecov account

- fastlane/.env.default
Adding team id to fastlane env.  Will need for code signing and testflight deployment.
https://github.com/CruGlobal/cru-fastlane-files/pull/37
> GT Add team id to fastlane env

- godtools/App/Features/Menu/Domain/UseCases/AuthenticateUserUseCase/AuthenticateUserUseCase.swift
- godtools/App/Features/Menu/Domain/UseCases/GetUserAccountProfileNameUseCase/GetUserAccountProfileNameUseCase.swift
- godtools/App/Share/Data/UserAuthentication/AuthenticationProviders/AuthenticationProviderInterface.swift
- godtools/App/Share/Data/UserAuthentication/AuthenticationProviders/FacebookAuthentication+AuthenticationProviderInterface.swift
- godtools/App/Share/Data/UserAuthentication/AuthenticationProviders/GoogleAuthentication+AuthenticationProviderInterface.swift
- godtools/App/Share/Data/UserAuthentication/UserAuthentication.swift
- Add ```func getAuthUserPublisher() -> AnyPublisher<AuthUserDomainModel?, Error>``` to AuthenticationProviderInterface.
- Implement getAuthUserPublisher in Facebook and Google Authentication providers.
> GT-2012 Add getAuthUserPublisher to AuthenticationProviderInterface

- godtools/App/Features/Menu/Domain/UseCases/AuthenticateUserUseCase/AuthenticateUserUseCase.swift
- godtools/App/Features/Menu/Presentation/LegacyMenu/LegacyMenuViewModel.swift
- godtools/App/Features/Menu/Presentation/SocialSignIn/SocialSignInViewModel.swift
- godtools/App/Flows/FlowStep.swift
- godtools/App/Flows/Menu/MenuFlow.swift
In this PR reload the menu data source after a login is made.  Needed to send a PassthroughValueSubject to the SocialSignInViewModel in order to communicate back to the MenuViewModel.
> GT-2026 update menu section after login

- godtools.xcodeproj/project.pbxproj
- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/App/Share/Data/MobileContentAuthTokenRepository/Cache/MobileContentAuthTokenCache.swift
- godtools/App/Share/Data/MobileContentAuthTokenRepository/Cache/Realm/RealmMobileContentAuthToken.swift
- godtools/App/Share/Data/MobileContentAuthTokenRepository/Cache/Realm/RealmMobileContentAuthTokenCache.swift
- godtools/App/Share/Data/MobileContentAuthTokenRepository/MobileContentAuthTokenDataModel.swift
- godtools/App/Share/Data/MobileContentAuthTokenRepository/MobileContentAuthTokenRepository.swift
- godtools/App/Share/Data/RealmDatabase/Configuration/RealmDatabaseProductionConfiguration.swift
Updated the MobileContentAuthTokenCache to include the expiration date in the event we need to check if the mobile-content-api auth token has expired.
- Cache the auth token expiration date.
- Add isExpired to check if the auth token has expired.
> GT Cache mobile-content-api auth token expiration date

- godtools.xcodeproj/project.pbxproj
- godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
- godtools/App/AppBuild/AppBuild.swift
- godtools/App/AppBuild/AppEnvironment.swift
- godtools/App/AppConfig/AppConfig.swift
- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/Info.plist
This PR contains the following changes:
- Adding AppEnvironment enum for staging and production.
- In AppBuild.swift set environment based on the build configuration.
- AppConfig.swift will now configure values based on the environment rather than configuration to reduce any inconsistencies between staging and production.
- Added staging and production clientId and serverClientId for Google SignIn.
- Added staging reverse client id for Google SignIn.
- Added AppleAuthentication as a provider to UserAuthentication.swift.
> GT Include serverClientId for Google Sign-In

- godtools/App/Features/Menu/Presentation/SocialSignIn/SocialSignInViewModel.swift
- godtools/App/Share/Common/SharedAppleExtensions/Combine/Publisher/Publisher+ReceiveOnMain.swift
If any sort of error occurs, a `flatMap` in a publisher chain won't execute unless the error is caught.  So, I added a `catch` that essentially allows us to ignore the error for a second in order to call `receiveOnMainIfNeeded`, and then re-propagates the existing error after we know we're on main.
Changed SocialSignInView to use `received(on:)` rather than the `receiveOnMain` extension.  Created a ticket to look into the favorite tools animation glitch again, which was the initial reason the extension was created: https://jira.cru.org/browse/GT-2054
(I removed the `subscribe(on:)` from the extension since it seemed risky.)
> GT-2052 ReceiveOnMain with Error

- godtools/App/Features/Dashboard/Presentation/Tools/ToolCardsView/ToolCardView/ViewModels/ToolCardViewModel.swift
- godtools/App/Share/SwiftUI Views/ResourceCard Subviews/ResourceCardBannerImageView.swift
Created two follow-up tickets too:
1. to remove the `receiveOnMain` extension (https://jira.cru.org/browse/GT-2056)
2. to investigate using a local image cache (https://jira.cru.org/browse/GT-2055)
> GT-2054 add animation modifier to banner image view

- godtools/App/Features/Menu/Domain/UseCases/AuthenticateUserUseCase/AuthenticateUserUseCase.swift
- godtools/App/Share/Data/MobileContentApiAuthSession/MobileContentApiAuthSession.swift
- godtools/App/Share/Data/UserAuthentication/AuthenticationProvider/AuthenticationProviderInterface.swift
- godtools/App/Share/Data/UserAuthentication/AuthenticationProvider/Providers/AppleAuthentication+AuthenticationProviderInterface.swift
- godtools/App/Share/Data/UserAuthentication/AuthenticationProvider/Providers/FacebookAuthentication+AuthenticationProviderInterface.swift
- godtools/App/Share/Data/UserAuthentication/AuthenticationProvider/Providers/GoogleAuthentication+AuthenticationProviderInterface.swift
- godtools/App/Share/Data/UserAuthentication/AuthenticationProvider/Response/AuthenticationProviderResponse+MobileContentAuthProviderToken.swift
- godtools/App/Share/Data/UserAuthentication/AuthenticationProvider/Response/AuthenticationProviderResponse.swift
- godtools/App/Share/Data/UserAuthentication/UserAuthentication.swift
Hey @rachaelblue I made some more changes to UserAuthentication providers.  
- Changed AuthenticationProviderResponse identityToken, accessToken, refreshToken to be optional.  We aren't guaranteed to get an identity token, access token, or refresh token from our auth provider's and rather than include an empty string would prefer to include null.
- Changed the return type in Extension AuthenticationProviderResponse+MobileContentAuthProviderToken to return a Result type this way if identityToken, accessToken, refreshToken happen to be null or invalid we can return an Error here.
- Changed AuthenticationProviderInterface method name from renewAccessTokenPublisher() to renewTokenPublisher() since we are dealing with more than an access token with our auth providers.
> GT updates to user authentication provider

- godtools/App/Features/Menu/Domain/UseCases/LogOutUserUseCase/LogOutUserUseCase.swift
- godtools/App/Features/Menu/Presentation/LegacyMenu/LegacyMenuViewModel.swift
- godtools/App/Features/Menu/Presentation/Menu/MenuView.swift
- godtools/App/Features/Menu/Presentation/Menu/MenuViewModel.swift
- godtools/App/Features/Menu/Presentation/Menu/Subviews/MenuSectionView.swift
- godtools/App/Flows/Menu/MenuFlow.swift
This PR has the following changes:
- Add viewModel inputs to new menu viewModel design. (Copied over from LegacyMenuViewModel.swift).
- Update MenuSectionView to use ViewBuilder in order to toggle visibility of menu options
> GT-2061 add new menu design view model inputs

- godtools/App/Features/Articles/Presentation/ArticleCategories/ArticleCategoriesViewModel.swift
- godtools/App/Features/Dashboard/Presentation/Lesson/LessonViewModel.swift
- godtools/App/Features/Dashboard/Presentation/Tool/ToolViewModel.swift
- godtools/App/Flows/Article/ArticleFlow.swift
- godtools/App/Services/Analytics/UserAnalytics/UserAnalytics.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
This PR fixes counters for the following:
- Track lesson completion counter once per session (lesson open).
- Add article tool open counting.
- Moved lesson and tool open counting into base viewModel and check resource type when it comes to incrementing a tract vs lesson.
> GT-2081 fix tool and lesson counters

- godtools/App/Services/Localization/Bundle/LocalizableStringsBundle.swift
Fixed issue where phrase was returning null if the phrase and key are equal.
> GT-2076 Remove check for localized string equaling key

- godtools/App/Features/Dashboard/Presentation/ChooseYourOwnAdventure/ChooseYourOwnAdventureViewModel.swift
- godtools/App/Features/Dashboard/Presentation/Tool/ToolViewModel.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
This fixes an issue where tool cards are closing when toggling between the primary and parallel language in a tool during screen share.
> GT-2103 Provide page position state when switching the page renderer

- godtools/App/Features/Dashboard/Presentation/Dashboard/DashboardView.swift
- godtools/App/Features/LearnToShareTool/Presentation/LearnToShareTool/LearnToShareToolView.swift
- godtools/App/Features/Menu/Presentation/Tutorial/TutorialView.swift
- godtools/App/Features/Onboarding/Presentation/OnboardingTutorial/OnboardingTutorialView.swift
- godtools/App/Share/SwiftUI Views/PageControl/PageControl.swift
This PR fixes a bug in SwiftUI's TabView that occurred only in iOS 16.  iOS 15 there is no issue.  When the device is in a right to left language such as Arabic and scrolling through a TabView, the pager tied to the TabView would end up displaying the incorrect page index.  It would be mirrored, or flipped.  Adding this modifer fixes that (https://developer.apple.com/documentation/swiftui/view/flipsforrighttoleftlayoutdirection(_:)) In reading the documentation there it says that is enabled by default.  However, doesn't seem to be the case when using a TabView in iOS 16.
> GT-2102 Fix TabView bug in iOS 16 when device is in right to left language (Arabic)

- godtools.xcodeproj/project.pbxproj
- godtools/App/AppDelegate.swift
- godtools/App/Services/Analytics/Firebase/FirebaseAnalytics.swift
- godtools/App/Services/Analytics/Google/DisableGoogleTagManagerLogging.swift
Should no longer be getting these messages in the Xcode console.
```
2023-08-25 09:10:50.892022-0400 godtools[13920:113784] GoogleTagManager info: Sending universal analytics hit: {
"&ate" = 0;
"&cd" = Lessons;
"&cd1" = ar;
"&cd21" = "GTM-547468H";
"&cd22" = 25;
"&cd24" = "GodTools App";
"&cd26" = 1692966941;
"&cd3" = home;
"&cd31" = "Not Logged In";
"&cd4" = "";
"&cd40" = undefined;
"&cd41" = undefined;
"&cd42" = undefined;
"&cd43" = undefined;
"&cd44" = undefined;
"&cd45" = undefined;
"&cd51" = app;
"&cd52" = "screen_view";
"&cd53" = 2;
"&cd55" = true;
"&idfa" = "00000000-0000-0000-0000-000000000000";
"&t" = screenview;
"&tid" = "UA-181145622-99";
"&uid" = undefined;
}
2023-08-25 09:10:50.896199-0400 godtools[13920:113784] GoogleTagManager info: Processing logged event: iam_mytools with …
```
> GT Add class to disable GoogleTagManager console logging

- godtools/App/Features/Dashboard/Presentation/Tools/Subviews/ToolCard/ToolCardView.swift
- Fix parallel language to align with tool card title.
- Add parallel language below tool category for thumbnail cards.
> GT-2082 Fix parallel language text alignment in tool card

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/Dashboard/Presentation/Dashboard/DashboardView.swift
- godtools/App/Features/Dashboard/Presentation/Dashboard/DashboardViewModel.swift
- godtools/App/Features/Dashboard/Presentation/Dashboard/Subviews/DashboardTabBar/DashboardTabBarView.swift
- godtools/App/Features/Dashboard/Presentation/Dashboard/Subviews/DashboardTabBar/Subviews/DashboardTabBarItem/DashboardTabBarItemView.swift
- godtools/App/Features/Dashboard/Presentation/Dashboard/Subviews/DashboardTabBar/Subviews/DashboardTabBarItem/DashboardTabBarItemViewModel.swift
- godtools/App/Features/LearnToShareTool/Presentation/LearnToShareTool/LearnToShareToolView.swift
- godtools/App/Features/Menu/Presentation/Tutorial/TutorialView.swift
- godtools/App/Features/Onboarding/Presentation/OnboardingTutorial/OnboardingTutorialView.swift
- godtools/App/Share/SwiftUI Views/PageControl/PageControl.swift
- godtools/App/Share/SwiftUI Views/PageControl/PageControlButton.swift
- godtools/App/Share/SwiftUI Views/PagedView/PagedView.swift
This PR fixes iOS 16 bugs with the TabView when in a right to left language.  Ended up having to force a TabView and any accompanying TabBarView or PageControl that controls the TabView to always be in a left to right environment.  Then manually adjust them for right to left languages. 
As of this PR only left to right languages will be supported on PagedView.  Once we start implementing the new App Language feature these will be able to support right to left.  Will create a PR pointing to the app-languages-feature to address that.  
- Add PagedView which wraps a TabView and forced the environment to left to right and manually adjust for right to left languages.
- Updated PageControl to always be in a left to right environment and manually adjust for right to left languages.
- Updated …
> GT-2102 fix tab view bug for iOS 16

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/Dashboard/Presentation/Dashboard/Subviews/DashboardTabBar/DashboardTabBarView.swift
- godtools/App/Share/Application/ApplicationLayout/ApplicationLayout.swift
- godtools/App/Share/Application/ApplicationLayout/ApplicationLayoutDirection.swift
- godtools/App/Share/SwiftUI Views/PageControl/PageControl.swift
- godtools/App/Share/SwiftUI Views/PagedView/PagedView.swift
- Update PagedView, PageControl, and DashboardTabBarView to default to ApplicationLayout.direction.layoutDirection instead of leftToRight.  
- Changed naming in ApplicationLayoutDirection for swiftUI and uiKit directions to layoutDirection and semanticContentAttribute.
> GT-2102 Default to ApplicationLayout.direction.layoutDirection instead of .leftToRight

- godtools.xcodeproj/project.pbxproj
- godtools/App/AppDelegate.swift
- godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
- godtools/App/Features/AppLanguage/Domain/UseCases/GetAppLanguageUseCase/AppLanguageDomainModel.swift
- godtools/App/Features/AppLanguage/Domain/UseCases/GetAppLanguageUseCase/GetAppLanguageUseCase.swift
- godtools/App/Features/AppLanguage/Domain/UseCases/GetInterfaceStringUseCase/DependencyInversion/GetInterfaceStringRepositoryInterface.swift
- godtools/App/Features/AppLanguage/Domain/UseCases/GetInterfaceStringUseCase/GetInterfaceStringUseCase.swift
- godtools/App/Features/LanguageSettings/Presentation/LanguageSettings/LanguageSettingsView.swift
- godtools/App/Features/LanguageSettings/Presentation/LanguageSettings/LanguageSettingsViewModel.swift
- godtools/App/Features/LanguageSettings/Presentation/LanguageSettings/Subviews/LanguageSettingsAppInterfaceLanguage/LanguageSettingsAppInterfaceLanguageView.swift
- godtools/App/Features/LanguageSettings/Presentation/LanguageSettings/Subviews/LanguageSettingsAppInterfaceLanguage/Subviews/AppInterfaceLanguageButtonView.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Flows/LanguageSettings/LanguageSettingsFlow.swift
- godtools/App/Services/Analytics/AnalyticsContainer+TrackActionAnalyticsInterface.swift
- godtools/App/Services/Analytics/AnalyticsContainer+TrackScreenViewAnalyticsInterface.swift
- godtools/App/Share/Data/AppLanguagesRepository/AppLanguageDataModel.swift
- godtools/App/Share/Data/AppLanguagesRepository/AppLanguagesRepository+GetAppLanguagesRepositoryInterface.swift
- godtools/App/Share/Data/AppLanguagesRepository/AppLanguagesRepository.swift
- godtools/App/Share/Data/LocalizationServices/LocalizationServices+GetInterfaceStringRepositoryInterface.swift
- godtools/App/Share/Domain/UseCases/TrackActionAnalyticsUseCase/DependencyInversion/TrackActionAnalyticsInterface.swift
- godtools/App/Share/Domain/UseCases/TrackActionAnalyticsUseCase/DependencyInversion/TrackActionAnalyticsPropertiesDomainModel.swift
- godtools/App/Share/Domain/UseCases/TrackActionAnalyticsUseCase/TrackActionAnalyticsUseCase.swift
- godtools/App/Share/Domain/UseCases/TrackScreenViewAnalyticsUseCase/DependencyInversion/TrackScreenViewAnalyticsInterface.swift
- godtools/App/Share/Domain/UseCases/TrackScreenViewAnalyticsUseCase/DependencyInversion/TrackScreenViewAnalyticsPropertiesDomainModel.swift
- godtools/App/Share/Domain/UseCases/TrackScreenViewAnalyticsUseCase/TrackScreenViewAnalyticsUseCase.swift
- godtools/App/Share/LanguageCode.swift
- godtools/App/Share/SwiftUI Modifiers/FlipForAppLanguage.swift
- godtoolsTests/App/Features/AppLanguage/Domain/UseCases/GetAppLanguageUseCase/GetAppLanguageUseCaseTests.swift
- godtoolsTests/App/Features/AppLanguage/Domain/UseCases/GetAppLanguageUseCase/TestsAppLanguagesRepository.swift
This PR unlocks some work for fixing issues with right to left and left to right layouts.   Going forward we will need to depend on the ApplicationLayout direction since the language direction will now depend on the user's app language rather than device language and primary settings language.
It also starts some work for language settings and new use cases for analytics tracking to be done in GT-2135.
> GT-2139 Add interface strings UI to language settings

- .github/workflows/build.yml
- Gemfile.lock
- Use setup-ruby GHA action to use the version of ruby specified in .ruby-version
- add GHA macos platform to lockfile
> Use the version of ruby specified in .ruby-version

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/Articles/Presentation/ArticlesWeb/ArticleWebView.swift
- godtools/App/Features/Dashboard/Presentation/Tool/Subviews/ToolNavBar/ToolNavBarView.swift
- godtools/App/Features/DownloadTool/DownloadTool/DownloadToolView.swift
- godtools/App/Features/ToolSettings/Presentation/ShareToolScreenTutorial/ShareToolScreenTutorialView.swift
- godtools/App/Share/Common/SharedAppleExtensions/UIKit/UIViewController/UIBarButtonItem/BarButtonItemBarPosition.swift
- godtools/App/Share/Common/SharedAppleExtensions/UIKit/UIViewController/UIBarButtonItem/UIViewController+UIBarButtonItem.swift
- godtools/App/Share/Extensions/UIViewController+AppNavBackButton.swift
- godtools/App/Share/Extensions/UIViewController+LottieNavItem.swift
- godtools/App/Share/Views/LoadingView/LoadingView.swift
- godtools/App/Share/Views/Navigation/NavigationBar/AppNavigationBar.swift
- godtools/App/Share/Views/Navigation/NavigationBar/NavBarItems/NavBarItemController/AppInterfaceStringNavBarItemController.swift
- godtools/App/Share/Views/Navigation/NavigationBar/NavBarItems/NavBarItemController/AppLayoutDirectionNavBarItemController.swift
- godtools/App/Share/Views/Navigation/NavigationBar/NavBarItems/NavBarItemController/NavBarItemController.swift
- godtools/App/Share/Views/Navigation/NavigationBar/NavBarItems/NavBarItems.swift
- godtools/App/Share/Views/Navigation/ViewControllers/AppHostingController.swift
- godtools/App/Share/Views/Navigation/ViewControllers/AppViewController.swift
- Fixed a bug where the back button toggle visibility wasn't working.  Needed to add some additional checks since when redrawing bar button items they need to be removed and added back to the navigation bar.
- Renamed the bar position from left and right to leading and trailing.
- Moved nav bar items configuration into AppNavigationBar.
> GT-2102 Fix back button showing on first page of tutorial

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/AppLanguage/Data/AppLanguagesRepository/AppLanguagesRepository.swift
- godtools/App/Features/AppLanguage/Data/AppLanguagesRepository/Cache/AppLanguagesCache.swift
- godtools/App/Features/AppLanguage/DependencyContainer/AppLanguageFeatureDataLayerDependencies.swift
- godtools/App/Features/AppLanguage/Presentation/AppLanguages/AppLanguagesView.swift
- godtools/App/Features/Dashboard/Presentation/Favorites/FavoritesView.swift
- godtools/App/Features/Dashboard/Presentation/Tools/ToolsView.swift
- godtools/App/Features/Lessons/Presentation/Lessons/LessonsView.swift
- godtools/App/Features/Onboarding/Data-DomainInterface/GetOnboardingQuickStartSupportedLanguagesRepository.swift
- godtools/App/Features/Onboarding/Data/OnboardingQuickStartSupportedLanguagesRepository/Cache/OnboardingQuickStartSupportedLanguagesCache.swift
- godtools/App/Features/Onboarding/Data/OnboardingQuickStartSupportedLanguagesRepository/OnboardingQuickStartSupportedLanguagesRepository.swift
- godtools/App/Features/Onboarding/DependencyContainer/OnboardingDataLayerDependencies.swift
- godtools/App/Features/Onboarding/Presentation/OnboardingQuickStart/OnboardingQuickStartView.swift
- godtools/App/Features/Onboarding/Presentation/OnboardingTutorial/OnboardingTutorialView.swift
- godtools/App/Features/Onboarding/Presentation/OnboardingTutorial/Subviews/ChooseAppLanguageButton/InvisibleChooseAppLanguageButtonForNavigationBar.swift
- godtools/App/Features/Onboarding/Presentation/OnboardingTutorial/Subviews/OnboardingTutorialPrimaryButton/OnboardingTutorialPrimaryButton.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Flows/Onboarding/OnboardingFlow.swift
- godtools/App/Share/Application/Accessibility/AccessibilityScreenElementView.swift
- godtools/App/Share/Application/Accessibility/AccessibilityStrings.swift
- godtools/App/Share/Data/DeepLinkingService/ParsedDeepLink/ParsedDeepLinkType.swift
- godtools/App/Share/Data/DeepLinkingService/Parsers/Onboarding/OnboardingPathDeepLinkParser.swift
- godtools/App/Share/Domain/Entities/LanguageCodeDomainModel.swift
- godtools/App/Share/SwiftUI Views/FullScreenVideoView/FullScreenVideoView.swift
- godtools/App/Share/SwiftUI Views/GTBlueButton/GTBlueButton.swift
- godtoolsTests/App/Features/AppLanguage/Domain/UseCaseTests/GetInterfaceLayoutDirectionUseCaseTests.swift
- godtoolsTests/App/Share/Data/DeepLinkingService/DeepLinkingServiceTests.swift
- godtoolsUITests/App/Flows/Onboarding/OnboardingFlowTests.swift
- godtoolsUITests/Share/Extensions/XCUIApplication+Query.swift
Adding some more navigation tests for the Onboarding Flow in the GodTools-UITests Scheme.  
Navigation tests include:
- Test skipping onboarding tutorial will go to the quick starts screen if quick start is supported by the selected app language.
- Testing skipping onboarding tutorial will go to dashboard favorites if quick start is not supported by the selected app language.
- Added a SwiftUI View AccessibilityScreenElementView.swift which must be placed inside of a View that makes up a screen.  I had some issues placing the accessibility identifier on the top level View that makes up a screen.
> GT add onboarding flow ui tests

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/DownloadToolProgress/Data-DomainInterface/GetDownloadToolProgressInterfaceStringsRepository.swift
- godtools/App/Features/DownloadToolProgress/Domain/Entities/DownloadToolProgressInterfaceStringsDomainModel.swift
- godtoolsTests/App/Features/DownloadToolProgress/Data-DomainInterface/TestsGetDownloadToolProgressInterfaceStringsRepository.swift
- godtoolsTests/App/Features/DownloadToolProgress/Domain/UseCaseTests/GetDownloadToolProgressInterfaceStringsUseCaseTests.swift
When the downloading tool progress view is displayed it has 2 different types of messaging.  
- 1 messaging for downloading the latest translation for this tool. 
- Another messaging for favoriting the tool to make it available for offline use.  For this messaging to display a tool must be unfavorited and it also must be a tool that can be favorited since our ResourceModel has multiple types of tools and not all are types that can be favorited.
I wanted this logic to be part of the domain layer so I could create a behavior test.  This PR change updates the domain model to take isFavorited as an argument which will then set the download messaging based on the isFavorited argument.  This way I could create behavior tests that define which messaging should display based on the isFavorited …
> GT-2183 Move download tool messaging logic for favorited vs unfavorited into domain model

- godtools/App/Features/Dashboard/Presentation/Dashboard/DashboardView.swift
- godtools/App/Features/Dashboard/Presentation/Dashboard/DashboardViewModel.swift
- godtools/App/Features/LearnToShareTool/Presentation/LearnToShareTool/LearnToShareToolViewModel.swift
- godtools/App/Features/Onboarding/Presentation/OnboardingTutorial/OnboardingTutorialViewModel.swift
- godtools/App/Features/Tutorial/Presentation/Tutorial/TutorialViewModel.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Flows/LearnToShareTool/LearnToShareToolFlow.swift
- godtools/App/Flows/Onboarding/OnboardingFlow.swift
- godtools/App/Flows/Tutorial/TutorialFlow.swift
- godtools/App/Share/Views/Navigation/ViewControllers/AppHostingController.swift
- godtools/App/Share/Views/Navigation/ViewControllers/AppViewController.swift
- Fixed visibility toggle publisher by moving AppNavigationBar configure to UIViewController viewWillAppear().  There seemed to be some issue with accessing navigation item before viewWillAppear life cycle.
- Also removed some of the CurrentValueSubjects that were exposed on the ViewModel for toggling bar button item visibility and replaced with Published property wrappers.
> GT-2207 fix navigation bar button visibility toggle

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/ToolSettings/Data-DomainInterface/GetShareToolInterfaceStringsRepository.swift
- godtools/App/Features/ToolSettings/DependencyContainer/ToolSettingsDataLayerDependencies.swift
- godtools/App/Features/ToolSettings/DependencyContainer/ToolSettingsDomainLayerDependencies.swift
- godtools/App/Features/ToolSettings/Domain/Entities/ShareToolInterfaceStringsDomainModel.swift
- godtools/App/Features/ToolSettings/Domain/Entities/ViewShareToolDomainModel.swift
- godtools/App/Features/ToolSettings/Domain/Interfaces/GetShareToolInterfaceStringsRepositoryInterface.swift
- godtools/App/Features/ToolSettings/Domain/UseCases/ViewShareToolUseCase.swift
- godtools/App/Features/ToolSettings/Presentation/ShareTool/ShareToolView.swift
- godtools/App/Features/ToolSettings/Presentation/ShareTool/ShareToolViewModel.swift
- godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
This PR translates the interface strings in Share Tool modal to the current app language.  I had to inject the ViewShareToolDomainModel since I can't have a publisher on the UIActivityViewController.
> GT-2231 update tool options share tool modal for app language

- godtools.xcodeproj/project.pbxproj
- godtools/App/Share/Data/TranslationsRepository/TranslationsDownloadProgressDataModel.swift
- godtools/App/Share/Data/TranslationsRepository/TranslationsRepository.swift
This PR adds a way to track the download progress of translations by comparing how many translations have been downloaded against the total number of translations to download.  
Example method of downloading tool translations for a given language code with progress.
```swift
private func downloadToolTranslations(for languageCode: BCP47LanguageIdentifier) -> AnyPublisher<Double, Error> {
let includeToolTypes: [ResourceType] = [.article, .tract, .lesson, .chooseYourOwnAdventure]
let tools: [ResourceModel] = resourcesRepository.getCachedResourcesByFilter(filter: ResourcesFilter(category: nil, languageCode: languageCode, resourceTypes: includeToolTypes))
let translations: [TranslationModel] = tools.compactMap {
translationsRepository.getLatestTranslation(resourceId: $0.id, languageCode: …
```
> GT Add method to track download translations from remote with progress

- godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
- godtools/App/Share/Data/ResourcesRepository/ResourcesFilter.swift
- godtoolsTests/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCacheTests.swift
Hey @rachaelblue I added isHidden to the ResourcesFilter.  It's optional in the event we ever want to ignore filtering on isHidden, however, I set the default value to false on init() since most cases we will want to ignore tools that are marked as hidden ```attr-hidden```.
I still need to work on filtering for variants and the default variant.  Thinking about that a little more.
> GT-2233 update resource filtering to include optional isHidden

- godtools/App/Share/SwiftUI Views/TextWithLinks/BackwardsCompatibleTextWithLinks.swift
- godtools/App/Share/SwiftUI Views/TextWithLinks/TextViewLinksCoordinator.swift
- godtools/App/Share/SwiftUI Views/TextWithLinks/TextWithLinks.swift
This is pretty cool, you can mark something as ```obsoleted``` with iOS version.  This way when we move the minimum target to iOS 15 we will get an error here.
> GT Deprecate and obsolete TextWithLinks

- godtools/App/Features/AppLanguage/Presentation/LanguageSettings/LanguageSettingsViewModel.swift
- godtools/App/Flows/LanguageSettings/LanguageSettingsFlow.swift
Hey @rachaelblue found a retain cycle in LanguageSettingsViewModel.  It was a little tricky to spot, but inside of the flatMap I was capturing self which was leading to the retain cycle.  Since that UseCase is available in the scope of that flatMap (injected on init) I was able to just remove the ```self.``` capture.
I created another ticket to go through the rest of our ViewModels to make sure those aren't staying in memory.
> GT-2246 fix retain cycle in language settings

- godtools/App/Share/Data/RealmDatabase/RealmDatabase.swift
Removing the backgroundRealmPublisher on RealmDatabase.  I think this could lead to random crashes of Realm being accessed from incorrect threads when flatMapping on backgroundRealmPublisher.  
RealmDatabase has some extensions (read, write, delete) for working with publishers in the background.
> GT Remove backgroundRealmPublisher

- godtools/App/Flows/ChooseYourOwnAdventure/ChooseYourOwnAdventureFlow.swift
- godtools/App/Flows/Tract/TractFlow.swift
This PR fixes a bug when viewing a tool with primary and parallel language.  The bug occurred when the parallel language was selected in the navigation bar and when tapping tool options it would then highlight the primary language in the navigation bar.  
This is because the language selection was getting rebuilt without highlighting the selectedIndex from the viewModel.  This fix includes that.
> GT-2259 Fix opening tool options when parallel language is selected selects primary language in the navigation bar

- godtools/App/Features/Dashboard/Presentation/ChooseYourOwnAdventure/ChooseYourOwnAdventureViewModel.swift
- godtools/App/Features/Dashboard/Presentation/Tool/ToolView.swift
- godtools/App/Features/Dashboard/Presentation/Tool/ToolViewModel.swift
- godtools/App/Features/LearnToShareTool/Presentation/LearnToShareTool/LearnToShareToolViewModel.swift
- godtools/App/Features/Lessons/Presentation/Lesson/LessonViewModel.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsView.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Flows/ChooseYourOwnAdventure/ChooseYourOwnAdventureFlow.swift
- godtools/App/Flows/Flow/FlowStep.swift
- godtools/App/Flows/LearnToShareTool/LearnToShareToolFlow.swift
- godtools/App/Flows/ToolNavigation/ToolNavigationFlow.swift
- godtools/App/Flows/Tract/TractFlow.swift
- godtools/App/Services/Renderer/Navigation/MobileContentRendererNavigation.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
This task adds selectedLanguageIndex: Int to base class MobileContentPagesViewModel.  This will allow us to control which language should start as selected.
- When opening a tool from the tools list, the tool will be opened with the app language as primary and the tool filter language as parallel and the parallel language will be selected.
> GT-2222 change tool primary to app language

- godtools/App/Features/ToolDetails/Data-DomainInterface/GetToolDetailsLearnToShareToolIsAvailableRepository.swift
- godtools/App/Features/ToolDetails/Domain/Interface/GetToolDetailsLearnToShareToolIsAvailableRepositoryInterface.swift
- godtools/App/Features/ToolDetails/Domain/UseCases/GetToolDetailsLearnToShareToolIsAvailableUseCase.swift
- godtools/App/Features/ToolDetails/Presentation/ToolDetails/ToolDetailsViewModel.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Flows/ToolNavigation/ToolNavigationFlow.swift
- godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
- godtools/App/Share/Domain/UseCases/GetToolTranslationsFilesUseCase/DetermineToolTranslationsToDownload/DetermineToolTranslationsToDownload.swift
- Added a check in ToolDetaisViewModel to ensure parallel language doesn't match primary.
- Updated tool navigation flow to take a Set of languageIds instead of an Array to ensure it is unique.
- Removed AnyPublishers inputs in GetToolDetailsLearnToShareToolIsAvailableUseCase and moved those to the ViewModel and inject values instead.
> GT-2280 Fix tool parallel should not match primary

- godtools/App/Features/AppLanguage/Presentation/DownloadableLanguages/DownloadableLanguagesView.swift
- godtools/App/Features/AppLanguage/Presentation/DownloadableLanguages/DownloadableLanguagesViewModel.swift
- godtools/App/Features/AppLanguage/Presentation/DownloadableLanguages/Subviews/DownloadableLanguageItemView.swift
- godtools/App/Features/AppLanguage/Presentation/DownloadableLanguages/Subviews/LanguageDownloadIcon.swift
Current logic is that tapping once on a downloaded language should show the red "x", and tapping a second time removes the download.  Waiting to hear back from Jill if there's supposed to be a way to cancel if a user gets the "x" but doesn't want to download.  Depending on what the solution is, I'm thinking that will just be a separate ticket.
> GT-2214 Undownload language button

- godtools/App/Features/Dashboard/Presentation/ChooseYourOwnAdventure/ChooseYourOwnAdventureViewModel.swift
- godtools/App/Features/Dashboard/Presentation/Tool/ToolViewModel.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
- godtools/App/Share/Views/PageNavigationCollectionView/Models/PageNavigationCollectionViewNavigationModel.swift
- godtools/App/Share/Views/PageNavigationCollectionView/PageNavigationCollectionView.swift
When back button is pressed from a tool that is CYOA (choose your own adventure), instead of moving to the previous page in the list of pages, instead navigate back to the current pages parent page.
> GT-2294 Update cyoa back navigation to go to parent

- godtools.xcodeproj/project.pbxproj
- godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
- godtools/App/Services/WebSocket/StarscreamWebSocket.swift
- Updated versions for Lottie, Realm, Starscream, and Firebase.  Hopefully there will be a solution to automate this process for us.
- Starscream added a peerClosed for when server terminates connection which currently isn't being handled.
> GT-2306 Update swift package versions

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/ToolsFilter/Data-DomainInterface/GetToolFilterCategoriesInterfaceStringsRepository.swift
- godtools/App/Features/ToolsFilter/Data-DomainInterface/GetToolFilterLanguagesInterfaceStringsRepository.swift
- godtools/App/Features/ToolsFilter/DependencyContainer/ToolsFilterFeatureDataLayerDependencies.swift
- godtools/App/Features/ToolsFilter/DependencyContainer/ToolsFilterFeatureDomainLayerDependencies.swift
- godtools/App/Features/ToolsFilter/Domain/Entities/ToolFilterCategoriesInterfaceStringsDomainModel.swift
- godtools/App/Features/ToolsFilter/Domain/Entities/ToolFilterLanguagesInterfaceStringsDomainModel.swift
- godtools/App/Features/ToolsFilter/Domain/Entities/ViewToolFilterCategoriesDomainModel.swift
- godtools/App/Features/ToolsFilter/Domain/Entities/ViewToolFilterLanguagesDomainModel.swift
- godtools/App/Features/ToolsFilter/Domain/Interface/GetToolFilterCategoriesInterfaceStringsRepositoryInterface.swift
- godtools/App/Features/ToolsFilter/Domain/Interface/GetToolFilterLanguagesInterfaceStringsRepositoryInterface.swift
- godtools/App/Features/ToolsFilter/Domain/Interface/GetToolFilterLanguagesRepositoryInterface.swift
- godtools/App/Features/ToolsFilter/Domain/UseCases/ViewToolFilterCategoriesUseCase.swift
- godtools/App/Features/ToolsFilter/Domain/UseCases/ViewToolFilterLanguagesUseCase.swift
- godtools/App/Features/ToolsFilter/Presentation/ToolFilterCategorySelectionView/ToolFilterCategorySelectionViewModel.swift
- godtools/App/Features/ToolsFilter/Presentation/ToolFilterLanguageSelectionView/ToolFilterLanguageSelectionViewModel.swift
- godtools/App/Flows/App/AppFlow.swift
Removed `GetInterfaceStringInAppLanguageUseCase` from the 2 filter selection pages and added repos to get the interfaceStrings in each.  All the other tasks listed in the ticket were completed in a previous PR.
> GT-2298 tools filter remove deprecations

- godtools/App/Share/Common/SharedAppleExtensions/Swift/String/String+ToUrlMarkdown.swift
- godtools/App/Share/SwiftUI Views/TextWithLinks/TextWithLinksView.swift
The Tool Details about text uses an AttributedString for formatting the URLs. 
Including option ```inlineOnlyPreservingWhitespace``` appears to preserve the line breaks when creating the AttributedString.
https://developer.apple.com/documentation/foundation/attributedstring/markdownparsingoptions/interpretedsyntax/inlineonlypreservingwhitespace
> GT-2334 Fix line break not applied in Tool Details about text

- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/App/Features/AppLanguage/Data-DomainInterface/GetConfirmAppLanguageInterfaceStringsRepository.swift
- godtools/App/Features/AppLanguage/Data-DomainInterface/GetLanguageSettingsInterfaceStringsRepository.swift
- godtools/App/Features/AppLanguage/DependencyContainer/AppLanguageFeatureDataLayerDependencies.swift
- godtools/App/Features/ToolsFilter/Data-DomainInterface/GetToolFilterCategoriesRepository.swift
- godtools/App/Features/ToolsFilter/Data-DomainInterface/GetToolFilterLanguagesRepository.swift
- godtools/App/Features/ToolsFilter/DependencyContainer/ToolsFilterFeatureDataLayerDependencies.swift
This PR updates a few places where LocaleLanguageName is being used.  Since then TranslatedLanguageNameRepository has been created in order to resolve performance issues when attempting to translate languages from OneSky.
- Removes get method for fetching LocaleLanguageName from AppDataLayerDependencies in order to avoid any confusion.  Instead, TranslatedLanguageNameRepository should be used when translating a language name.
- Replaces occurrences of LocaleLanguageName with TranslatedLanguageNameRepository for translating a language name in GetConfirmAppLanguageInterfaceStringsRepository.swift, GetLanguageSettingsInterfaceStringsRepository.swift, and GetToolFilterLanguagesRepository.swift.
> GT-2335 Replace LocaleLanguageName dependency with TranslatedLanguageNameRepository

- godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
This PR adds ```private func getAllToolsListResults(filterByCategory: String?, filterByLanguageId: String?, sortByDefaultOrder: Bool) -> Results<RealmResource>``` mainly for the benefit of exposing ```Results<RealmResource>``` for using additional methods that provides.
> GT Add private method for all tools list that returns type Results<RealmResource>

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/AppLanguage/Presentation/AppLanguages/AppLanguagesViewModel.swift
- godtools/App/Features/AppLanguage/Presentation/DownloadableLanguages/DownloadableLanguagesViewModel.swift
- godtools/App/Features/ToolsFilter/Presentation/ToolFilterCategorySelectionView/ToolFilterCategorySelectionViewModel.swift
- godtools/App/Features/ToolsFilter/Presentation/ToolFilterLanguageSelectionView/ToolFilterLanguageSelectionViewModel.swift
- godtools/App/Share/SwiftUI Views/SearchBar/SearchBar.swift
- godtools/App/Share/SwiftUI Views/SearchBar/SearchBarLegacy.swift
- godtools/App/Share/SwiftUI Views/SearchBar/SearchBarView.swift
Hey @levieggertcru, this was simple enough to accomplish using the `FocusState` property wrapper, which is really cool!  But it's only available on iOS 15+, and it looked like maybe the only possible way to accomplish the same thing on iOS 14 was to use `UIViewRepresentable`, and it seemed like a lot more effort than it would be worth.  So I copied the existing SearchBar implementation into a legacy version without `FocusState` and made the changes only for iOS 15+, which also allowed me to clean up several other things in the new version.
Also fixed some glitchiness with the "Cancel" button--  the SearchBarViewModel was getting re-initialized every time the view changed, so just needed to keep a reference to it.
> GT-2116 increase search bar tap area

- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/App/Features/Articles/Presentation/ArticleCategories/ArticleCategoriesViewModel.swift
- godtools/App/Features/Articles/Presentation/Articles/ArticlesViewModel.swift
- godtools/App/Share/Data/ArticlesRepository/Categories/ArticleManifestAemRepository.swift
- godtools/App/Share/Data/ToolDownloader/ToolDownloader.swift
- godtools/App/Share/Data/TranslationsRepository/TranslationsRepository.swift
Updated the ToolDownloader to include downloading articles for offline.  Each article requires a URL to be downloaded which is found in the translation manifest.  This work includes checking to see if a downloaded translation is for an article and will then download the aem URLs for offline use.
> GT-2285 include articles in tool downloading

- godtools.xcodeproj/project.pbxproj
- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/App/DependencyContainer/AppDomainLayerDependencies.swift
- godtools/App/Features/AppLanguage/Data-DomainInterface/GetDownloadableLanguagesListRepository.swift
- godtools/App/Features/GlobalActivity/Data-DomainInterface/GetGlobalActivityThisWeekRepository.swift
- godtools/App/Features/GlobalActivity/DependencyContainer/GlobalActivityDataLayerDependencies.swift
- godtools/App/Features/Menu/Domain/UseCases/GetUserActivityBadgeUseCase/GetUserActivityBadgeUseCase.swift
- godtools/App/Features/Menu/Domain/UseCases/GetUserActivityStatsUseCase/GetUserActivityStatsUseCase.swift
- godtools/App/Features/ToolsFilter/Data-DomainInterface/GetToolFilterCategoriesRepository.swift
- godtools/App/Features/ToolsFilter/Data-DomainInterface/GetToolFilterLanguagesRepository.swift
- godtools/App/Share/Data-DomainInterface/Supporting/GetTranslatedNumberCount/GetTranslatedNumberCount.swift
This PR updates places in the app where number counts are displayed and the goal is to format those number counts based on the provided language to translate in.  This is mostly noticeable when number counts get into the thousands.
- Any number counts that aren't part of the ```.stringsdict``` are formatted using a NumberFormatter in the shared Supporting ```GetTranslatedNumberCount.swift```.
- Any number counts that are part of a ```.stringsdict``` will provide the Locale in String formatting.  Example: ```String(format: formatString, locale: Locale(identifier: localeId), numberOfTools)```
Screenshot of Global Activity using GetTranslatedNumberCount
Screenshot of downloadable languages with test count 535,123,456 and language Portuguese using String formatting with Locale.
> GT-2340 format number counts based on app language

- godtools.xcodeproj/project.pbxproj
- godtoolsTests/App/Features/ToolsFilter/Data-DomainInterface/SearchToolFilterCategoriesRepositoryTests.swift
Hey @rachaelblue this is my thinking on behavior tests for our business logic (domain interface implementations).  
This example includes tests for tools category filter searching.
These tests would mostly live in ```/godtoolsTests/App/Features/FeatureName/Data-DomainInterface/*``` to line up with the godtools target folder structure.
I will probably also include tests for the ```/App/Share/Data-DomainInterface/Supporting/*```.
This means for mocking the data layer dependencies we would need to either:
1. Create an interface to mock against.  One example of this is LocalizationServices, where GetOnboardingTutorialInterfaceStringsRepositoryTests.swift includes a mock and GetOnboardingTutorialInterfaceStringsRepository.swift points to the LocalizationServicesInterface.
That mock lives in …
> GT Add some behavior tests for tools category filter searching

- godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
- godtools/App/Services/Renderer/Views/MobileContent/Views/CardCollectionPage/MobileContentCardCollectionPageView.swift
- godtools/App/Share/Views/PageNavigationCollectionView/PageNavigationCollectionView.swift
Needed to use the did scroll to page.  Since this particular UI pages are revealed on the edges using page did appear would trigger the arrow visibility too early.
> GT-2346 Fix openers arrows disappearing too early

- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
Somewhere during a refactor of the renderer page navigation a call to ```rendererWillChangeSignal.accept()``` was removed.  This signal tells the View that the renderer is about to change and allows the View to save it's current state this way when the page renderer does change the View can restore its state.
> GT-2351 Fix openers cards resetting to card 1 when toggling language

- godtools/App/Features/LessonEvaluation/Presentation/LessonEvaluation/LessonEvaluationView.swift
- godtools/App/Features/LessonEvaluation/Presentation/LessonEvaluation/LessonEvaluationViewModel.swift
- godtools/App/Share/SwiftUI Views/ScaleValueSlider/ScaleValueSliderView.swift
In iOS 17 the lesson evaluation ready to share faith scale slider would sometimes not render.  Was about 50/50.  It seemed due to the fact that it was initially being drawn with min scale 0 and max scale 0 and when the publisher would update with actual scale values it wouldn't update the view.  However, iOS 15 this wasn't an issue.  Not sure what the difference is between iOS 17 and iOS 15, but I'm curious to explore that more.
The fix was to change the published property on the ViewModel to optional and only draw the scale slider view once we have data.
> GT-2363 Fix lesson evaluation scale slider disappearing in iOS 17

- godtools/App/Features/AppLanguage/Domain/UseCases/GetInterfaceLayoutDirectionUseCase.swift
- godtools/App/Share/Application/ApplicationLayout/ApplicationLayout.swift
As part of our architecture guidelines we will no longer be injecting publishers into UseCases as inputs.
> GT Remove publisher as argument in UseCase

- godtools/App/Features/Dashboard/Data-DomainInterface/GetToolsRepository.swift
- godtools/App/Features/Dashboard/Presentation/Tools/ToolsViewModel.swift
- godtools/App/Features/SpotlightTools/Data-DomainInterface/GetSpotlightToolsRepository.swift
This bug was interesting and something we will need to pay attention to and will need to come to some type of standard to reduce the chances of similar bugs.
The main issue was where we had the ```resourcesChanged``` observing.  When that was triggered it was taking in the scope of the language availability rather than what the true language selection was.  This was fixed by removing the observer and pushing the trigger to the top of publisher chain in the ViewModel.
Need to do some more thinking here as a way to ensure we don't introduce similar bugs like this.
> GT-2372 Fix bug where language availability checkmark was reverting to the previous language selection after a pull to refresh

- godtools/App/Features/Dashboard/Data-DomainInterface/GetToolsRepository.swift
- godtools/App/Features/Dashboard/Presentation/Tools/ToolsViewModel.swift
- godtools/App/Features/Favorites/Presentation/Favorites/FavoritesViewModel.swift
- godtools/App/Features/Lessons/Presentation/Lessons/LessonsViewModel.swift
- godtools/App/Features/SpotlightTools/Data-DomainInterface/GetSpotlightToolsRepository.swift
This bug fixes some strange behavior where interface strings in lessons and favorites were reverting back to a prior app language selection.  I also include this fix to ToolsViewModel for the language availability issue here (https://github.com/CruGlobal/godtools-swift/pull/2096/files).
These bugs had to do with how we're using Combine Published properties and flatMap and our inner Publishers using Realm objectWillChange observing.
The main fix for this was to use ```switchToLatest()``` instead of ```flatMap```. (https://developer.apple.com/documentation/combine/publisher/switchtolatest()-453ht)
A few other changes include:
- Update ```.assign(to:``` to include ```.receive(on: DispatchQueue.main)```.  Initially I thought it was okay to exclude the main thread here since UI isn't being …
> GT-2377 fix bug in favorites and lessons where data was reverting back to a previously selected app language

- godtools.xcodeproj/project.pbxproj
After adding RealmSwift 10.50.0 which embeds and signs as a framework I was getting a cycle error in the Build Phases.  Checking Copy only when installing seemed to fix the build error.  Not sure if this will introduce any other problems when building?
> GT Check Copy only when installing in Build Phases Embed Frameworks

- godtools/App/Features/SpotlightTools/Data-DomainInterface/GetSpotlightToolsRepository.swift
- godtools/App/Share/Data/ResourcesRepository/Cache/RealmResourcesCache.swift
- godtools/App/Share/Data/ResourcesRepository/ResourcesRepository.swift
- Adds flag to ResourcesRepository to fetch spotlight tools by default order.
- Updates business logic in GetSpotlightToolsRepository to sort spotlight tools by default order when fetching.
> GT-2354 Sort spotlight tools by tool order

- godtools.xcodeproj/project.pbxproj
- godtools/App/Share/Common/LocaleLanguageName/LocaleLanguageName.swift
- godtools/App/Share/Common/LocaleLanguageName/LocaleLanguageNameInterface.swift
- godtools/App/Share/Common/LocaleLanguageRegionName/LocaleLanguageRegionName.swift
- godtools/App/Share/Common/LocaleLanguageRegionName/LocaleLanguageRegionNameInterface.swift
- godtools/App/Share/Common/LocaleLanguageScriptName/LocaleLanguageScriptName.swift
- godtools/App/Share/Common/LocaleLanguageScriptName/LocaleLanguageScriptNameInterface.swift
- godtools/App/Share/Data-DomainInterface/Supporting/GetTranslatedLanguageName/GetTranslatedLanguageName.swift
- godtoolsTests/App/Share/Common/LocaleLanguageName/MockLocaleLanguageName.swift
- godtoolsTests/App/Share/Common/LocaleLanguageRegionName/MockLocaleLanguageRegionName.swift
- godtoolsTests/App/Share/Common/LocaleLanguageScriptName/MockLocaleLanguageScriptName.swift
- godtoolsTests/App/Share/Data-DomainInterface/Supporting/GetTranslatedLanguageName/GetTranslatedLanguageNameTests.swift
- godtoolsTests/App/Share/Data-DomainInterface/Supporting/GetTranslatedLanguageName/MockTranslatableLanguage.swift
This PR adds tests for GetTranslatedLanguageName.  I needed to add interfaces for the GetTranslatedLanguageName dependencies in order to mock the data for testing the behavior.
These tests will allow @gyasistory to add additional tests for changes in GT-2323.
> GT-2323 Add interfaces for GetTranslatedLanguageName in order to mock tests

- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/App/Share/Data-DomainInterface/Supporting/GetTranslatedToolCategory/GetTranslatedToolCategory.swift
- godtools/App/Share/Data/LanguagesRepository/LanguagesRepository.swift
See Jill's comment on https://jira.cru.org/browse/GT-2266 about the category not translating correctly.
The existing logic was failing because a `BCP47LanguageIdentifier` was being passed into `resource.supportsLanguage(languageId:)`.  But `languageId` isn't equivalent to `BCP47LanguageIdentifier`.  But  `BCP47LanguageIdentifier` is equivalent to `languageCode` and `localeId`, right?  I feel like we need a better way to convert/standardize this.
> convert to language ID to check if language is supported

- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/App/Share/Data-DomainInterface/Supporting/GetTranslatedToolCategory/GetTranslatedToolCategory.swift
Updated comment from Jill on https://jira.cru.org/browse/GT-2266-- tool category should always be translated in app language.
> GT-2266 always translate tool category in app language

- godtools/App/Share/Data/LocalizationLanguageNameRepository/LocalizationLanguageNameRepository.swift
Adding ```fil``` to localization language names so this can be pulled from Localization when translating the language for fil.
> GT-1800 Add fil to localization language names

- godtools/App/Features/Lessons/Data-DomainInterface/GetLessonsListRepository.swift
- godtools/App/Features/Lessons/Presentation/Lessons/LessonsViewModel.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Flows/Flow/FlowStep.swift
Fixes:
1. When clicked, lessons should open up in the chosen filter language.
2. The lesson title should be written in the filtered language rather than the app language.
> GT-2405 lesson navigation fix

- godtoolsTests/App/Share/Data-DomainInterface/Supporting/GetTranslatedLanguageName/GetTranslatedLanguageNameTests.swift
- godtoolsTests/App/Share/Data-DomainInterface/Supporting/GetTranslatedLanguageName/MockTranslatableLanguage.swift
- Adding ```forceLanguageName``` to ```MockTranslatableLanguage.swift.```
- Added test to ensure languageName is returned when forceLanguageName is true and a translation is available in both localizable strings and Locale.
- Added test to ensure fallbackName is returned when the translate in language string is empty.
- Added some additional checks in tests against localizable strings and locale.
> GT-2323 update tests to include force language name

- godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsHostingView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentButton/MobileContentButtonView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentFlowRow/MobileContentFlowRow.swift
- godtools/App/Share/Common/SharedAppleExtensions/UIKit/UIView/UIView+Constraints.swift
- godtools/App/Share/Views/PageNavigationCollectionView/PageNavigationCollectionView.swift
This PR makes a fix to buttons (```MobileContentButtonView.swift```) in the mobile content renderer to support multiple lines of text.  I noticed multiple lines of text was working correctly when buttons rendered a title only.  However, when rendering a title + icon then multiline text would fail to work and a single line of text was rendered.
The reason being, in title only mode a width constraint was being defined by applying a leading and trailing constraint to the title's parent view which allowed for multiple lines of text to render.  In title + icon mode there wasn't a width constraint being defined and the title was instead horizontally constrained to the center of the parent.  Without a defined width, the title width would stretch as far and wide as it could to account for all the …
> GT-2420 enable wrapping multi line text for buttons

- godtools/App/Share/Data/ToolDownloader/ToolDownloader.swift
This PR adds about banner animation downloading to the tool downloader process.  This will include banner animation downloads when choosing a language to download from the download languages list.
This change fixes an issue where opening a tool offline to tool details wouldn't display the banner animation.
Now when a language is chosen to download, such as English, it will include about banner animations and when an english tool is opened for the first time offline, it will display the about banner animation in tool details.
> GT-2435 Fixes banner animation not showing when opening tool for first time 

- godtools.xcodeproj/project.pbxproj
- godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
Started seeing a strange error in GitHub Actions when running tests.  Hoping updating Realm will resolve it.
StackOverflow popped up with this (https://stackoverflow.com/questions/31029255/no-space-left-on-device-error-when-compiling). 
Wondering if GitHub Actions macos is running out of space?
> GT Update realm dependency version to 20.0.0

- godtools/App/Flows/DownloadToolTranslations/DownloadToolTranslationsFlow.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesView.swift
This fixes a bug where opening tools in iOS 18 the tool content would be rendered behind the navigation bar and wasn't respecting the safe area.  To trigger the bug you would have to open a tool that wasn't downloaded. For example, honor restored and power over fear tools.
The fix is to ensure the download tool modal is completely dismissed before navigating to a tool.  Not sure if this is just something buggy in iOS 18 since this wasn't an issue in iOS 16 and iOS 17.
> GT-2456 fix tract tools expanding into navbar

- godtools.xcodeproj/project.pbxproj
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Flows/Flow+NavigateToUrl/Flow+NavigateToUrl.swift
- godtools/App/Share/Common/ExitAppToUrl/ExitAppToUrl.swift
The Facebook SDK uses method swizzling on UIApplication open url and currently FBSDK 16 is using deprecated (https://developer.apple.com/documentation/uikit/uiapplication/1622961-openurl) which has caused open url to no longer work in iOS 18.  This is a temp fix to use SwiftUI until we upgrade to FBSDK 17.3+
> GT-2458 Open URL using SwiftUI

- godtools/App/Features/Dashboard/Presentation/ChooseYourOwnAdventure/ChooseYourOwnAdventureViewModel.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
- godtools/App/Share/Views/PageNavigationCollectionView/PageNavigationCollectionView.swift
Hey @rachaelblue looks like initial page navigation was broken across the board.  The collection view needed to be reloaded when performing an initial page navigation.  Once reloaded and the data model (pageModels) aren't mutated, page navigation can be performed without the need to reload the collection view.
> GT-2438 Fix initial page navigation in renderer

- godtools.xcodeproj/project.pbxproj
- godtools/App/AppDelegate.swift
- godtools/App/main.swift
- godtoolsTests/App/TestsAppDelegate.swift
Exploring using a barebones AppDelegate when running GodTools tests. Since tests launches the simulator, it will then launch AppDelegate which performs a lot of background tasks on app startup. 
Providing a bare bones AppDelegate for tests would remove some of this unnecessary overhead.
See (https://qualitycoding.org/ios-app-delegate-testing/)
> GT add separate app delegate for tests

- Podfile.lock
- godtools.xcodeproj/project.pbxproj
- godtools/App/AppDelegate.swift
- godtools/App/DependencyContainer/AppDataLayerDependencies.swift
- godtools/App/DependencyContainer/AppDiContainer.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Flows/Flow/FlowStep.swift
- godtools/App/Preview/DependencyContainer/SwiftUIPreviewDiContainer.swift
- godtools/App/Share/Application/LaunchEnvironment/LaunchEnvironmentKey.swift
- godtools/App/Share/Application/LaunchEnvironment/LaunchEnvironmentReader.swift
- godtools/App/Share/Application/LaunchEnvironment/LaunchEnvironmentWriter.swift
- godtools/App/Share/Data/AppMessaging/AppMessagingDelegate.swift
- godtools/App/Share/Data/AppMessaging/AppMessagingInterface.swift
- godtools/App/Share/Data/AppMessaging/DisabledInAppMessaging/DisabledInAppMessaging.swift
- godtools/App/Share/Data/AppMessaging/FirebaseInAppMessaging/FirebaseInAppMessaging.swift
- godtoolsTests/App/DependencyContainer/TestsDiContainer.swift
- godtoolsUITests/App/Flows/App/AppFlowTests.swift
- godtoolsUITests/App/Flows/BaseFlowTests.swift
This PR will make in app messaging configurable.  Currently we use FirebaseInAppMessaging to display messages when the app is launched.  I believe this is interrupting some of our UI tests which do checks to see if a screen is visible and also checks for buttons to tap on the dashboard.  I'm pretty sure those in app messages are getting in the way.
> GT-2469 disable firebase messaging in UI tests

- godtools/App/Features/Dashboard/Presentation/Dashboard/DashboardView.swift
- godtools/App/Services/Analytics/AppsFlyer/AppsFlyerAnalytics.swift
- godtools/App/Services/Analytics/Firebase/FirebaseAnalytics.swift
- godtools/App/Share/Data/AppsFlyer/AppsFlyer.swift
Fixed crashes in SwiftUI Preview. Mainly were caused by assertions. 
Actually it appears AppDelegate does run.  It's just that SwiftUI uses a different AppDiContainer so those analytics were never configured which caused the assertions.
> GT fix swiftui preview

- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentTabs/MobileContentTabsViewModel.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentText/MobileContentTextView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/MobileContentViewModel.swift
- godtools/App/Services/Renderer/Views/Tract/Views/CallToAction/TractPageCallToActionViewModel.swift
- godtools/App/Services/Renderer/Views/Tract/Views/Card/TractPageCardViewModel.swift
- godtools/App/Services/Renderer/Views/Tract/Views/Header/TractPageHeaderViewModel.swift
- godtools/App/Share/Protocols/NibBased.swift
Fixed the context-text start image to respect language direction:
Example in English:
Example in Arabic:
> GT-2429 fix start image logic

- godtools/App/Features/Dashboard/Presentation/Tools/Subviews/ToolCard/ToolCardView.swift
- godtools/App/Features/Dashboard/Presentation/Tools/Subviews/ToolSpotlight/ToolSpotlightView.swift
- godtools/App/Features/Dashboard/Presentation/Tools/ToolsView.swift
- godtools/App/Features/Favorites/Presentation/AllYourFavoriteTools/AllYourFavoriteToolsView.swift
- godtools/App/Features/Favorites/Presentation/Favorites/Subviews/YourFavoriteTools/YourFavoriteToolsView.swift
- godtools/App/Share/SwiftUI Views/GTBlueButton/GTBlueButton.swift
- godtools/App/Share/SwiftUI Views/GTWhiteButton/GTWhiteButton.swift
Decreased the tool card details and open button title padding to 5 points for the favorites tool cards.
By default SwiftUI uses a system defined value when applying padding, so ended up going with 5 points (https://developer.apple.com/documentation/swiftui/view/padding(_:_:)).
> GT-2488 decrease tool tile button padding

- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentText/MobileContentTextView.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentText/MobileContentTextView.xib
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentText/Models/MobileContentTextLabelAttributes.swift
- godtools/App/Services/Renderer/Views/Tract/Views/Header/TractPageHeaderViewModel.swift
Also removed line spacing and default to system.
> GT-2482 add top and bottom padding to renderer text element

- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentStack/MobileContentStackView.swift
When attaching images to a vertical stack in the renderer, the max image width is clamped to the width of the stack minus content insets.
The issue was when clamping the max image width the difference in the content insets was also getting applied to the clamped height and this was getting done after resizing the image to the max width of the stack.
Needed to clamp the image width first and only the width and then resize the image to scale based on the clamped width.
Invalid clamping and resizing of image.
Fix which clamps max width first and then resizes the image.
> GT-1603 Fix to content image sizing in renderer stack

- godtools/App/Features/Dashboard/Presentation/Tract/TractView.swift
- godtools/App/Features/Dashboard/Presentation/Tract/TractViewModel.swift
- godtools/App/Flows/ChooseYourOwnAdventure/ChooseYourOwnAdventureFlow.swift
- godtools/App/Flows/Flow/FlowStep.swift
- godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
- godtools/App/Flows/ToolSettingsNavigationFlow/ToolSettingsNavigationFlow.swift
- godtools/App/Flows/Tract/TractFlow.swift
Allows for the language to be changed from tool settings during a screen share.
- When closing tool settings the publisher will send a screen share navigation event.
- The subscriber can now handle any locale given to it from the publisher as long as it exists in the LanguagesRepository.
> GT-1628 change tool language in screen share from tool settings

- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentButton/MobileContentButtonView.swift
- godtools/App/Share/Common/SharedAppleExtensions/UIKit/UIView/UIView+Constraints.swift
For buttons with a title and icon those will act as one element and be centered within the button.
> GT-1261 center both title and icon for renderer button

- godtools/App/Share/Data/ToolDownloader/ToolDownloader.swift
This PR addresses 2 fixes in ToolDownloader when determining the progress.
1. Originally all of the translations and articles were counted as a single request (single publisher).  Those are now broken up into individual publishers and added to the ```allRequests: [AnyPublisher<Void, Error>]``` array which is used to determine progress.
2. I decided to add a check for the downloadCount against the number of running requests and clamp the progress to 1 when downloadCount reaches the number of running requests.
> GT-2478 Fix to ToolDownloader progress

- godtools/App/Features/AppLanguage/Data/DownloadedLanguagesRepository/Cache/RealmDownloadedLanguagesCache.swift
- godtools/App/Features/AppLanguage/Data/DownloadedLanguagesRepository/DownloadedLanguagesRepository.swift
- godtools/App/Features/AppLanguage/Data/ToolLanguageDownloader/ToolLanguageDownloader.swift
The ToolLanguageDownloader sync will run anytime the app is launched from a terminated state or launched from the background past 2 hours or more.
It will fetch downloadable languages from the DownloadedLanguagesRepository and download new data (translations, attachments, articles, etc.).
When this is run I think it's a good idea to mark any downloadable language in DownloadedLanguagesRepository as downloaded completed = true.  This way if a user was downloading some languages and they either closed the app or were on a slow network connection and closed the app, the next time they launch the app the sync would mark those as completed and begin downloading data again in the background.
If they were to open up the list of downloadable languages they would see those languages they tapped on …
> GT-2478 When sync is called on ToolLanguageDownloader, mark all downloadable languages as downloaded

- godtools/App/Share/Common/SwiftUITimer/SwiftUITimer.swift
A wrapper for Timer.TimerPublisher.  
- Creates a non blocking timer which can happen when scrolling via ScrollView ```RunLoop.Mode = .common```.
- Provides a publisher that can be used to sink on and also used with SwiftUI onReceive.
- Can be stopped by cancelling the AnyCancellable.
> GT Add wrapper for TimerPublisher

- godtools/App/Features/Dashboard/Presentation/ChooseYourOwnAdventure/ChooseYourOwnAdventureViewModel.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Pages/MobileContentPagesViewModel.swift
Adds support for CYOA back navigation to navigate back to a parent page when the parent page does NOT exist in the current navigation stack.
If the parent page has an ancestor that exists in the navigation stack, CYOA will attach the parent page on top of the nearest ancestor that exists in the navigation stack and then navigate back to the parent page.
> GT-2508 cyoa support inserting parent page on back navigation

- godtools/App/Flows/DownloadToolTranslations/DownloadToolTranslationsFlow.swift
- godtools/App/Services/Renderer/Navigation/MobileContentRendererNavigation.swift
- godtools/App/Services/Renderer/Views/MobileContent/Views/Renderer/MobileContentRendererViewModel.swift
Fix to download tool modal from tool > tool settings > primary language tapped needs to download translation.
The issue was the error was produced so quickly that dismiss was called before the modal fully presented.  So a delay was added to dismiss the modal when coming from an error.
Also, sending the error from the renderer.
> GT-2541 fix download modal getting stuck

- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Share/Data/ToolDownloader/ToolDownloader.swift
This PR fixes an issue where articles couldn't be opened offline even after downloading the language from downloadable languages.
Changes include:
- Changed the article downloading to include related files when downloading against the TranslationsRepository.  I don't think this was actually necessary because I don't think articles have related files, but decided better to be safe and include true on that flag.
- Previously, tapping an article from the tools list where a tool filter language was selected would cause the article to attempt to open with app language primary and tool filter language parallel.  This meant the downloader would attempt to download both app language and tool filter language.  I've updated the flow to detect when an article is tapped and default to the tool filter …
> GT-2478 GT-2543 fix language download not fully downloading articles

- godtoolsTests/App/Features/Favorites/Data-DomainInterface/ToggleToolFavoritedRepositoryTests.swift
Removing this test because this is a scenario that should never take place.
In this test the existing favorited tools were all at position 0, however, they didn't have a set createdAt date which would never be a scenario in the app.  When storing tool in favorites, the createdAt date is set correctly.
> GT-1719 remove invalid test

- godtools.xcodeproj/project.pbxproj
- godtools/App/Services/Renderer/Views/MobileContent/Views/ContentText/MobileContentTextViewModel.swift
- godtools/App/Share/Common/SharedAppleExtensions/UIKit/UIFont/UIFont+Traits.swift
I believe using ```size: 0``` is okay here.  Seems to maintain font size. (https://developer.apple.com/documentation/uikit/uifont/init(descriptor:size:))
Before:
After:
> GT-1793 add support for italics in renderer

- godtools.xcodeproj/project.pbxproj
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Flows/Flow/FlowStep.swift
- godtools/App/Share/Common/AppLaunchObserver/AppLaunchObserver.swift
- godtools/App/Share/Common/AppLaunchObserver/AppLaunchState.swift
This PR removes the UIApplication life cycle observers from AppFlow and moves those into class AppLauncher which can now be observed using Combine.
This helps remove some code from AppFlow and also consolidates the app launch state into a single step in AppFlow rather than monitoring a step for launched from terminated state and step for launched from background state.
> GT Consolidate app launched into Combine Publisher

- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Share/Common/AppLaunchObserver/AppLaunchState.swift
In the code change that moved App launching triggering to a combine publisher I forgot to add these calls back in!
```AppBackgroundState.shared.start(appDiContainer: appDiContainer)```
```ApplicationLayout.shared.configure(appLanguageFeatureDiContainer: appDiContainer.feature.appLanguage)```
See in release 6.3.8 (https://github.com/CruGlobal/godtools-swift/blob/releases/6.3.8/godtools/App/Flows/App/AppFlow.swift#L1403)
These two calls happen on application did become active prior to invoking app launched from terminated state or background state. 
Also, loadInitialData() and countAppSessionLaunch() need to happen separately.  Either from terminated state or background state in background 2 hours or more.
> GT- Fix app launch

- godtools/App/Features/Dashboard/Data-DomainInterface/StoreInitialFavoritedTools.swift
May need to merge this PR with GT-1719. 
When storing the initial favorited tools into the repository, the next tool in the list will have a date that is later than the prior tool by 1 second.  
For example:
Store favorited resources....
index: 0
createdAtDate: 2025-04-17 20:25:43 +0000
index: 1
createdAtDate: 2025-04-17 20:25:44 +0000
index: 2
createdAtDate: 2025-04-17 20:25:45 +0000
index: 3
createdAtDate: 2025-04-17 20:25:46 +0000
This means the last added tool will show at the top of the favorites list since it has the latest created at date.  However, it was intended that the first added tool in this list is at the top of the favorites list.  
I couldn't find the exact cause for this issue that is now appearing, but it must have been a programmer error where the list wasn't getting …
> GT-1719 Need to reverse order since last favorited tool will show first

- godtools/App/Features/Dashboard/Data-DomainInterface/FavoritedToolsLatestToolDownloader.swift
- godtools/App/Share/Data/FavoritedResourcesRepository/Cache/RealmFavoritedResourcesCache.swift
- godtools/App/Share/Data/FavoritedResourcesRepository/FavoritedResourcesRepository.swift
- Updated favorited tools realm migration to use Combine Publisher and make call to writePublisher extension. I think this will resolve the crash.
- Use the fetch publisher instead of onChange publisher in FavoritedToolsLatestToolDownloader since the fetch publisher will respond to changes.
> GT 2567 fix realm crash

- godtools.xcodeproj/project.pbxproj
- godtools.xcworkspace/xcshareddata/swiftpm/Package.resolved
- godtools/App/Services/Renderer/Views/Tract/Views/Card/TractPageCardViewModel.swift
- godtools/App/Share/Application/Strings/LocalizableStringKeys.swift
This PR updates the fetch language order for prev / next in tool cards to be tool language > app language > english language.
> GT-1502 fetch prev next from translated strings

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/Lessons/Presentation/Lessons/LessonsView.swift
- godtools/App/Features/Lessons/Presentation/Lessons/LessonsViewModel.swift
- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Share/Common/SyncInvalidator/SyncInvalidator.swift
- godtools/App/Share/Common/SyncInvalidator/SyncInvalidatorTimeInterval.swift
- godtools/App/Share/Data/ResourcesRepository/Cache/Sync/RealmResourcesCacheSyncResult.swift
- godtools/App/Share/Data/ResourcesRepository/ResourcesRepository.swift
- On first fetch of latest languages, resources, and attachments and translations, those will first be fetched from the json file cache since the newest data is added to the app on first install.
Unchecked build script ```For install builds only```.  This will allow the script to run when building in Xcode.
> GT-2611 ensure resource download triggered once

- godtools.xcodeproj/project.pbxproj
- godtools/App/Features/ToolSettings/Presentation/ToolSettings/Subviews/ToolSettingsOptions/Subviews/ToolSettingsOption/ToolSettingsOption.swift
- godtools/App/Features/ToolSettings/Presentation/ToolSettings/Subviews/ToolSettingsOptions/ToolSettingsOptionsView.swift
- godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsView.swift
- godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsViewModel.swift
- Removes the 3 published properties for each tool option and instead uses an array of type ToolSettingsOption.
> GT-2434 Replaced tool options with published array of ToolSettingsOption

- godtools/App/Flows/App/AppFlow.swift
- godtools/App/Flows/Tract/TractFlow.swift
- godtools/App/Share/Data/DeepLinkingService/DeepLinkingService.swift
Removes the Legacy PassthroughValue Observer and instead uses Combine PassthroughSubject in DeepLinkingService.
Also made a fix when moving some AppFlow logic into DashboardFlow.  Deep linking to a tool from AppFlow will now go through the DashboardFlow.
> GT-2649 update deep linking to use combine publisher

- .github/workflows/run-tests.yml
- godtools.xcodeproj/xcshareddata/xcschemes/GodTools-Production.xcscheme
Changes in PR:
- Updated run tests to run xcode build against all tests and generate single xc result file for code coverage.
- Updated godtools-production scheme to default to all tests test plan.
> GT Verify tests post code coverage

- godtools/App/Features/ToolScreenShareQRCode/Presentation/ToolScreenShareQRCode/ToolScreenShareQRCodeView.swift
- godtools/App/Features/ToolSettings/Presentation/ToolSettings/ToolSettingsView.swift
- godtools/App/Flows/ToolScreenShare/ToolScreenShareFlow.swift
- godtools/App/Flows/ToolScreenShare/ToolScreenShareFlowCreateSessionTrigger.swift
- godtools/App/Flows/ToolSettings/ToolSettingsFlow.swift
- godtools/App/Flows/ToolSettingsNavigationFlow/ToolSettingsNavigationFlow.swift
- godtools/App/Share/SwiftUI Views/GTModalView/GTModalView.swift
- Added isHidden Binding to GTModalView.  This way external views can control showing / hiding the modal.
- Apply GTModalView to ToolSettingsView.
- When tapping share screen from tool settings, the tool settings view will be hidden / dismissed.
- Fixed an issue where the tool screen share session was getting created twice.  Now when tool screen share is tapped it will either start at the beginning of the tutorial if the tutorial hasn't been viewed or the last page of the tutorial with qr code option or share link option.
- Ensure screen share tutorial is dimissed before presenting next view controller. This should address where the view would sometimes delay before being presented. (https://github.com/CruGlobal/godtools-swift/blob/GT-2671-tool-settings-and-tool-screen- …
> GT-2671 tool settings and tool screen share navigation fixes and gt modal view

- godtools.xcodeproj/project.pbxproj
- godtools/App/Share/Data/DeepLinkingService/GodToolsManifest/GodToolsDeepLinkingManifest.swift
- godtools/App/Share/Data/DeepLinkingService/Manifest/DeepLinkingParserManifestUrl.swift
- godtoolsTests/App/Share/Data/DeepLinkingService/Manifest/DeepLinkingParserManifestUrlTests.swift
- godtoolsTests/Mock/App/Share/Data/DeepLinkingService/Parsers/MockEmptyDeepLinkParser.swift
This PR begins adding unit tests to the deep linking classes.
- Added unit tests for DeepLinkingParserManifestUrl.swift.
- Updated DeepLinkingParserManifestUrl to support multiple hosts (Useful for sharing same parsing logic across hosts).
> GT-2716 create tests for deep linking classes

- godtools.xcodeproj/project.pbxproj
Convert godtoolsUITests folder from group folder to buildable folder.
> GT-2723 Convert ui tests group folder to buildable folder
